### ISSUE TITLE
CNVnator make error

### ISSUE THREAD

**Issue by jjjscuedu** [abyzovlab/CNVnator#10]
Dear all,

I have successfully install root package, however, when I try to make CNVnator, there are still some errors:

/gpfs01/home/jingjing/software/root-6.04.02/include/TFitResultPtr.h: At global scope:
/gpfs01/home/jingjing/software/root-6.04.02/include/TFitResultPtr.h:38:24: error: 鈙hared_ptr?in namespace 鈙td?does not name a type
    TFitResultPtr(const std::shared_ptr<TFitResult> & p);
                        ^
/gpfs01/home/jingjing/software/root-6.04.02/include/TFitResultPtr.h:38:29: error: ISO C++ forbids declaration of 鈖arameter?with no type [-fpermissive]
    TFitResultPtr(const std::shared_ptr<TFitResult> & p);
                             ^
/gpfs01/home/jingjing/software/root-6.04.02/include/TFitResultPtr.h:38:39: error: expected ??or ?..?before ??token
    TFitResultPtr(const std::shared_ptr<TFitResult> & p);
                                       ^
/gpfs01/home/jingjing/software/root-6.04.02/include/TFitResultPtr.h:38:4: error: 釺FitResultPtr::TFitResultPtr(int)?cannot be overloaded
    TFitResultPtr(const std::shared_ptr<TFitResult> & p);
    ^
/gpfs01/home/jingjing/software/root-6.04.02/include/TFitResultPtr.h:36:4: error: with 釺FitResultPtr::TFitResultPtr(int)?
    TFitResultPtr(int status = -1): fStatus(status), fPointer(0) {};
    ^
/gpfs01/home/jingjing/software/root-6.04.02/include/TFitResultPtr.h:59:4: error: 鈙hared_ptr?in namespace 鈙td?does not name a type
    std::shared_ptr<TFitResult>  fPointer;  //! Smart Pointer to TFitResult class
    ^
/gpfs01/home/jingjing/software/root-6.04.02/include/TFitResultPtr.h: In constructor 釺FitResultPtr::TFitResultPtr(int)?
/gpfs01/home/jingjing/software/root-6.04.02/include/TFitResultPtr.h:36:53: error: class 釺FitResultPtr?does not have any field named 鈌Pointer?
    TFitResultPtr(int status = -1): fStatus(status), fPointer(0) {};
                                                     ^
In file included from /gpfs01/home/jingjing/software/root-6.04.02/include/TFormula.h:26:0,
                 from /gpfs01/home/jingjing/software/root-6.04.02/include/TF1.h:29,
                 from HisMaker.hh:23,
                 from cnvnator.cpp:8:
/gpfs01/home/jingjing/software/root-6.04.02/include/TMethodCall.h: At global scope:
/gpfs01/home/jingjing/software/root-6.04.02/include/TMethodCall.h:44:10: error: expected nested-name-specifier before 釫ReturnType?
    using EReturnType = TInterpreter::EReturnType;
          ^
/gpfs01/home/jingjing/software/root-6.04.02/include/TMethodCall.h:44:10: error: using-declaration for non-member at class scope
/gpfs01/home/jingjing/software/root-6.04.02/include/TMethodCall.h:44:22: error: expected ??before ??token
    using EReturnType = TInterpreter::EReturnType;
                      ^
/gpfs01/home/jingjing/software/root-6.04.02/include/TMethodCall.h:44:22: error: expected unqualified-id before ??token
/gpfs01/home/jingjing/software/root-6.04.02/include/TMethodCall.h:47:17: error: 釫ReturnType?does not name a type
    static const EReturnType kLong = TInterpreter::EReturnType::kLong;
                 ^
/gpfs01/home/jingjing/software/root-6.04.02/include/TMethodCall.h:48:17: error: 釫ReturnType?does not name a type
    static const EReturnType kDouble = TInterpreter::EReturnType::kDouble;
                 ^
/gpfs01/home/jingjing/software/root-6.04.02/include/TMethodCall.h:49:17: error: 釫ReturnType?does not name a type
    static const EReturnType kString = TInterpreter::EReturnType::kString;
                 ^
/gpfs01/home/jingjing/software/root-6.04.02/include/TMethodCall.h:50:17: error: 釫ReturnType?does not name a type
    static const EReturnType kOther = TInterpreter::EReturnType::kOther;
                 ^
/gpfs01/home/jingjing/software/root-6.04.02/include/TMethodCall.h:51:17: error: 釫ReturnType?does not name a type
    static const EReturnType kNoReturnType = TInterpreter::EReturnType::kNoReturnType;
                 ^
/gpfs01/home/jingjing/software/root-6.04.02/include/TMethodCall.h:53:17: error: 釫ReturnType?does not name a type
    static const EReturnType kNone = TInterpreter::EReturnType::kNoReturnType;
                 ^
/gpfs01/home/jingjing/software/root-6.04.02/include/TMethodCall.h:66:4: error: 釫ReturnType?does not name a type
    EReturnType    fRetType;   //method return type
    ^
In file included from /gpfs01/home/jingjing/software/root-6.04.02/include/TFormula.h:26:0,
                 from /gpfs01/home/jingjing/software/root-6.04.02/include/TF1.h:29,
                 from HisMaker.hh:23,
                 from cnvnator.cpp:8:
/gpfs01/home/jingjing/software/root-6.04.02/include/TMethodCall.h:98:4: error: 釫ReturnType?does not name a type
    EReturnType    ReturnType();
    ^
/gpfs01/home/jingjing/software/root-6.04.02/include/TMethodCall.h:108:22: warning: variadic templates only available with -std=c++11 or -std=gnu++11 [enabled by default]
    template <typename... T> void SetParams(const T&... params) {
                      ^
/gpfs01/home/jingjing/software/root-6.04.02/include/TMethodCall.h:108:56: warning: variadic templates only available with -std=c++11 or -std=gnu++11 [enabled by default]
    template <typename... T> void SetParams(const T&... params) {
                                                        ^
make: *** [obj/cnvnator.o] Error 1

I am not sure this is the problem because of root or CNVnator?

[jingjing@headnode src]$ echo $LD_LIBRARY_PATH
/apps/platform/lsf/9.1/linux2.6-glibc2.3-x86_64/lib:/gpfs01/software/general/libgd-2.1.0/lib::/gpfs01/home/jingjing/software/root-6.04.02//lib:/gpfs01/home/jingjing/software/root-6.04.02/lib
[jingjing@headnode src]$ echo $ROOTSYS
/gpfs01/home/jingjing/software/root-6.04.02
[jingjing@headnode src]$ which root
~/software/root-6.04.02/bin/root

Can anyone give me some suggestions?

Jingjing

**Comment by bintriz** [comment]
Dear Jingjing,

To make sure, could you let me know which release version of CNVnator you use? Only v0.3.2 is compatible with root6. For v0.3.1, you should use root5.

Thanks,
