### ISSUE TITLE
Could not visualize the specified regions

### ISSUE THREAD

**Issue by GangLiTarheel** [abyzovlab/CNVnator#100]
Hi, I am working on CNV calling on a ~100 kB region on Chr 16 with CNVnator .  I work this through your pipeline with bin size 2500. When I tried to visualize the specified region, I met the following error: 

![image](https://user-images.githubusercontent.com/31409321/35699825-31fc36dc-075f-11e8-9a6c-f97f20db9691.png)

I don't understand when such directory 'bin-2500' is made?
Any thoughts on that?

In addition, do you have any example data and scripts for this package? I just want to verify my installation is complete and the CNVnator works on my cluster.

Best,
Gang

**Comment by abyzov** [comment]
You don’t see anything for two reasons:
1) Display can’t be opened. You probably need to ssh with -X or -Y option
2) You have to visualize data form NWD100097.recab.hist.root file

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
