### ISSUE TITLE
use scrollTo in HisMaker::produceTrees

### ISSUE THREAD

**Issue by brentp** [abyzovlab/CNVnator#101]
specifying a subset of  `-chroms` with `-tree` helps cnvnator to use less memory:
eg:
```
cnvnator -root $root -chroms 1 2 3 -tree $bam
cnvnator -root $root -chroms 4 5 6 -tree $bam
cnvnator -root $root -chroms 7 8 9 10 -tree $bam
...
```
This increases the run-time because (AFAICT) it's iterating over the entire bam for each set, instead of placing an iterator at the requested start.

**Comment by abyzov** [comment]
I see. You are correct. Every time you run the CNVnator the way you described it will go through entire bam.
It is possible but not very easy to implement scroll. It would help if you can post an example of C++ code about how to scroll to a place in a bam.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by brentp** [comment]
you mean the htslib code? that's something like:

```
hts_itr_t *qiter = sam_itr_querys(idx, hdr, chrom);
for(slen = sam_itr_next(hts, qiter, b) > 0) {
   # do something with bam1_t *b
}
hts_itr_destroy(qiter)
```
