### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by waqasuddinkhan** [abyzovlab/CNVnator#103]
Hi,

My system has:

```
gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
and

```
Welcome to ROOT 6.13/01                        http://root.cern.ch |
  |                                       (c) 1995-2017, The ROOT Team |
  | Built for linuxx8664gcc                                            |
  | From heads/master@v6-11-02-1533-gee46575, févr. 08 2018, 11:51:05 |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'
```  
I used the following export commands:

```
export ROOTSYS=/home/wuk/software/root/build/bin/root
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$/home/wuk/software/root/build/bin/root
```
When I tried to run `make` within the src folder of CNVnator_v0.3, I received the following error:

```
make
g++ -m64 -DCNVNATOR_VERSION=\"v0.3\" -I/home/wuk/software/root/build/bin/root/include -Isamtools -c cnvnator.cpp -o obj/cnvnator.o
cc1plus: error: /home/wuk/software/root/build/bin/root/include: Not a directory
Makefile:34: recipe for target 'obj/cnvnator.o' failed
make: *** [obj/cnvnator.o] Error 1
```
Is it version compatibility issue? or export issue of root? Any help is highly appreciated...,,,!!!!!

Thanks,

Waqas.

**Comment by abyzov** [comment]
Hi,
from the message that you send it looks like there is a problem with directories in ROOT installation location


cc1plus: error: /home/wuk/software/root/build/bin/root/include: Not a directory



Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
