### ISSUE TITLE
GRCh38 reference

### ISSUE THREAD

**Issue by tstokowy** [abyzovlab/CNVnator#106]
Hi, I would like to use CNVnator to analyze samples aligned to GRCh38.p10. Is this possible?

--
Tomasz Stokowy
Senior Engineer
Department of Clinical Science
University of Bergen, Norway

**Comment by rmf4** [comment]
I was checking cnvnator.cpp and Genome.cpp and I can not find where GRCh38 (hg38) is applied. Moreover in the usage help code seems hg38 is not listed. Is there some piece of code that CNVnator treat this issue?

**Comment by abyzov** [comment]
Hi,
the information about the reference genome used for alignment is parsed from bam header. So, no need to worry that there is genome description in the source code. Specifying genome in command line is also not necessary.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by astulaaa** [comment]
Does that also apply to older versions? Specifically asking about v0.3.3

Thanks,
Asta

**Comment by abyzov** [comment]
Yes.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
