### ISSUE TITLE
can't find out.root file

### ISSUE THREAD

**Issue by hafizmtalha** [abyzovlab/CNVnator#107]
my commands runs completely fine but cant find out.root file in the current directory. where this file get stored ?

**Comment by abyzov** [comment]
Hi,
it should be in the current dir.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
