### ISSUE TITLE
does any one have this issue "undefined reference to png_set_..."

### ISSUE THREAD

**Issue by RuofanXia** [abyzovlab/CNVnator#108]
Hi, 
does anybody have this issue?
Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.3\" -fopenmp -o cnvnator obj/cnvnator.o obj/EXOnator.o obj/HisMaker.o obj/AliParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a samtools/htslib-1.3.1/libhts.a -lz -L/home/ruofan/Downloads/ROOT_INSTALL/root-6.13.02/obj/lib      -lCore -lRIO -lHist -lGraf -lGpad -lTree -lMathCore
/usr/bin/ld: warning: libpng16.so.16, needed by //home/ruofan/anaconda2/lib/libfreetype.so.6, not found (try using -rpath or -rpath-link)
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_set_interlace_handling@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_get_io_ptr@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_set_longjmp_fn@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_set_gray_to_rgb@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_set_read_user_transform_fn@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_get_valid@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_get_error_ptr@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_destroy_read_struct@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_set_palette_to_rgb@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_set_packing@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_read_end@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_set_read_fn@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_set_expand_gray_1_2_4_to_8@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_error@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_set_strip_16@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_create_read_struct@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_set_tRNS_to_alpha@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_set_filler@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_get_IHDR@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_create_info_struct@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_read_update_info@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_read_image@PNG16_0'
//home/ruofan/anaconda2/lib/libfreetype.so.6: undefined reference to `png_read_info@PNG16_0'
collect2: error: ld returned 1 exit status
Makefile:59: recipe for target 'cnvnator' failed
make: *** [cnvnator] Error 1
Any replies are appreciated!

**Comment by ipstone** [comment]
Hi @RuofanXia  - you have closed this - did you find the solution or what's the reason? I encountered similar problems (I guess library installation issue) when compiling another tool. Thanks
