### ISSUE TITLE
CNVnator not compiling

### ISSUE THREAD

**Issue by sitaramrajaraman** [abyzovlab/CNVnator#109]
Dear Alexej ! I tried to install CNVnator through speedseq. It compiles samtools but keeps throwing the warning that Root is not installed. I have installed it properly and can invoke it through the root command in the terminal. I have also set the ROOTSYS and LD_LIBRARY_PATH to point the respective paths. I ran the "set" command to check the following.

ROOTSYS=/opt/root_v6.12.06
LD_LIBRARY_PATH=/opt/root_v6.12.06/lib

Somehow it seems CNVnator cannot detect my root installation. Am I missing something else here?

**Comment by abyzov** [comment]
Hi,
I think that you may need to recompile CNVnator.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by sitaramrajaraman** [comment]
Hi Alexej,
   Ok I managed to do that. I had to re-create the folder structure similar to how you set up in your README and re-compile. Speedseq pipeline had it differently.  Thanks for that !
