### ISSUE TITLE
CNVnator not recognising GRCh37 aligned samples

### ISSUE THREAD

**Issue by s-boardman** [abyzovlab/CNVnator#11]
Hi,

When I run CNVnator with `-genome GRCh37` and pass the file path to the chromosome directory containing 1.fa (etc) it still tries to find 'chr1' etc as the chromosomes.

Exact command:

```
cnvnator -root sample.root -genome GRCh37 -his 10000 -d /mnt/lustre/references/speedseq/annotations/cnvnator_chroms
```

Error messages:
```
Can't open file /mnt/lustre/references/speedseq/annotations/cnvnator_chroms/chr1.fa
No chromosome/contig information parsed
Read sequence is of different length from expectation

```

I'm using v0.3 FYI.
Any ideas why this might be happening?

Thanks,

SB

**Comment by abyzov** [comment]
Hi,
the information about genome is taken from BAM header. Option -genome is only relevant when using with SAM files. Could you please check the header of the .bam you used and see how chromosomes are named. The version you are using should follow that naming.

**Comment by s-boardman** [comment]
Taking the -genome option out still gives the same error.

Bam header:

```
@HD	VN:1.3	SO:coordinate
@SQ	SN:1	LN:249250621
@SQ	SN:2	LN:243199373
@SQ	SN:3	LN:198022430
@SQ	SN:4	LN:191154276
@SQ	SN:5	LN:180915260
@SQ	SN:6	LN:171115067
@SQ	SN:7	LN:159138663
@SQ	SN:8	LN:146364022
@SQ	SN:9	LN:141213431
@SQ	SN:10	LN:135534747
@SQ	SN:11	LN:135006516
@SQ	SN:12	LN:133851895
@SQ	SN:13	LN:115169878
@SQ	SN:14	LN:107349540
@SQ	SN:15	LN:102531392
@SQ	SN:16	LN:90354753
@SQ	SN:17	LN:81195210
@SQ	SN:18	LN:78077248
@SQ	SN:19	LN:59128983
@SQ	SN:20	LN:63025520
@SQ	SN:21	LN:48129895
@SQ	SN:22	LN:51304566
@SQ	SN:X	LN:155270560
@SQ	SN:Y	LN:59373566
@SQ	SN:M	LN:16569
@RG	ID:ID	LB:pairedend	PL:ILLUMINA	PU:barcode	SM:SM
@PG	ID:bwa	PN:bwa	CL:/opt/gridware/pkg/apps/bwa/0.7.8/gcc-4.4.6/bin/bwa mem -t 1 -M -R @RG\tID:ID\tPL:ILLUMINA\tPU:barcode\tLB:pairedend\tSM:SM /mnt/lustre/references/speedseq/GRCh37/grch37.fasta /mnt/lustre/public/hiseq1/150928_SN7001250_0192_BHYGJ7ADXX/Aligned/CNV_seq/ID/fastq/SM_R1.fastq.gz /mnt/lustre/public/hiseq1/150928_SN7001250_0192_BHYGJ7ADXX/Aligned/CNV_seq/ID/fastq/SM_R2.fastq.gz	VN:0.7.8-r455
```

I can't see anything obviously wrong with that?

**Comment by abyzov** [comment]
Hi,
sorry for late reply. I was and still traveling.
Could you send me a sample file with your header and 1000 lines with alignment. I’ll debag it on my computer.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745







On Oct 27, 2015, at 6:45 PM, s-boardman <notifications@github.com<mailto:notifications@github.com>> wrote:


Taking the -genome option out still gives the same error.

Bam header:

@HD VN:1.3  SO:coordinate
@SQ SN:1    LN:249250621
@SQ SN:2    LN:243199373
@SQ SN:3    LN:198022430
@SQ SN:4    LN:191154276
@SQ SN:5    LN:180915260
@SQ SN:6    LN:171115067
@SQ SN:7    LN:159138663
@SQ SN:8    LN:146364022
@SQ SN:9    LN:141213431
@SQ SN:10   LN:135534747
@SQ SN:11   LN:135006516
@SQ SN:12   LN:133851895
@SQ SN:13   LN:115169878
@SQ SN:14   LN:107349540
@SQ SN:15   LN:102531392
@SQ SN:16   LN:90354753
@SQ SN:17   LN:81195210
@SQ SN:18   LN:78077248
@SQ SN:19   LN:59128983
@SQ SN:20   LN:63025520
@SQ SN:21   LN:48129895
@SQ SN:22   LN:51304566
@SQ SN:X    LN:155270560
@SQ SN:Y    LN:59373566
@SQ SN:M    LN:16569
@RG ID:ID   LB:pairedend    PL:ILLUMINA PU:barcode  SM:SM
@PG ID:bwa  PN:bwa  CL:/opt/gridware/pkg/apps/bwa/0.7.8/gcc-4.4.6/bin/bwa mem -t 1 -M -R @RG\tID:ID\tPL:ILLUMINA\tPU:barcode\tLB:pairedend\tSM:SM /mnt/lustre/references/speedseq/GRCh37/grch37.fasta /mnt/lustre/public/hiseq1/150928_SN7001250_0192_BHYGJ7ADXX/Aligned/CNV_seq/ID/fastq/SM_R1.fastq.gz /mnt/lustre/public/hiseq1/150928_SN7001250_0192_BHYGJ7ADXX/Aligned/CNV_seq/ID/fastq/SM_R2.fastq.gz VN:0.7.8-r455


I can't see anything obviously wrong with that?

**Comment by s-boardman** [comment]
Hi Alexej,

Yup I can do that. What's your email and I'll ping you the truncated bam.

**Comment by abyzov** [comment]
Please email to  abyzov dot alexej at mayo dot edu

**Comment by s-boardman** [comment]
Hi Alexej,

Email sent from my work account today.

**Comment by s-boardman** [comment]
Noting that updating to the latest version (0.3.2) has fixed this issue.
