### ISSUE TITLE
installation: cannot find lCore

### ISSUE THREAD

**Issue by laurabuggiotti** [abyzovlab/CNVnator#110]
Hi,

I got stuck on the second part of the installation process of CNVnator v0.3.3 and got the following error:

`Compiling with parallel (OpenMP) support
g++ -O3 -std=c++0x -DCNVNATOR_VERSION=\"v0.3.3\" -fopenmp -o cnvnator obj/cnvnator.o obj/EXOnator.o obj/HisMaker.o obj/AliParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a samtools/htslib-1.3.1/libhts.a -lz -L/opt/gridware/pkg/libs/root/5.34.30/gcc-4.4.7/include/root -lCore -lRIO -lHist -lGraf -lGpad -lTree -lMathCore
/usr/bin/ld: cannot find -lCore
collect2: ld returned 1 exit status
make: *** [cnvnator] Error 1
`
ROOTSYS=/opt/gridware/pkg/libs/root/5.34.30/gcc-4.4.7/include/root
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/gridware/pkg/libs/root/5.34.30/gcc-4.4.7/lib

Im using HPCluster and installing the package in my user environment; root v5.
Do i need to modify Makefile in order to link lCore?
Thanks in advance for your help and time,
Laura

**Comment by abyzov** [comment]
Hi,
I hope the ROOT installation works fine. If so, then you probably need to remove lCore from Makefile.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
