### ISSUE TITLE
*** Break *** segmentation violation

### ISSUE THREAD

**Issue by basharatbhat** [abyzovlab/CNVnator#112]
following error occurred while executing   "cnvnator -root out.root -genome genome.fa -tree file.bam".
Please help
I have used root v5 and v6, but error is there 

![image](https://user-images.githubusercontent.com/817965/39628766-b1ee6e9a-4fc7-11e8-870c-aa636052daee.png)

**Comment by basharatbhat** [comment]
Also,

![image](https://user-images.githubusercontent.com/817965/39635213-6ee4080e-4fda-11e8-960d-aaf57096a7e4.png)

is prompted

**Comment by abyzov** [comment]
Hi,
looks like there could be a problem with you compiler.
Which one are you using?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
