### ISSUE TITLE
cnvnator always running the GENERATING A HISTOGRAM

### ISSUE THREAD

**Issue by koujiaodahan** [abyzovlab/CNVnator#114]
my cnvnator always running the GENERATING A HISTOGRAM . other chroms finished ,but chr5 always run the steps for 7 days.
my command  as follows;
for chr in chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13
                do
                {
                  /opt/bin/CNVnator_v0.2.7/src/cnvnator -root $chr.root -chrom $chr -tree $In_bam -unique && \
                  /opt/bin/CNVnator_v0.2.7/src/cnvnator -root $chr.root -d reference -his $Bin_size && \
                  /opt/bin/CNVnator_v0.2.7/src/cnvnator -root $chr.root -stat $Bin_size && \
                  /opt/bin/CNVnator_v0.2.7/src/cnvnator -root $chr.root -partition $Bin_size && \
                  /opt/bin/CNVnator_v0.2.7/src/cnvnator -root $chr.root -call $Bin_size  > split/$chr.CNV

**Comment by abyzov** [comment]
Hi,
If chr5 may be much longer than all other chromosomes? Which does the software stuck on?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by koujiaodahan** [comment]
Oh,I try to use CNVnator3.3 instead of CNVnator2.7, which runs very fast. Why?

**Comment by abyzov** [comment]
There were couple fixes. Not sure which one made such a difference. But if it runs it is good!

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by koujiaodahan** [comment]
this step running:/opt/bin/CNVnator_v0.2.7/src/cnvnator -root chr5.root -d reference -his 100 .
