### ISSUE TITLE
After GC correction AVG RD=0 +- 0

### ISSUE THREAD

**Issue by nimarafati** [abyzovlab/CNVnator#115]
Hi,

I searched the issues posted on github and couldn't find answer to my question. 
Average RD per bin (1-22) gives a ratio between 4-5 but after GC correction it becomes "0".
Is it normal? Am I doing something wrong?
These are my commands:
cnvnator -root P4601_196.root -tree bam-files/P4601_196.clean.dedup.bam -unique 
cnvnator -root P4601_196.root -his 300 >P4601_196.hist 
cnvnator -root P4601_196.root -stat 300 -chrom 1 >P4601_196_1.stat

And last question what happens if the ratio is not between 4-5?
I will appreciate your help!

Best,
Nima

**Comment by abyzov** [comment]
Hi,
could you send the output of -stat command.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by nimarafati** [comment]
Hi,

Thanks for your reply. I noticed that this sample had large ratio compared to recommended value (4-5). 
I went through other runs that I had from past where I could see larger ratio but the average depth was calculated after GC correction.  Please let me know if I can provide more info.

Making statistics for 1 ...
Average RD per bin (1-22) is 73.2037 +- 10.1633 (before GC correction)
Average RD per bin (X,Y)  is 0 +- 0 (before GC correction)
Correcting counts by GC-content for '1' ...
Making statistics for 1 after GC correction ...
Average RD per bin (1-22) is 0 +- 0 (after GC correction)
Average RD per bin (X,Y)  is 0 +- 0 (after GC correction)


Best,
Nima

**Comment by abyzov** [comment]
Hi,
something went wrong during GC correction. What is your bin size?
Can you open .root file and see how the histogram rd_gc_binsize looks like.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by nimarafati** [comment]
Hi Alexej,
Sorry for late reply. I was away for a conference and then a meeting in
last two weeks.
I opened the root file by "root P4601_196.root"
and it is output:

Error in <TFile::Init>: file P4601_196/P4601_196.root is truncated at
2837359814 bytes: should be 2319635283072516096, trying to recover

Info in <TFile::Recover>: P4601_196/P4601_196.root, recovered key TTree:3
at address 327418583

Info in <TFile::Recover>: P4601_196/P4601_196.root, recovered key TTree:11
at address 931136387

Info in <TFile::Recover>: P4601_196/P4601_196.root, recovered key TTree:12
at address 995687835

Info in <TFile::Recover>: P4601_196/P4601_196.root, recovered key
and same for other chromosomes but with different address IDs.
I did not find rd_gc_bisize maybe I am doing something wrong because it is
my first time opening a root file.
I will appreciate your help.

Regards,
Nima

**Comment by abyzov** [comment]
Hi,
looks like your root file may be corrupted.
Try the following:
* Start ROOT
* Open Browser by typing “new TBrowser”
* Open files from the browser


Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by nimarafati** [comment]
Dear Alexej,

In our main server we have some limitations in terms of internet connection
so I had to transfer the file to visualise them.
I took few screenshots. Please check the attached files and let me know if
I can specifically look or share other info.
This is my first time opening root files so I am not 100% sure to look for
which type of data.

Regards,
Nima

**Comment by abyzov** [comment]
Hi,
there were not schreeshots attached.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by nimarafati** [comment]
Hi!

It's strange because I see the attached files. I am putting them in text
now:

[image: his_rd_p_3_300.png]
[image: his_rd_u_3_300.png]
[image: 3_position.png]
[image: 3_gc_300.png]
I hope it goes through otherwise let me know then I will share via G-drive
or dropbox.
Thanks for your help!

Regards,
Nima

**Comment by nimarafati** [comment]
Hi Alexej,

I am now directly uploading on github.
Please let me know if it is still invisible.

Regards,
Nima

![his_rd_p_3_300](https://user-images.githubusercontent.com/9595824/41703172-bc6e9bc0-7532-11e8-9d9a-ab3ad3ba4830.png)
![his_rd_u_3_300](https://user-images.githubusercontent.com/9595824/41703173-bc8893fe-7532-11e8-86b0-a22da03b4792.png)
![3_position](https://user-images.githubusercontent.com/9595824/41703175-bca771fc-7532-11e8-8174-4a0b18ebdaa3.png)
![3_gc_300](https://user-images.githubusercontent.com/9595824/41703176-bcc180d8-7532-11e8-9657-1a36cc53f105.png)

**Comment by abyzov** [comment]
Overall, everything looks normal. May be you can try rerunin the method with larger bin size.
Also, I’ve just checked our previous communication and didn’t see the output of -his command. Could you please send it.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by nimarafati** [comment]
Dear Alexej,

I am really sorry for delay (I lost a family member :( and was away).
Here is the hist file. I don't see any error. 
Please let me know if I can provide more info.

Regards,
Nima

[CNVnator_hist.txt](https://github.com/abyzovlab/CNVnator/files/2183724/CNVnator_hist.txt)

**Comment by abyzov** [comment]
Hi,
sorry to hear this!
Yes, everything looks normal. Not sure where is an issue.
Looking back into our communication, may be you should do -stat for all chromosoem rather than for chr1 only.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by nimarafati** [comment]
Thanks!
I will try it on whole genome and let you know the results as soon as I
have them.

Regards,
Nima

**Comment by nimarafati** [comment]
Dear Alexej,

Following your suggestion I ran hist and stat for all chromosomes and this
time I got calculated GC corrected RD:

Average RD per bin (1-22) is 72.0736 +- 9.84148
According to discussions in CNVnator forum and your paper I have to adjust
bin size to reach a ratio between 4-5 instead of 9.84.
I have 1000 individuals with different sequencing depth. I think, I have to
try few different bins to read ratio 4-5 for each sample separately.
Any suggestion/comment/advice?

Best regards,
Nima

**Comment by abyzov** [comment]
Hi,
sorry for late response. Yes, you have to try different bin size and the one that fits the mentioned criteria.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
