### ISSUE TITLE
output file

### ISSUE THREAD

**Issue by sususy** [abyzovlab/CNVnator#118]
Hi，
I have a simple question about the output file of each step. Here is my script after merging:
./cnvnator -root file.root -chrom chr16 -d ${ref} -his 100
./cnvnator -root file.root -chrom chr16 -stat 100
./cnvnator -root file.root -chrom chr16 -partition 100
./cnvnator -root file.root -chrom chr16 -call 100 
Will file.root be rewritten after every step? 
Thank you!

**Comment by abyzov** [comment]
Hi,
yes, the root file is updated at every step.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by sususy** [comment]
Thank you!

**Comment by abyzov** [comment]
Hi,
you have to install ROOT and use TBrowser object open the file. Please also read ROOT manual.


Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
