### ISSUE TITLE
Merging root files

### ISSUE THREAD

**Issue by sususy** [abyzovlab/CNVnator#119]
Hi,
I am not sure about the order of the steps. When I have  1000 samples, I think I should merge read mappings extracted from 1000 files, then generate histogram, calculate statistics. Or should I merge all root files after partitioning?
Thank you!

**Comment by sususy** [comment]
Also, will merging root files affect the CN result of each sample?

**Comment by abyzov** [comment]
Don’t merge.
Please do analysis per sample using separate .root files.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
