### ISSUE TITLE
Calculating histograms error

### ISSUE THREAD

**Issue by biozzq** [abyzovlab/CNVnator#12]
Deal all,
Very popular tool to call CNVs. For me, an error bothers me for a long time when running calculating histograms. My commands like following,

cnvnator -unique -root output.root -tree test.sort.dedup.realn.bam  (succeed)
cnvnator -root ouput.root -his 200 -d /ref/sep/ (failed)

and the error logs

Total of 1534005368 reads were placed.
Allocating memory ...
Done.
Calculating histograms with bin size of 200 for '1' ...
Making directory bin_200 ...
Making GC histogram for '1' ...
SysError in <TFile::Seek>: cannot seek to position -1634381530 in file ERR194147.root, retpos=-1 (Invalid argument)
SysError in <TFile::Seek>: cannot seek to position 8419450657427287862 in file ERR194147.root, retpos=-1 (Invalid argument)
Error in <TFile::ReadBuffer>: error reading all requested bytes from file ERR194147.root, got 8522541 of 67108895
Error in <TKey::ReadFile>: Failed to read data.
SysError in <TFile::Seek>: cannot seek to position -216073498781733252 in file ERR194147.root, retpos=-1 (Invalid argument)
Done.

The version I used is v0.3.2, I hope you can help me, any suggestion will be appreciated.

best wishes.

**Comment by abyzov** [comment]
Hello,
looks like your file got corrupted. Not sure about the reason. If the issue persist, the walk around is to save histograms into a different .root file. e.g.

cnvnator -root tree.root -outroot his.root -his 200 -d /ref/sep/

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by biozzq** [comment]
Dear Alexej Abyzov,

Good, it works now according to your suggestion. Thanks.
