### ISSUE TITLE
Is it possible to output copynumber generating from the step Genotyping genomic regions in a batch process?

### ISSUE THREAD

**Issue by zjgbz** [abyzovlab/CNVnator#120]
Hi CNVnator users,

I am running the step "Genotyping genomic regions" to calculate the copynumber of the regions. But the process to calculate the copynumber can only be realized one region by one region. Is it possible to calculate copynumber of multiple regions and input them to a .out file by bash or python or similar script? Thank you in advance.

Best regards,
zjgbz

**Comment by abyzov** [comment]
Please read the bottom of README file.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
