### ISSUE TITLE
CNVnator on CentOS6

### ISSUE THREAD

**Issue by fpbarthel** [abyzovlab/CNVnator#123]
Has anyone had success installing this on CentOS6 / glibc 2.12? I have been trying to install/compile CNVnator 3.3 for the past several days without any luck. I am using a NLesC ROOT 6.05 install via conda.

**Comment by abyzov** [comment]
Hi,
what is the issue that you have? Can you run ROOT?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by fpbarthel** [comment]
Initially I tried using the CNVnator release on Anaconda [here](https://anaconda.org/pwwang/cnvnator). CNVnator runs...

```
(cnvnator) barthf@helix180$ cnvnator
Not enough parameters.

CNVnator v0.3.3

Usage:

```

But returns a ROOT run-time error when trying to use it:

```
xxx (TRYING TO REPRODUCE .. )
```

This suggested to me that we need to update GLIBC to 2.15 (we are on CENTOS6 with GLIBC 2.12), so we tried that and I prepended these libraries to my `LD_LIBRARY_PATH`, however that did not resolve the issue and led to `segmentation fault (core dumped)`.

Manually overwriting the ROOT that was packaged with the `pwwang` conda install did not work either and resulted in more library errors:

```
barthf@helix180$ cnvnator.orig
cnvnator.orig: error while loading shared libraries: libImt.so: cannot open shared object file: No such file or directory
```

This suggested that there is a general OS/compiler incompatibility and that I need to recompile CNVnator from source. So for this I installed ROOT via conda, which works... 

```
(root6) barthf@helix180$ root -b -q
   ------------------------------------------------------------
  | Welcome to ROOT 6.05/02                http://root.cern.ch |
  |                               (c) 1995-2014, The ROOT Team |
  | Built for linuxx8664gcc                                    |
  | From tag v6-05-02, 14 September 2015                       |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q' |
   ------------------------------------------------------------

root [0] 

```

But when I try to compile CNVnator from source, I get the following error:

```
(root6) barthf@helix180:..../CNVnator_v0.3.3/src/samtools$ make
gcc -g -Wall -O2 -I. -Ihtslib-1.3.1  -c -o bam_index.o bam_index.c
gcc -g -Wall -O2 -I. -Ihtslib-1.3.1  -c -o bam_plcmd.o bam_plcmd.c
gcc -g -Wall -O2 -I. -Ihtslib-1.3.1  -c -o sam_view.o sam_view.c
gcc -g -Wall -O2 -I. -Ihtslib-1.3.1  -c -o bam_cat.o bam_cat.c
gcc -g -Wall -O2 -I. -Ihtslib-1.3.1  -c -o bam_md.o bam_md.c
gcc -g -Wall -O2 -I. -Ihtslib-1.3.1  -c -o bam_reheader.o bam_reheader.c
gcc -g -Wall -O2 -I. -Ihtslib-1.3.1  -c -o bam_sort.o bam_sort.c
/tmp/cczn0T9j.s: Assembler messages:
/tmp/cczn0T9j.s:12135: Error: expecting string instruction after `rep'
/tmp/cczn0T9j.s:15860: Error: expecting string instruction after `rep'
make: *** [bam_sort.o] Error 1
```

If I try using a different GCC, `src/samtools/` compiles but running `make` in `src/` returns errors. Regardless, I figure compiling ROOT and CNVnator using different compilers would give problems later on anyways. So... I should probably re-compile both ROOT6 and CNVnator from scratch? This is not really an ideal scenario and I'm hoping there is a more "portable" approach? Are there any singularity containers or conda environments for CNVnator?

**Comment by abyzov** [comment]
Hi,
not sure what is the optimal sequence of compilation steps, but for sure one need to use the same compiler version.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by fpbarthel** [comment]
Thanks
