### ISSUE TITLE
P value correction for multiple testing

### ISSUE THREAD

**Issue by chirrie** [abyzovlab/CNVnator#125]
Once you get   CNV output from CNVnator. Do one need to do p-value correction to take care of multiple testing it is already taken care of?

I am using one sample.

**Comment by abyzov** [comment]
If you analyze one sample than no correction is needed. If you analyze multiple sample then yes, correction is necessary.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by abyzov** [comment]
Using Bonferroni correction is common.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On Sep 11, 2018, at 12:24 PM, chirrie <notifications@github.com<mailto:notifications@github.com>> wrote:


Just for knowledge purposes, which correction method is suitable if someone is using more than one samples?

**Comment by chirrie** [comment]
Hii Abyzov ,

On the issue of correction due to multiple testing, is it not necessary to do it given that we analyzing RD for multiple bins or windows?

**Comment by abyzov** [comment]
Hi,
I believe you don’t need to do multiple testing correction per sample, even if you are conducting analysis with multiple different bins.
In my view the correction is only necessary when analyzing multiple samples.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
