### ISSUE TITLE
Can't open/write to file 'test.root'

### ISSUE THREAD

**Issue by qingping12** [abyzovlab/CNVnator#126]
when I run CNVnator tree command ,the error block me ,who give me some advise,thank you .
root version is 5.32
cnvnator version is  0.2.7
![image](https://user-images.githubusercontent.com/27046631/45805790-095d0a00-bcf2-11e8-81b6-a2b10cea76db.png)

**Comment by abyzov** [comment]
Hi,
it could be a problem with ROOT installation or a problem with read/write permission to the file test_0920.root. Perhaps, you can delete the file and start processing from scratch.
Please also use the latest CNVnator.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
