### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by npbhavya** [abyzovlab/CNVnator#127]
Hi, 
I am trying to compile cnvnator for the program speedseq on our cluster with  root/6.14 and  gcc/6.3.0 versions. When I run the command "make -c CNVnator" , I run into the following error 

[bhnala@c71 speedseq]$ make -C src/CNVnator

Compiling with parallel (OpenMP) support
make: Entering directory `/N/dc2/scratch/bhnala/speedseq/src/CNVnator'
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.3\" -fopenmp -o cnvnator obj/cnvnator.o obj/EXOnator.o obj/HisMaker.o obj/AliParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a samtools/htslib-1.3.1/libhts.a -lz -L/N/soft/rhel7/root/6.14/lib      -lCore -lRIO -lHist -lGraf -lGpad -lTree -lMathCore
obj/HisMaker.o: In function `HisMaker::HisMaker(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Genome*)':
HisMaker.cpp:(.text+0x48a0): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::pe_for_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, double, double)':
HisMaker.cpp:(.text+0x85d9): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::HisMaker(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, Genome*)':
HisMaker.cpp:(.text+0xadfa): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::generateView(TString, int, int, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)':
HisMaker.cpp:(.text+0xd652): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
HisMaker.cpp:(.text+0xd98f): undefined reference to `TString::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
HisMaker.cpp:(.text+0xe426): undefined reference to `TString::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::view(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, bool, bool)':
HisMaker.cpp:(.text+0xf172): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::genotype(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, bool, bool)':
HisMaker.cpp:(.text+0xf750): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::eval(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, bool, bool)':
HisMaker.cpp:(.text+0x1222a): undefined reference to `TString::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::produceHistogramsNew(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)':
HisMaker.cpp:(.text+0x137d6): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::mergeTrees(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)':
HisMaker.cpp:(.text+0x15e4a): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::callSVs(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, bool, bool, bool)':
HisMaker.cpp:(.text+0x16ada): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
HisMaker.cpp:(.text+0x16b5a): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
HisMaker.cpp:(.text+0x16bea): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o:HisMaker.cpp:(.text+0x16c6a): more undefined references to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
collect2: error: ld returned 1 exit status
make: *** [cnvnator] Error 1
make: Leaving directory `/N/dc2/scratch/bhnala/speedseq/src/CNVnator'

I have tried compiling the program with gcc/4.8.5 , root/6.14 version and I run into the error 

obj/Genome.o: In function `_GLOBAL__sub_I__ZN6Genome7genomesE':
Genome.cpp:(.text.startup+0xd7): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
Genome.cpp:(.text.startup+0x11d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
Genome.cpp:(.text.startup+0x140): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
Genome.cpp:(.text.startup+0x163): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/N/soft/rhel7/root/6.14/lib/libtbb.so.2: undefined reference to `std::length_error::length_error(char const*)@GLIBCXX_3.4.21'
/N/soft/rhel7/root/6.14/lib/libtbb.so.2: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/N/soft/rhel7/root/6.14/lib/libtbb.so.2: undefined reference to `std::invalid_argument::invalid_argument(char const*)@GLIBCXX_3.4.21'
/N/soft/rhel7/root/6.14/lib/libtbb.so.2: undefined reference to `std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'
/N/soft/rhel7/root/6.14/lib/libtbb.so.2: undefined reference to `std::out_of_range::out_of_range(char const*)@GLIBCXX_3.4.21'
/N/soft/rhel7/root/6.14/lib/libtbb.so.2: undefined reference to `std::range_error::range_error(char const*)@GLIBCXX_3.4.21'
/N/soft/rhel7/root/6.14/lib/libtbb.so.2: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
/N/soft/rhel7/root/6.14/lib/libtbb.so.2: undefined reference to `operator delete[](void*, unsigned long)@CXXABI_1.3.9'
collect2: error: ld returned 1 exit status
make: *** [cnvnator] Error 1
make: Leaving directory `/N/dc2/scratch/bhnala/speedseq/src/CNVnator'

**Comment by abyzov** [comment]
Hi,
for the first error, if you have ROOT libraries in /N/soft/rhel7/root/6.14/lib then the issue is probably using different compilers for ROOT and CNVnator,

The second error looks like problem with linking standard libraries.

You may try one of the following compiler options

CXX    = g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"$(VERSION)\" $(OMPFLAGS)

CXX    = g++ -O3 -DCNVNATOR_VERSION=\"$(VERSION)\" $(OMPFLAGS)

in the Makefile.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by jamesvanalstine** [comment]
I am running into the same issue right now with
```
g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.

ROOT: 6.22.0
cnvnator: 0.4.1
```

I compiled ROOT from source with the above compiler fine.
