### ISSUE TITLE
Can CNVnator detect gender abnormalities?

### ISSUE THREAD

**Issue by theodorc** [abyzovlab/CNVnator#129]
Hi,

A general question about how CNVnator detects how many copies of Chr X and Y is present in a WGS sample.  I tested this by artificially adding (to a NA12878 WGS bam) an equivalent amount of chrX reads so that it appears as a XXX female, and vice versa reducing reads to a X female (Turner syndrome). Running CNVnator in the above two cases didn't produce expected output of 3 copies of X or 1 copy of X.  I wonder why.

Interestingly however, in a similar experiment for a male sample, it was able to detect XYY (extra copy of Y), but not XXY (Klinefelter's syndrome). This would lead me to suspect that CNVnator can correctly call abnormalities on Y but not on X.

Could you please comment on these observations for the sex chromosomes?

Thanks,
Ted

**Comment by abyzov** [comment]
Hi,
currently CNVnator makes independent RD normalization for chr 1-22 and X&Y. So, for XXX and for X cases if would not be able to find deviations in RD, as the default assumption with the algorithm that this is normal RD. However, detection of XYY case is possible as X is much longer than Y and normalization is driven by read mapping from X.

I think it is in principle possible to introduce an option to make special consideration for sex chromosomes. I don’t think we can implement it soon, but I would suggest to submit a ticket at github.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by C4t3** [comment]
Hello,
I wanted to ask if my understanding of X-Y normalization is correct.

1- CNVnator calculate avg_coverage of all autosomes collectively on one side , then on X-Y (i.e. avg_cvg of X and Y considered together);
2- It assumes gender based on X-Y_avg_coverage: if X-Y_avg_coverage is half autosomes_avg_cvg, then it considers it male. Otherwise it considers it female.
3- It uses avg_coverage of all autosomes when calling CNVs on autosomes, while it uses avg_coverage of X-Y when calling CNVs on X or Y. Therefore:
     3.a) It calls almost-whole-Y-homoz-deletion (RD=0, except for pseudo-autosomal regions) in all females;
     3.b) copy number of the call would be: 2*RD if autosome, 2*RD if X in female, 1*RD if Y in male, 1*RD if X in male.
     3.c) it CANNOT identify: XXX, nor X0. It CAN identify XYY. 

Is all of this correct?
Could CNVnator potentially identify XXY?

Thank you
Caterina

**Comment by abyzov** [comment]
Hi,
yes this is correct.
We haven’t thought of XXY issue but we may implement such a functionality in CNVpytor (a successor of CNVnator).
Please feel free to submit a request for such a functionality.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
