### ISSUE TITLE
CNVnatorv0.3.2, root 6.04.10, Ubuntu 14.04, and make

### ISSUE THREAD

**Issue by zinj97** [abyzovlab/CNVnator#13]
I have successfully installed root version 6.04.10, and I have installed the CNVnator version of samtools but when I go to compile the CNVnator code with make I keep getting the following error. The version of Ubuntu is running BioLinux

Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.2\" -fopenmp -I/include      -Isamtools -Isamtools/htslib-1.2.1 -c cnvnator.cpp -o obj/cnvnator.o
In file included from cnvnator.cpp:14:0:
HisMaker.hh:11:20: fatal error: TFrame.h: No such file or directory
 #include <TFrame.h>
                    ^
compilation terminated.
make: *** [obj/cnvnator.o] Error 1

I get the same with make OMP=no

I realize that this was previously been associated with ROOTSYS and the  LD_LIBRARY_PATH settings but even when these are correct I get the same error.

The .TFrame.h is in the correct setting for root in /data/software/root-6.04.10/graf2d/graf/inc

set command provides the following (partial output)

GID=1014
GNOME_KEYRING_CONTROL=/run/user/1002/keyring-xVuzel
GNOME_KEYRING_PID=119570
GPG_AGENT_INFO=/run/user/1002/keyring-xVuzel/gpg:0:1
GTK_IM_MODULE=ibus
GTK_MODULES=overlay-scrollbar
HISTCHARS='!^#'
HISTCMD=723
HISTFILE=/home/philbup/.zsh_history
HISTSIZE=2000
HOME=/home/philbup
HOST=MDHS-NIX-028
IFS=' 	'
KEYBOARD_HACK=''
KEYTIMEOUT=40
LANG=en_AU.UTF-8
LANGUAGE=en_AU:en
LD_LIBRARY_PATH=/data/software/root-6.04.10/lib
LIBPATH=/data/software/root-6.04.10/lib
LINENO=377
LINES=51
LISTMAX=100
LOGCHECK=60
LOGNAME=philbup
MACHTYPE=x86_64
MAIL=/var/mail/philbup
MAILCHECK=60
MAILPATH=''
MANPATH=/data/software/root-6.04.10/man/man1:/man1:/man1:/man1:/data/software/root/man:/usr/local/man:/usr/local/share/man:/usr/share/man
MATE_DESKTOP_SESSION_ID=this-is-deprecated
MODULE_PATH=/usr/lib/x86_64-linux-gnu/zsh/5.0.2
NULLCMD=cat

Do I need to change something in the Makefile? or could be problem with the .Zsh shell?

**Comment by abyzov** [comment]
Hello,
sorry for late reply. I think you need to set shell ROOTSYS variable to the location where ROOT is installed.
For example
> echo $ROOTSYS
/Users/abyzov/bin/root-6.04.02

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745







On Dec 14, 2015, at 1:51 AM, zinj97 <notifications@github.com<mailto:notifications@github.com>> wrote:


I have successfully installed root version 60410, and I have installed the CNVnator version of samtools but when I go to compile the CNVnator code with make I keep getting the following error The version of Ubuntu is running BioLinux

Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v032\" -fopenmp -I/include -Isamtools -Isamtools/htslib-121 -c cnvnatorcpp -o obj/cnvnatoro
In file included from cnvnatorcpp:14:0:
HisMakerhh:11:20: fatal error: TFrameh: No such file or directory
#include
^
compilation terminated
make: *** [obj/cnvnatoro] Error 1

I get the same with make OMP=no

I realize that this was previously been associated with ROOTSYS and the LD_LIBRARY_PATH settings but even when these are correct I get the same error

The TFrameh is in the correct setting for root in /data/software/root-60410/graf2d/graf/inc

set command provides the following (partial output)

GID=1014
GNOME_KEYRING_CONTROL=/run/user/1002/keyring-xVuzel
GNOME_KEYRING_PID=119570
GPG_AGENT_INFO=/run/user/1002/keyring-xVuzel/gpg:0:1
GTK_IM_MODULE=ibus
GTK_MODULES=overlay-scrollbar
HISTCHARS='!^#'
HISTCMD=723
HISTFILE=/home/philbup/zsh_history
HISTSIZE=2000
HOME=/home/philbup
HOST=MDHS-NIX-028
IFS=' '
KEYBOARD_HACK=''
KEYTIMEOUT=40
LANG=en_AUUTF-8
LANGUAGE=en_AU:en
LD_LIBRARY_PATH=/data/software/root-60410/lib
LIBPATH=/data/software/root-60410/lib
LINENO=377
LINES=51
LISTMAX=100
LOGCHECK=60
LOGNAME=philbup
MACHTYPE=x86_64
MAIL=/var/mail/philbup
MAILCHECK=60
MAILPATH=''
MANPATH=/data/software/root-60410/man/man1:/man1:/man1:/man1:/data/software/root/man:/usr/local/man:/usr/local/share/man:/usr/share/man
MATE_DESKTOP_SESSION_ID=this-is-deprecated
MODULE_PATH=/usr/lib/x86_64-linux-gnu/zsh/502
NULLCMD=cat

Do I need to change something in the Makefile? or could be problem with the Zsh shell?
