### ISSUE TITLE
can cnvnator be applied to somatic ?

### ISSUE THREAD

**Issue by worker000000** [abyzovlab/CNVnator#131]
I find someone ever asked CNVnator for multiple samples
in https://github.com/abyzovlab/CNVnator/issues/77 .

I want to ask whether is it fit for cnvnator for calling cnv in just tumor sample? Because I guess it can not be applied for case-control.

Thanks a lot.

**Comment by abyzov** [comment]
Hi,
in principle yes. But CNVnator assumes that coverage is more or less the same across genome. For highly aneuploid cancer this may not be the case, which will affect RD signal normalization, and may bias results.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
