### ISSUE TITLE
error trying to install CNVnator

### ISSUE THREAD

**Issue by cacat93** [abyzovlab/CNVnator#138]
when trying to 'make' CNVnator I get the following error:

Please help with any suggestions

Compiling with NO parallel support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.3\"  -o cnvnator obj/cnvnator.o obj/EXOnator.o obj/HisMaker.o obj/AliParser.o obj/FastaParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a samtools/htslib-1.9/libhts.a -lz -lbz2 -lcurl -llzma -L/home/t/tb275/Documents/rootbuild/lib      -lCore -lRIO -lHist -lGraf -lGpad -lTree -lMathCore
/usr/bin/ld: samtools/htslib-1.9/libhts.a(thread_pool.o): undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
//usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [cnvnator] Error 1

**Comment by abyzov** [comment]
Hi,
not sure but looks like it could be related to a compiler or using different compiler to compile samtools and CNVnator.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On Feb 5, 2019, at 6:31 PM, cacat93 <notifications@github.com<mailto:notifications@github.com>> wrote:


when trying to 'make' CNVnator I get the following error:

Please help with any suggestions

Compiling with NO parallel support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION="v0.3.3" -o cnvnator obj/cnvnator.o obj/EXOnator.o obj/HisMaker.o obj/AliParser.o obj/FastaParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a samtools/htslib-1.9/libhts.a -lz -lbz2 -lcurl -llzma -L/home/t/tb275/Documents/rootbuild/lib -lCore -lRIO -lHist -lGraf -lGpad -lTree -lMathCore
/usr/bin/ld: samtools/htslib-1.9/libhts.a(thread_pool.o): undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
//usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [cnvnator] Error 1

**Comment by anthonypalacios** [comment]
I have this same issue....was there a solution or possible cause?

Thank you

**Comment by abyzov** [comment]
Hi,
I haven’t heard back from the other user. Not sure whether ensuring using the same compiler help.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by anthonypalacios** [comment]
Thank you Alexej....I am having a similar issue when compiling.

root variable exported
root library in path
gcc version = 7.4
g++ version = 4.9.4
samtools 1.10
Using htslib 1.10

make LIBS="-lcrypto" OMP-no

/usr/bin/ld: samtools/htslib-1.10/libhts.a(thread_pool.o): undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line

(make verbose output)

 obj/AliParser.o obj/FastaParser.o obj/VcfParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a samtools/htslib-1.10/libhts.a -lcrypto -lz -lbz2 -lcurl -llzma -lreadline -L/software/root/lib      -lCore -lRIO -lHist -lGraf -lGpad -lTree -lMathCore
Makefile:66: recipe for target 'cnvnator' failed

**Comment by Miajss** [comment]
I am using the same compiler version (7.4.0) for samtools and CNVnator, and still getting a similar error. 

Compiling with NO parallel support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4.1\"  -o cnvnator obj/cnvnator.o obj/EXOnator.o obj/IO.o obj/Visualizer.o obj/HisMaker.o obj/AliParser.o obj/FastaParser.o obj/VcfParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a samtools/htslib-1.10/libhts.a -lz -lbz2 -lcurl -llzma -lreadline -L/home/mia/software/yeppp-1.0.0/binaries/linux/x86_64/ -lyeppp -L/home/mia/software/root_v6.18.04.Linux-ubuntu18-x86_64-gcc7.4/root/lib      -lCore -lRIO -lHist -lGraf -lGpad -lTree -lMathCore
/usr/bin/ld: samtools/htslib-1.10/libhts.a(thread_pool.o): undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:66: recipe for target 'cnvnator' failed
make: *** [cnvnator] Error 1

Has any solution been found?

**Comment by abyzov** [comment]
Hi,
some people were eventually able to compile it but I don’t know exactly how they did it.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On Feb 10, 2020, at 5:24 PM, miajss <notifications@github.com<mailto:notifications@github.com>> wrote:


I am using the same compiler version (7.4.0) for samtools and CNVnator, and still getting a similar error.

Compiling with NO parallel support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION="v0.4.1" -o cnvnator obj/cnvnator.o obj/EXOnator.o obj/IO.o obj/Visualizer.o obj/HisMaker.o obj/AliParser.o obj/FastaParser.o obj/VcfParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a samtools/htslib-1.10/libhts.a -lz -lbz2 -lcurl -llzma -lreadline -L/home/mia/software/yeppp-1.0.0/binaries/linux/x86_64/ -lyeppp -L/home/mia/software/root_v6.18.04.Linux-ubuntu18-x86_64-gcc7.4/root/lib -lCore -lRIO -lHist -lGraf -lGpad -lTree -lMathCore
/usr/bin/ld: samtools/htslib-1.10/libhts.a(thread_pool.o): undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:66: recipe for target 'cnvnator' failed
make: *** [cnvnator] Error 1

Has any solution been found?

**Comment by suvakov** [comment]
We have similar issue before on some platforms but with different library (crypto instead pthread). Solution can be to compile with -lpthread:
 
make LIBS="-lcrypto -lpthread " 
  or without OMP:
make LIBS="-lcrypto -lpthread " OMP=no
