### ISSUE TITLE
number of repetition deleted or duplicated

### ISSUE THREAD

**Issue by shannjiang** [abyzovlab/CNVnator#139]
Hi,

I ran CNVnator on my sample and got my result as attached. As I know there is no info on the number of repetition deleted or duplicated in the result file. I am wondering if there is any way can calculate the number by using info from the CNVnator result file?

[CNVnator_result.txt](https://github.com/abyzovlab/CNVnator/files/2870216/CNVnator_result.txt)

thanks,

Shan

**Comment by abyzov** [comment]
Hi,
you can use fraction of q0 mapped reads as a proxy to repetitiveness.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
