### ISSUE TITLE
Can't find all histograms for '1'.

### ISSUE THREAD

**Issue by s-boardman** [abyzovlab/CNVnator#14]
Hi Alexej,

I've got some hg19 aligned samples and am using CNVnator running version 0.3.2.

When calling the `stat` step I get the above error `Can't find all histograms for '1'.`

Here's the commands and output (truncated to remove chrs 2-21) I'm using:

```bash
cnvnator -root sample.root -tree ../bam/sample.sorted.nodup.bam -unique
Parsing file ../bam/sample.sorted.nodup.bam ...
Allocating memory ...
Done.
Filling and saving tree for 'chr1' ...
...
Filling and saving tree for 'chr22' ...
Filling and saving tree for 'chrX' ...
Filling and saving tree for 'chrY' ...
Filling and saving tree for 'chrM' ...
Writing histograms ... 
Total of 13819118 reads were placed.
cnvnator -root sample.root -his 6000 -d /mnt/lustre/references/hg19/
Allocating memory ...
Done.
Calculating histograms with bin size of 6000 for 'chr1' ...
Making directory bin_6000 ...
Making GC histogram for 'chr1' ...
Done.
...
Calculating histograms with bin size of 6000 for 'chr22' ...
Making GC histogram for 'chr22' ...
Done.
Calculating histograms with bin size of 6000 for 'chrX' ...
Making GC histogram for 'chrX' ...
Done.
Calculating histograms with bin size of 6000 for 'chrY' ...
Making GC histogram for 'chrY' ...
Done.
Calculating histograms with bin size of 6000 for 'chrM' ...
Making GC histogram for 'chrM' ...
Done.
cnvnator -root sample.root -stat 6000
Making statistics for chr1 ...
...
Making statistics for chr22 ...
Making statistics for chrX ...
Making statistics for chrY ...
Making statistics for chrM ...
Average RD per bin (1-22) is 28.2875 +- 7.9401 (before GC correction)
Average RD per bin (X,Y)  is 14.4064 +- 5.43518 (before GC correction)
Correcting counts by GC-content for 'chr1' ...
Correcting counts by GC-content for 'chr2' ...
Correcting counts by GC-content for 'chr3' ...
Correcting counts by GC-content for 'chr4' ...
Correcting counts by GC-content for 'chr5' ...
Correcting counts by GC-content for 'chr6' ...
Correcting counts by GC-content for 'chr7' ...
Correcting counts by GC-content for 'chr8' ...
Correcting counts by GC-content for 'chr9' ...
Correcting counts by GC-content for 'chr10' ...
Correcting counts by GC-content for 'chr11' ...
Zero value of GC average.
Bin 16073 with center 9.6435e+07 is not corrected.
Correcting counts by GC-content for 'chr12' ...
Correcting counts by GC-content for 'chr13' ...
Zero value of GC average.
Bin 19071 with center 1.14423e+08 is not corrected.
Correcting counts by GC-content for 'chr14' ...
Correcting counts by GC-content for 'chr15' ...
Correcting counts by GC-content for 'chr16' ...
Correcting counts by GC-content for 'chr17' ...
Correcting counts by GC-content for 'chr18' ...
Correcting counts by GC-content for 'chr19' ...
Correcting counts by GC-content for 'chr20' ...
Correcting counts by GC-content for 'chr21' ...
Correcting counts by GC-content for 'chr22' ...
Correcting counts by GC-content for 'chrX' ...
Correcting counts by GC-content for 'chrY' ...
Correcting counts by GC-content for 'chrM' ...
Making statistics for chr1 after GC correction ...
...
Making statistics for chr22 after GC correction ...
Making statistics for chrX after GC correction ...
Making statistics for chrY after GC correction ...
Making statistics for chrM after GC correction ...
Average RD per bin (1-22) is 27.2265 +- 7.3848 (after GC correction)
Average RD per bin (X,Y)  is 12.221 +- 5.19508 (after GC correction)
Can't find all histograms for 'chr1'
```

My bam header is as follows:

```
@HD	VN:1.0	SO:coordinate
@SQ	SN:chr1	LN:249250621
@SQ	SN:chr2	LN:243199373
@SQ	SN:chr3	LN:198022430
@SQ	SN:chr4	LN:191154276
@SQ	SN:chr5	LN:180915260
@SQ	SN:chr6	LN:171115067
@SQ	SN:chr7	LN:159138663
@SQ	SN:chr8	LN:146364022
@SQ	SN:chr9	LN:141213431
@SQ	SN:chr10	LN:135534747
@SQ	SN:chr11	LN:135006516
@SQ	SN:chr12	LN:133851895
@SQ	SN:chr13	LN:115169878
@SQ	SN:chr14	LN:107349540
@SQ	SN:chr15	LN:102531392
@SQ	SN:chr16	LN:90354753
@SQ	SN:chr17	LN:81195210
@SQ	SN:chr18	LN:78077248
@SQ	SN:chr19	LN:59128983
@SQ	SN:chr20	LN:63025520
@SQ	SN:chr21	LN:48129895
@SQ	SN:chr22	LN:51304566
@SQ	SN:chrX	LN:155270560
@SQ	SN:chrY	LN:59373566
@SQ	SN:chrM	LN:16571
@RG	ID:1	PL:ILLUMINA	PU:barcode	LB:pairedend	SM:sample
```

My chromosomes directory contains chr1.fa ... chrM.fa.

I also have this same sample aligned with GRCh37 as the reference and get the same error (passing the correctly named chromosome fasta files).

Looking at the source code I can see that the error is generated when the signal, partition, or distribution names aren't set correctly ([source lines 890 & 1186](https://github.com/abyzovlab/CNVnator/blob/8263fafddac89e87b16c6f7ea9ec9a119e49c05a/HisMaker.cpp#L890)). But I'm not 100% clear why this should be the case.

**Comment by abyzov** [comment]
Hi,
this is strange. This error could only happen when one uses -partition or -call options. If you get this message when using -stat then this may imply corrupted .root file or compiled binary of CNVnator.

A quick way to check will be to rerun calculations for chr1 only, e.g.

cnvnator -root sample.root -tree ../bam/sample.sorted.nodup.bam -unique -chrom chr1
cnvnator -root sample.root -outroot sample.his.root -his 6000 -d /mnt/lustre/references/hg19/ -chrom chr1
cnvnator -root sample.his.root -stat 6000
cnvnator -root sample.his.root -partition 6000
cnvnator -root sample.his.root -call 6000

Please let me know the result.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic


On Jan 4, 2016, at 7:44 AM, s-boardman <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Alexej,

I've got some hg19 aligned samples and am using CNVnator running version 0.3.2.

When calling the stat step I get the above error Can't find all histograms for '1'.

Here's the commands and output (truncated to remove chrs 2-21) I'm using:

cnvnator -root sample.root -tree ../bam/sample.sorted.nodup.bam -unique
Parsing file ../bam/sample.sorted.nodup.bam ...
Allocating memory ...
Done.
Filling and saving tree for 'chr1' ...
...
Filling and saving tree for 'chr22' ...
Filling and saving tree for 'chrX' ...
Filling and saving tree for 'chrY' ...
Filling and saving tree for 'chrM' ...
Writing histograms ...
Total of 13819118 reads were placed.
cnvnator -root sample.root -his 6000 -d /mnt/lustre/references/hg19/
Allocating memory ...
Done.
Calculating histograms with bin size of 6000 for 'chr1' ...
Making directory bin_6000 ...
Making GC histogram for 'chr1' ...
Done.
...
Calculating histograms with bin size of 6000 for 'chr22' ...
Making GC histogram for 'chr22' ...
Done.
Calculating histograms with bin size of 6000 for 'chrX' ...
Making GC histogram for 'chrX' ...
Done.
Calculating histograms with bin size of 6000 for 'chrY' ...
Making GC histogram for 'chrY' ...
Done.
Calculating histograms with bin size of 6000 for 'chrM' ...
Making GC histogram for 'chrM' ...
Done.
cnvnator -root sample.root -stat 6000
Making statistics for chr1 ...
...
Making statistics for chr22 ...
Making statistics for chrX ...
Making statistics for chrY ...
Making statistics for chrM ...
Average RD per bin (1-22) is 28.2875 +- 7.9401 (before GC correction)
Average RD per bin (X,Y)  is 14.4064 +- 5.43518 (before GC correction)
Correcting counts by GC-content for 'chr1' ...
Correcting counts by GC-content for 'chr2' ...
Correcting counts by GC-content for 'chr3' ...
Correcting counts by GC-content for 'chr4' ...
Correcting counts by GC-content for 'chr5' ...
Correcting counts by GC-content for 'chr6' ...
Correcting counts by GC-content for 'chr7' ...
Correcting counts by GC-content for 'chr8' ...
Correcting counts by GC-content for 'chr9' ...
Correcting counts by GC-content for 'chr10' ...
Correcting counts by GC-content for 'chr11' ...
Zero value of GC average.
Bin 16073 with center 9.6435e+07 is not corrected.
Correcting counts by GC-content for 'chr12' ...
Correcting counts by GC-content for 'chr13' ...
Zero value of GC average.
Bin 19071 with center 1.14423e+08 is not corrected.
Correcting counts by GC-content for 'chr14' ...
Correcting counts by GC-content for 'chr15' ...
Correcting counts by GC-content for 'chr16' ...
Correcting counts by GC-content for 'chr17' ...
Correcting counts by GC-content for 'chr18' ...
Correcting counts by GC-content for 'chr19' ...
Correcting counts by GC-content for 'chr20' ...
Correcting counts by GC-content for 'chr21' ...
Correcting counts by GC-content for 'chr22' ...
Correcting counts by GC-content for 'chrX' ...
Correcting counts by GC-content for 'chrY' ...
Correcting counts by GC-content for 'chrM' ...
Making statistics for chr1 after GC correction ...
...
Making statistics for chr22 after GC correction ...
Making statistics for chrX after GC correction ...
Making statistics for chrY after GC correction ...
Making statistics for chrM after GC correction ...
Average RD per bin (1-22) is 27.2265 +- 7.3848 (after GC correction)
Average RD per bin (X,Y)  is 12.221 +- 5.19508 (after GC correction)
Can't find all histograms for 'chr1'

My bam header is as follows:

@HD VN:1.0  SO:coordinate
@SQ SN:chr1 LN:249250621
@SQ SN:chr2 LN:243199373
@SQ SN:chr3 LN:198022430
@SQ SN:chr4 LN:191154276
@SQ SN:chr5 LN:180915260
@SQ SN:chr6 LN:171115067
@SQ SN:chr7 LN:159138663
@SQ SN:chr8 LN:146364022
@SQ SN:chr9 LN:141213431
@SQ SN:chr10    LN:135534747
@SQ SN:chr11    LN:135006516
@SQ SN:chr12    LN:133851895
@SQ SN:chr13    LN:115169878
@SQ SN:chr14    LN:107349540
@SQ SN:chr15    LN:102531392
@SQ SN:chr16    LN:90354753
@SQ SN:chr17    LN:81195210
@SQ SN:chr18    LN:78077248
@SQ SN:chr19    LN:59128983
@SQ SN:chr20    LN:63025520
@SQ SN:chr21    LN:48129895
@SQ SN:chr22    LN:51304566
@SQ SN:chrX LN:155270560
@SQ SN:chrY LN:59373566
@SQ SN:chrM LN:16571
@RG ID:1    PL:ILLUMINA PU:barcode  LB:pairedend    SM:sample


My chromosomes directory contains chr1.fa ... chrM.fa.

I also have this same sample aligned with GRCh37 as the reference and get the same error (passing the correctly named chromosome fasta files).

Looking at the source code I can see that the error is generated when the signal, partition, or distribution names aren't set correctly (source lines 890 & 1186<https://github.com/abyzovlab/CNVnator/blob/8263fafddac89e87b16c6f7ea9ec9a119e49c05a/HisMaker.cpp#L890>). But I'm not 100% clear why this should be the case.

**Comment by s-boardman** [comment]
Hi Alexej,

Thanks for that.

Running those commands gives error free output when run from the command line. That's true for both individual chromosomes and for the whole genome.

However, when I call the commants from my wrapper script [link](https://gist.github.com/s-boardman/ad2b0da486811b39cae4) it throws the above errors.

I wonder if my `cnvnator_calling` function needs to wait between stages?

I appreciate you might not be familiar with Python, but if there's anything obvious you can see in the way I'm calling cnvnator I'd be grateful for feedback.

**Comment by abyzov** [comment]
Hi,
may be the issue is related to how python runs subprocesses.
Would it through an error if you execute only first three steps.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745



On Jan 6, 2016, at 4:18 AM, s-boardman <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Alexej,

Thanks for that.

Running those commands gives error free output when run from the command line. That's true for both individual chromosomes and for the whole genome.

However, when I call the commants from my wrapper script link<https://gist.github.com/s-boardman/ad2b0da486811b39cae4> it throws the above errors.

I wonder if my cnvnator_calling function needs to wait between stages?

I appreciate you might not be familiar with Python, but if there's anything obvious you can see in the way I'm calling cnvnator I'd be grateful for feedback.
