### ISSUE TITLE
usage of cnvnator2VCF.pl

### ISSUE THREAD

**Issue by shannjiang** [abyzovlab/CNVnator#141]
Hi Abyzov,

I have gotten my called CNV by cnvnator and am trying to use the attached perl script cnvnator2VCF.pl to transform the called CNV file to vcf file which can accommodate downstream analysis. But I am confused how to use the perl script.

As the code of cnvnator2VCF.pl shown:
_my $usage = "\tcnvnator2VCF.pl [-prefix prefix] [-reference reference_name ] file.calls [genome_dir]\n";_

There should be several arguments I need to set for the script (-prefix, -reference, file.calls, genome_dir). From my understanding, -prefix is the prefix for output .vcf file, -reference is the reference.fasta file used to call CNV, file.calls is the called out file of CNVnator, genome_dir is the output directory for the .vcf file.

So the command is:
cnvnator2VCF.pl -prefix sample1.prefix -reference 1gk_decoy_GRCh37.fasta sample1.cnvnator.out /dir/out/to/vcf

Is this right? If it is not, what's the correct command to run the perl script?

thanks,

Shan

**Comment by ShobanaSekar** [comment]
Hi Shan,

Thank you for your interest in CNVnator and apologies for our delay in getting back to you. Below are the descriptions of the script arguments:

_-prefix_ specifies a prefix string you want to append to the ID field in your output VCF. For e.g., if you set your _-prefix_ as “study1”, then your resulting ID column will be study1_CNVnator_del_1,  study1_CNVnator_del_2 etc.

_-reference_ stands for the name of reference genome you used, for e.g., GRCh37, hg19 etc. 

_file.calls_ is your CNVnator output file with the CNV calls

_genome_dir_ is the directory containing your individual reference fasta files such as 1.fa, 2.fa etc. (or chr1.fa, chr2.fa etc.)

Here is a usage example:
`cnvnator2VCF.pl -prefix study1 -reference GRCh37 sample1.cnvnator.out /path/to/individual/fasta_files`

Please let us know if you have any further questions!

Thanks,
Shobana
