### ISSUE TITLE
the value of mean to segma is not between 4 and 5

### ISSUE THREAD

**Issue by jingydz** [abyzovlab/CNVnator#144]
All my steps are right(there were no errors reported during the operation) and there seems nothing wrong.
But when I use parameter -eval,I can't make mean to Sigma between 4-5 every time, and if it's not between 4-5, should I trust my results?

**Comment by abyzov** [comment]
Hi,
yes you can trust results but with such data you are likely loosing detection power and real CNVs are likely to be fragmented in multiple calls.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On Mar 13, 2019, at 12:18 PM, jingydz <notifications@github.com<mailto:notifications@github.com>> wrote:


All my steps are right(there were no errors reported during the operation) and there seems nothing wrong.
But when I use parameter -eval,I can't make mean to Sigma between 4-5 every time, and if it's not between 4-5, should I trust my results?

**Comment by jingydz** [comment]
I am very sorry I just saw this reply, thank you very much!
