### ISSUE TITLE
partitioning of the genome

### ISSUE THREAD

**Issue by pyghost504** [abyzovlab/CNVnator#147]
I want to know if is possible to directly partition a bam file without going other processes and does it need a ref file? and also please i am finiding it a bit difficult to install CNVnator with the makefile i get this errors.
 Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4\" -fopenmp -I/include      -Isamtools -c cnvnator.cpp -o obj/cnvnator.o
cc1plus: warning: samtools: not a directory
In file included from cnvnator.cpp:13:0:
AliParser.hh:10:17: fatal error: sam.h: No such file or directory
compilation terminated.
Makefile:66: recipe for target 'obj/cnvnator.o' failed
make: *** [obj/cnvnator.o] Error 1

**Comment by abyzov** [comment]
Hi,
looks like you need to have “samtools” in inside CNVnator dir.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
