### ISSUE TITLE
adding -lcrypto to makefile

### ISSUE THREAD

**Issue by najoshi** [abyzovlab/CNVnator#148]
I needed to add -lcrypto to the makefile to get cnvnator to do the final linking step.

**Comment by abyzov** [comment]
Thanks.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
