### ISSUE TITLE
Is unique flag is deprecated and BAF calculation from root file of older version 

### ISSUE THREAD

**Issue by npatel22526** [abyzovlab/CNVnator#149]
Hello, 

I have two queries, 
I've been using  **-unique** flag  until CNVnator version 0.3.2 and after upgrade to new version I got an error "Unknown option -unique"  , is the flag no longer required ? 

Second, I see that there is BAF plotting functionality added to the latest version, would it work accurately with root files created with Older version of CNVnator. 

Thanks, 
Nick

**Comment by suvakov** [comment]
Hi Nick,

In v0.4 flag -unique is set by default and does not exist any more as an option.

Importing variant data from VCF file (options -vcf -idvar -mask), plotting BAF, and python tool plotbaf.py should work properly with old root files.  If not, please let us know. 

Thanks,
Milovan

**Comment by npatel22526** [comment]
Perfect !! Thanks  for clarification.
