### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SKM-bio** [abyzovlab/CNVnator#15]
Hi I tried installing CNVnator and ended with the following error. I am newbie to such analysis and trying to use CNVnator for CNV detections. Please help me to fix this. 

g++ -m64 -DCNVNATOR_VERSION=\"v0.3\" -I/wrk/../CNV_dir/CNVnator_v0.3/root//include -Isamtools -c cnvnator.cpp -o obj/cnvnator.o
g++ -m64 -DCNVNATOR_VERSION=\"v0.3\" -I/wrk/../CNV_dir/CNVnator_v0.3/root//include -Isamtools -c HisMaker.cpp -o obj/HisMaker.o
g++ -m64 -DCNVNATOR_VERSION=\"v0.3\" -I/wrk/../CNV_dir/CNVnator_v0.3/root//include -Isamtools -c AliParser.cpp -o obj/AliParser.o
g++ -m64 -DCNVNATOR_VERSION=\"v0.3\" -I/wrk/../CNV_dir/CNVnator_v0.3/root//include -Isamtools -c Genotyper.cpp -o obj/Genotyper.o
g++ -m64 -DCNVNATOR_VERSION=\"v0.3\" -I/wrk/../CNV_dir/CNVnator_v0.3/root//include -Isamtools -c Interval.cpp -o obj/Interval.o
g++ -m64 -DCNVNATOR_VERSION=\"v0.3\" -I/wrk/../CNV_dir/CNVnator_v0.3/root//include -Isamtools -c Genome.cpp -o obj/Genome.o
g++ -m64 -DCNVNATOR_VERSION=\"v0.3\" -o cnvnator obj/cnvnator.o obj/HisMaker.o obj/AliParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a -lz -L/wrk/../CNV_dir/CNVnator_v0.3/root//lib -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lMatrix -lPhysics -lMathCore -lThread -lGui
/wrk/../CNV_dir/CNVnator_v0.3/root//lib/libCore.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
collect2: error: ld returned 1 exit status
make: *** [cnvnator] Error 1

Best regards,
SKM

**Comment by bintriz** [comment]
Could you let me know which version of root you used to compile?

**Comment by SKM-bio** [comment]
It is root_v6.06.00

**Comment by SKM-bio** [comment]
I tried the same in Linux and the make ended with error again:

g++ -m64 -DCNVNATOR_VERSION=\"v0.3\" -o cnvnator obj/cnvnator.o obj/HisMaker.o obj/AliParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a -lz -
../CNVnator_v0.3/root/lib -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lMatrix -lPhysics -lMathCore -lThread -lGui
../CNVnator_v0.3/root/lib/libCore.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
collect2: error: ld returned 1 exit status
make: *** [cnvnator] Error 1


Please help me with the installation.

**Comment by abyzov** [comment]
Hi,
could you please let us know which version of gcc or g++ you are using, e.g. 'g++ -v’ or ‘gcc -v’.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745







On Jan 26, 2016, at 7:45 AM, SKM-bio <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried the same in Linux and the make ended with error again:

g++ -m64 -DCNVNATOR_VERSION=\"v0.3\" -o cnvnator obj/cnvnator.o obj/HisMaker.o obj/AliParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a -lz -
../CNVnator_v0.3/root/lib -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lMatrix -lPhysics -lMathCore -lThread -lGui
../CNVnator_v0.3/root/lib/libCore.so: undefined reference to `std::__throw_out_of_range_fmt(char const, ...)@GLIBCXX_3.4.20'
collect2: error: ld returned 1 exit status
make: ** [cnvnator] Error 1

Please help me with the installation.

**Comment by SKM-bio** [comment]
gcc version 4.7.2 (GCC)

**Comment by SKM-bio** [comment]
Hi 
upgraded the gcc to gcc version 4.9.3 and now it works.

**Comment by abyzov** [comment]
Glad to hear this!

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745







On Jan 28, 2016, at 3:25 AM, SKM-bio <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi
upgraded the gcc to gcc version 4.9.3 and now it works.

**Comment by oeco28** [comment]
Hello,
  I am running into similar problems while compiling CNVnator_v0.3.3.
   I am compiling with ROOT version 6.08/06 and gcc/6.1.0 and I am obtaining a similar error when I run:
$ make OMP=no

Compiling with NO parallel support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.3\"  -I/data/cornejo/projects/programs/Structural/root/include      -Isamtools -Isamtools/htslib-1.3.1 -c cnvnator.cpp -o obj/cnvnator.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.3\"  -I/data/cornejo/projects/programs/Structural/root/include      -Isamtools -Isamtools/htslib-1.3.1 -c EXOnator.cpp -o obj/EXOnator.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.3\"  -I/data/cornejo/projects/programs/Structural/root/include      -Isamtools -Isamtools/htslib-1.3.1 -c HisMaker.cpp -o obj/HisMaker.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.3\"  -I/data/cornejo/projects/programs/Structural/root/include      -Isamtools -Isamtools/htslib-1.3.1 -c AliParser.cpp -o obj/AliParser.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.3\"  -I/data/cornejo/projects/programs/Structural/root/include      -Isamtools -Isamtools/htslib-1.3.1 -c Genotyper.cpp -o obj/Genotyper.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.3\"  -I/data/cornejo/projects/programs/Structural/root/include      -Isamtools -Isamtools/htslib-1.3.1 -c Interval.cpp -o obj/Interval.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.3\"  -I/data/cornejo/projects/programs/Structural/root/include      -Isamtools -Isamtools/htslib-1.3.1 -c Genome.cpp -o obj/Genome.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.3\"  -o cnvnator obj/cnvnator.o obj/EXOnator.o obj/HisMaker.o obj/AliParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a samtools/htslib-1.3.1/libhts.a -lz -L/data/cornejo/projects/programs/Structural/root/lib      -lCore -lRIO -lHist -lGraf -lGpad -lTree -lMathCore
/usr/bin/ld: samtools/htslib-1.3.1/libhts.a(thread_pool.o): undefined reference to symbol 'pthread_kill@@GLIBC_2.2.5'
/usr/bin/ld: note: 'pthread_kill@@GLIBC_2.2.5' is defined in DSO /usr/lib64/libpthread.so.0 so try adding it to the linker command line
/usr/lib64/libpthread.so.0: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make: *** [cnvnator] Error 1


If I remove the constraint of OMP=no and compile after loading mpi/openmp/1.10.1, I get the following error:

Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.3\" -fopenmp -o cnvnator obj/cnvnator.o obj/EXOnator.o obj/HisMaker.o obj/AliParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a samtools/htslib-1.3.1/libhts.a -lz -L/data/cornejo/projects/programs/Structural/root/lib      -lCore -lRIO -lHist -lGraf -lGpad -lTree -lMathCore
obj/HisMaker.o: In function `HisMaker::HisMaker(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Genome*)':
HisMaker.cpp:(.text+0x47a0): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::pe_for_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, double, double)':
HisMaker.cpp:(.text+0x8521): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::HisMaker(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, Genome*)':
HisMaker.cpp:(.text+0xae0a): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::generateView(TString, int, int, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)':
HisMaker.cpp:(.text+0xd6f5): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
HisMaker.cpp:(.text+0xda37): undefined reference to `TString::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
HisMaker.cpp:(.text+0xe4d6): undefined reference to `TString::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::view(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, bool, bool)':
HisMaker.cpp:(.text+0xf24a): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::genotype(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, bool, bool)':
HisMaker.cpp:(.text+0xf830): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::eval(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, bool, bool)':
HisMaker.cpp:(.text+0x1238a): undefined reference to `TString::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::produceHistogramsNew(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)':
HisMaker.cpp:(.text+0x1397d): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::mergeTrees(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)':
HisMaker.cpp:(.text+0x1618a): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o: In function `HisMaker::callSVs(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, bool, bool, bool)':
HisMaker.cpp:(.text+0x16e1a): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
HisMaker.cpp:(.text+0x16e9a): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
HisMaker.cpp:(.text+0x16f2a): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/HisMaker.o:HisMaker.cpp:(.text+0x16faa): more undefined references to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
collect2: error: ld returned 1 exit status
make: *** [cnvnator] Error 1

has anybody seeing something similar?
thank you,
Omar

**Comment by abyzov** [comment]
Hi,
looks like this is a problem at linking stage.
Can’t diagnose the problem at the moment. Users reported issues with i) new GCC compiler; ii) with ROOT v6; iii) and with new samtools.

Cold you also try uncommenting the following line in Makefile

#CXX    = g++ -O3 -DCNVNATOR_VERSION=\"$(VERSION)\" $(OMPFLAGS)

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by HelenCousins** [comment]
Hi, I hav very similar errors beginning with 
g++ -pthread -m64 -DCNVNATOR_VERSION=\"v0.3\" -o cnvnator obj/cnvnator.o obj/HisMaker.o obj/AliParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a -lz -L/software/root-6.08.06//lib/root -lCore -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lMatrix -lPhysics -lMathCore -lThread -lGui
obj/cnvnator.o: In function `__static_initialization_and_destruction_0(int, int)':
cnvnator.cpp:(.text+0x268f): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

I have gcc 6.2.0 or 6.3.0, I could have other versions, which would you recommend?  I'm using root 6.08.06, again other versions exist and could be used if you could recommend one

**Comment by abyzov** [comment]
Hi,
I use the following on Mac

> g++ -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

> root
   ------------------------------------------------------------
  | Welcome to ROOT 6.04/02                http://root.cern.ch |
  |                               (c) 1995-2014, The ROOT Team |
  | Built for macosx64                                         |
  | From tag v6-04-02, 14 July 2015                            |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q' |
   ------------------------------------------------------------

root [0]

and the following on Linux

g++ -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC)

root
  *******************************************
  *                                         *
  *        W E L C O M E  to  R O O T       *
  *                                         *
  *   Version   5.34/36      5 April 2016   *
  *                                         *
  *  You are welcome to visit our Web site  *
  *          http://root.cern.ch            *
  *                                         *
  *******************************************

ROOT 5.34/36 (v5-34-36@v5-34-36, Apr 05 2016, 10:25:45 on linuxx8664gcc)

CINT/ROOT C/C++ Interpreter version 5.18.00, July 2, 2010
Type ? for help. Commands must be C++ statements.
Enclose multiple statements between { }.

root [0]


Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by HelenCousins** [comment]
I'm on RHEL7.3 and the earliest gcc I can make work is 4.8.5  I have installed Root 5.34/36 and set up ROOTSYS  I have errors beginning:
g++ -pthread -m64 -DCNVNATOR_VERSION=\"v0.3\" -o cnvnator obj/cnvnator.o obj/HisMaker.o obj/AliParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a -lz -L/software/root-5.34.36//lib/root -lCore -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lMatrix -lPhysics -lMathCore -lThread -lGui -lCint
obj/cnvnator.o: In function `main':
cnvnator.cpp:(.text+0x4d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'

**Comment by abyzov** [comment]
Hi,
not sure about the cause. It could be that you need to add an option to the compiler to use standard library.
On Mac I’m doing it the following way

-std=c++11

e.g.,

g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"$(VERSION)\" $(OMPFLAGS)

in the Makefile

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by bhuwankhatri11** [comment]
Hi, 
I got this error in second stage of make command in src directory. The make command worked fine in samtools directory. What might be the problem?

```
Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.3\" -fopenmp -I/include      -Isamtools -Isamtools/htslib-1.3.1 -c cnvnator.cpp -o obj/cnvnator.o
cc1plus: error: unrecognized command line option "-std=c++11"
make: *** [obj/cnvnator.o] Error 1
```

**Comment by abyzov** [comment]
Likely you can simply remove -std=c++11 from compiler command.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by weihongqi** [comment]
Just a solution that worked in my situation:

On an Ubuntu box (3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux) I tried to compile CNVnator_v0.3.3 and got similar errors:
"/usr/bin/ld: samtools/htslib-1.3.1/libhts.a(thread_pool.o): undefined reference to symbol 'pthread_kill@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line"

After appending -lpthread to the makefile GCC flags, the problem was solved

CXX    = g++ -O3 -std=c++11 -lpthread -DCNVNATOR_VERSION=\"$(VERSION)\" $(OMPFLAGS)

gcc version 4.9.2 (Debian 4.9.2-10+deb8u1)
root_v6.12.06

**Comment by abyzov** [comment]
Thanks!

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745




On Mar 5, 2018, at 4:31 AM, weihongqi <notifications@github.com<mailto:notifications@github.com>> wrote:


Just a solution that worked in my situation:

On an Ubuntu box (3.16.0-5-amd64 #1<https://github.com/abyzovlab/CNVnator/pull/1> SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux) I tried to compile CNVnator_v0.3.3 and got similar errors:
"/usr/bin/ld: samtools/htslib-1.3.1/libhts.a(thread_pool.o): undefined reference to symbol 'pthread_kill@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line"

After appending -lpthread to the makefile GCC flags, the problem was solved

CXX = g++ -O3 -std=c++11 -lpthread -DCNVNATOR_VERSION="$(VERSION)" $(OMPFLAGS)

gcc version 4.9.2 (Debian 4.9.2-10+deb8u1)
root_v6.12.06
