### ISSUE TITLE
If I install cnvnator using different version of root, will the cnvnator output different results?

### ISSUE THREAD

**Issue by shenjia1** [abyzovlab/CNVnator#150]
Hello:
I installed cnvnator 0.3.3 using different version of root (root 6.14 and root 6.16).
When I ran the two cnvnator with the same data, it generated different results.
And the cnvnator with root 6.16 threw out the warning like "Unknown option '-unique'."

I feel confused with this thing. Could you help me? Thanks

**Comment by abyzov** [comment]
Hi,
in the recent version the option -unique is default.
How much are the results different?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On Apr 26, 2019, at 3:02 AM, shenjia <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello:
I installed cnvnator 0.3.3 using different version of root (root 6.14 and root 6.16).
When I ran the two cnvnator with the same data, it generated different results.
And the cnvnator with root 6.16 threw out the warning like "Unknown option '-unique'."

I feel confused with this thing. Could you help me? Thanks

**Comment by shenjia1** [comment]
Hi,

Sorry to reply to you later.
The cnv of the one with root 6.14 is 3399 and  the other is 5595. And the overlap of them is  2389.
Do you think there will be such difference using different versions of root?

Thanks,
Jia

**Comment by abyzov** [comment]
Hi,
not is shouldn’t be that different. Is it only the ROOT version that is different? Is the code for CNVnator (i.e., version) the same?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On Apr 29, 2019, at 12:19 AM, shenjia <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Sorry to reply to you later.
The cnv of the one with root 6.14 is 3399 and the other is 5595. And the overlap of them is 2389.
Do you think there will be such difference using different versions of root?

Thanks,
Jia

**Comment by shenjia1** [comment]
I both used 0.3.3 but different version of root.

**Comment by abyzov** [comment]
Such behavior is no expected.

It would be helpful if you can provide more info to try to understand this issue.
* Is average estimated RD the same, e.g., cnvnator -root your.root -eval your_bin give roughly the same values
* It would be great if you could visualize RD for a regions of discrepant call and send to me (use -view command).

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On Apr 29, 2019, at 12:46 AM, shenjia <notifications@github.com<mailto:notifications@github.com>> wrote:


I both used 0.3.3 but different version of root.
