### ISSUE TITLE
CNVnator makefile failed at line 63

### ISSUE THREAD

**Issue by fingerfen** [abyzovlab/CNVnator#151]
Dear developers,

I'm a new user and am not familiar with a lot of these technical issues. 

I am having some trouble when compiling CNVnator using the makefile. I have samtools 1.9, root 6.16, gcc 5.4.0, OpenSSL 1.0.2g. I did source "thisroot.sh" and also created a samtools symbolic link in the CNVnator folder. I have installed libssl-dev. I also ran make using make LIBS="-lcrypto".

I'm hoping to get help for my error, I am thinking it has something to do with OpenSSL but I am not sure how to resolve it. The error is:

root@801a96bb37e0:/CNVnator# make LIBS="-lcrypto"
Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4\" -fopenmp -I/root/include      -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c cnvnator.cpp -o obj/cnvnator.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4\" -fopenmp -I/root/include      -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c EXOnator.cpp -o obj/EXOnator.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4\" -fopenmp -I/root/include      -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c HisMaker.cpp -o obj/HisMaker.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4\" -fopenmp -I/root/include      -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c AliParser.cpp -o obj/AliParser.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4\" -fopenmp -I/root/include      -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c FastaParser.cpp -o obj/FastaParser.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4\" -fopenmp -I/root/include      -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c VcfParser.cpp -o obj/VcfParser.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4\" -fopenmp -I/root/include      -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c Genotyper.cpp -o obj/Genotyper.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4\" -fopenmp -I/root/include      -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c Interval.cpp -o obj/Interval.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4\" -fopenmp -I/root/include      -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c Genome.cpp -o obj/Genome.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4\" -fopenmp -o cnvnator obj/cnvnator.o obj/EXOnator.o obj/HisMaker.o obj/AliParser.o obj/FastaParser.o obj/VcfParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a samtools/htslib-1.9/libhts.a -lcrypto -lz -lbz2 -lcurl -llzma -L/root/lib      -lCore -lRIO -lHist -lGraf -lGpad -lTree -lMathCore
/usr/bin/ld: warning: libssl.so.1.1, needed by /root/lib/libNet.so.6.16, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcrypto.so.1.1, needed by /root/lib/libNet.so.6.16, not found (try using -rpath or -rpath-link)
/root/lib/libNet.so.6.16: undefined reference to `SSL_get_error@OPENSSL_1_1_0'
/root/lib/libtbb.so.2: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/root/lib/libNet.so.6.16: undefined reference to `SSL_CTX_use_certificate_chain_file@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to `SSL_CTX_free@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to `SSL_new@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to `SSL_CTX_new@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to `SSL_CTX_load_verify_locations@OPENSSL_1_1_0'
/root/lib/libtbb.so.2: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
/root/lib/libNet.so.6.16: undefined reference to `SSL_set_quiet_shutdown@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to `SSL_shutdown@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to `OPENSSL_init_ssl@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to `SSL_write@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to `SSL_free@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to `SSL_CTX_use_PrivateKey_file@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to `TLS_method@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to `SSL_peek@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to `SSL_read@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to `SSL_connect@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to `HMAC@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to `EVP_sha1@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to `SSL_set_fd@OPENSSL_1_1_0'
collect2: error: ld returned 1 exit status
Makefile:63: recipe for target 'cnvnator' failed
make: *** [cnvnator] Error 1

Thank you

**Comment by abyzov** [comment]
Hi,
I haven’t seen such error before. Yes, it does looks like there is something related to SSL. But the linking issue starts in /root/lib/libNet.so.6.16, which is a ROOT library. Are you able to run ROOT normally?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On Apr 29, 2019, at 1:39 PM, Nhat Duong <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear developers,

I'm a new user and am not familiar with a lot of these technical issues.

I am having some trouble when compiling CNVnator using the makefile. I have samtools 1.9, root 6.16, gcc 5.4.0, OpenSSL 1.0.2g. I did source "thisroot.sh" and also created a samtools symbolic link in the CNVnator folder. I have installed libssl-dev. I also ran make using make LIBS="-lcrypto".

I'm hoping to get help for my error, I am thinking it has something to do with OpenSSL but I am not sure how to resolve it. The error is:

root@801a96bb37e0:/CNVnator# make LIBS="-lcrypto"
Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION="v0.4" -fopenmp -I/root/include -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c cnvnator.cpp -o obj/cnvnator.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION="v0.4" -fopenmp -I/root/include -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c EXOnator.cpp -o obj/EXOnator.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION="v0.4" -fopenmp -I/root/include -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c HisMaker.cpp -o obj/HisMaker.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION="v0.4" -fopenmp -I/root/include -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c AliParser.cpp -o obj/AliParser.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION="v0.4" -fopenmp -I/root/include -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c FastaParser.cpp -o obj/FastaParser.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION="v0.4" -fopenmp -I/root/include -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c VcfParser.cpp -o obj/VcfParser.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION="v0.4" -fopenmp -I/root/include -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c Genotyper.cpp -o obj/Genotyper.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION="v0.4" -fopenmp -I/root/include -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c Interval.cpp -o obj/Interval.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION="v0.4" -fopenmp -I/root/include -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c Genome.cpp -o obj/Genome.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION="v0.4" -fopenmp -o cnvnator obj/cnvnator.o obj/EXOnator.o obj/HisMaker.o obj/AliParser.o obj/FastaParser.o obj/VcfParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a samtools/htslib-1.9/libhts.a -lcrypto -lz -lbz2 -lcurl -llzma -L/root/lib -lCore -lRIO -lHist -lGraf -lGpad -lTree -lMathCore
/usr/bin/ld: warning: libssl.so.1.1, needed by /root/lib/libNet.so.6.16, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcrypto.so.1.1, needed by /root/lib/libNet.so.6.16, not found (try using -rpath or -rpath-link)
/root/lib/libNet.so.6.16: undefined reference to SSL_get_error@OPENSSL_1_1_0' /root/lib/libtbb.so.2: undefined reference to __cxa_init_primary_exception@CXXABI_1.3.11'
/root/lib/libNet.so.6.16: undefined reference to SSL_CTX_use_certificate_chain_file@OPENSSL_1_1_0' /root/lib/libNet.so.6.16: undefined reference to SSL_CTX_free@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to SSL_new@OPENSSL_1_1_0' /root/lib/libNet.so.6.16: undefined reference to SSL_CTX_new@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to SSL_CTX_load_verify_locations@OPENSSL_1_1_0' /root/lib/libtbb.so.2: undefined reference to std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
/root/lib/libNet.so.6.16: undefined reference to SSL_set_quiet_shutdown@OPENSSL_1_1_0' /root/lib/libNet.so.6.16: undefined reference to SSL_shutdown@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to OPENSSL_init_ssl@OPENSSL_1_1_0' /root/lib/libNet.so.6.16: undefined reference to SSL_write@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to SSL_free@OPENSSL_1_1_0' /root/lib/libNet.so.6.16: undefined reference to SSL_CTX_use_PrivateKey_file@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to TLS_method@OPENSSL_1_1_0' /root/lib/libNet.so.6.16: undefined reference to SSL_peek@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to SSL_read@OPENSSL_1_1_0' /root/lib/libNet.so.6.16: undefined reference to SSL_connect@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to HMAC@OPENSSL_1_1_0' /root/lib/libNet.so.6.16: undefined reference to EVP_sha1@OPENSSL_1_1_0'
/root/lib/libNet.so.6.16: undefined reference to `SSL_set_fd@OPENSSL_1_1_0'
collect2: error: ld returned 1 exit status
Makefile:63: recipe for target 'cnvnator' failed
make: *** [cnvnator] Error 1

Thank you

**Comment by fingerfen** [comment]
Running "root -?" gives me the help for root. So it seems to be working fine

Running "root" gives me:
root@062e63093dfc:/# root
root: can't figure out DISPLAY, set it manually
In case you run a remote ssh session, restart your ssh session with:
=========>  ssh -Y

Running "root -b" to run in batch mode gives me:
root@062e63093dfc:/# root -b
ERROR in cling::CIFactory::createCI(): cannot extract standard library include paths!
Invoking:
  LC_ALL=C x86_64-linux-gnu-g++-7  -O3 -DNDEBUG -xc++ -E -v /dev/null 2>&1 >/dev/null | awk '/^#include </,/^End of search/{if (!/^#include </ && !/^End of search/){ print }}' | GREP_OPTIONS= grep -E "(c|g)\+\+"
Results was:
With exit code 256
   ------------------------------------------------------------
  | Welcome to ROOT 6.16/00                  https://root.cern |
  |                               (c) 1995-2018, The ROOT Team |
  | Built for linuxx8664gcc on Jan 23 2019, 09:06:13           |
  | From tags/v6-16-00@v6-16-00                                |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q' |
   ------------------------------------------------------------

cling::DynamicLibraryManager::loadLibrary(): /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /root/lib/libtbb.so.2)


Thanks again,

**Comment by abyzov** [comment]
Hi,
looks like there is some issue with ROOT installation as it can’t find C++ libraries.
Can you try CNVnator with a different ROOT installation on a different machine?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by fingerfen** [comment]
Thank you very much, I went back to fix my root installation. I got version 0.4 to work now. Thank you.
