### ISSUE TITLE
Can not install CNVnator

### ISSUE THREAD

**Issue by tongshiyuan** [abyzovlab/CNVnator#152]
Hi，
I use the cmd line as follow：
$ git clone https://github.com/abyzovlab/CNVnator.git
$ cd CNVnator
$ ln -s /biosoft/samtools-1.9/ samtools
$ mkdir yeppp && cd yeppp
$ wget http://bitbucket.org/MDukhan/yeppp/downloads/yeppp-1.0.0.tar.bz2
$ tar xjf yeppp-1.0.0.tar.bz2
$ make YEPPPLIBDIR=/biosoft/CNVnator/yeppp/yeppp-1.0.0/binaries/linux/x86_64/ YEPPPINCLUDEDIR=/biosoft/CNVnator/yeppp/yeppp-1.0.0/library/headers

and install error：
--------------------------------------------------------------------------
Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4\" -fopenmp -o cnvnator obj/cnvnator.o obj/EXOnator.o obj/HisMaker.o obj/AliParser.o obj/FastaParser.o obj/VcfParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a samtools/htslib-1.9/libhts.a -lz -lbz2 -lcurl -llzma -L/biosoft/CNVnator/yeppp/yeppp-1.0.0/binaries/linux/x86_64/ -lyeppp -L/biosoft/root/build/lib      -lCore -lRIO -lHist -lGraf -lGpad -lTree -lMathCore
/usr/bin/ld: samtools/htslib-1.9/libhts.a(hfile_s3.o): undefined reference to symbol 'HMAC@@OPENSSL_1_1_0'
//usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:63: recipe for target 'cnvnator' failed
make: *** [cnvnator] Error 1
--------------------------------------------------------------------------

What can we do to solve this? And what version of samtools is required?

**Comment by suvakov** [comment]
Can you please try to compile with:
make clean
make LIBS="-lcrypto"

**Comment by tongshiyuan** [comment]
> Can you please try to compile with:
> make clean
> make LIBS="-lcrypto"

Thanks，
And when I do that, install maybe done with no error.
But when I run cnvnator, report an error

./cnvnator: error while loading shared libraries: libCore.so: cannot open shared object file: No such file or directory

**Comment by abyzov** [comment]
Hi,
looks like you don’t have set a proper environment for ROOT libs.
You may need to do
. /path_to_root/bin/thisroot.sh

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On May 13, 2019, at 8:28 PM, tongshiyuan <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you please try to compile with:
make clean
make LIBS="-lcrypto"

Thanks，
And when I do that, install maybe done with no error.
But when I run cnvnator, report an error

./cnvnator: error while loading shared libraries: libCore.so: cannot open shared object file: No such file or directory
