### ISSUE TITLE
From normalized_RD to real copy number

### ISSUE THREAD

**Issue by hoonghim** [abyzovlab/CNVnator#153]
Dear professor Alexej Abyzov,

Hello, I am worried that I might have made a mistake in the process of calculating a copy number.

When I get the result of normalized_RD, I estimated the real copy number by rounding the product of normalized_RD and 2 (i.e, round(normalized_RD * 2))

Is this process wrong?

I just read these questions but couldn't find the answer
(https://github.com/abyzovlab/CNVnator/issues/24)
(https://github.com/abyzovlab/CNVnator/issues/69)
(https://github.com/abyzovlab/CNVnator/issues/135)

I followed this explanation - normalized_RD -- read depth normalized to 1.

So to obtain the real copy number of all CNV positions, I applied the following calculation method
estimated real copy number = round( normalized_RD *2 )

If this could make any issue, could you please tell the right way?

I thought that genotyping part is only used for a specific genomic region.
![image](https://user-images.githubusercontent.com/42195952/57868744-866b5f80-783e-11e9-8b32-4be6a73dc0d9.png)

Thanks in advance for your reply.

Sincerely,

Seung-hoon

**Comment by abyzov** [comment]
Hi,
yes your are doing correct round up to get CN.
However, please note, that when do genotyping the output is estimated CN. So, you don’t need to multiply by 2.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On May 16, 2019, at 9:57 AM, hoonghim <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear professor Alexej Abyzov,

Hello, I am worried that I might have made a mistake in the process of obtaining a copy number.

When I get the result of normalized_RD, I estimated the real copy number by rounding the product of normalized_RD and 2 (i.e, round(normalized_RD * 2))

Is this process wrong?

I just read these questions but couldn't find the answer
(#24<https://github.com/abyzovlab/CNVnator/issues/24>)
(#69<https://github.com/abyzovlab/CNVnator/issues/69>)
(#135<https://github.com/abyzovlab/CNVnator/issues/135>)

I followed this explanation - normalized_RD -- read depth normalized to 1.

So to obtain the real copy number of every CNVs, I applied the following calculation method
estimated real copy number = round( normalized_RD *2 )

If this could make any issue, could you please tell the right way?

I thought that genotyping part is only used for a specific genomic region.
[image]<https://user-images.githubusercontent.com/42195952/57868744-866b5f80-783e-11e9-8b32-4be6a73dc0d9.png>

Thanks in advance for your reply.

Sincerely,

Seung-hoon
