### ISSUE TITLE
Issue Installing CNVnator

### ISSUE THREAD

**Issue by pwiner88** [abyzovlab/CNVnator#154]
Hello,

I am trying to run make inside the CNVnator directory after setting a symbolic link to samtools and I get the following error:

pwiner@hpc-login3:/home/rcf-proj3/ajd/pwiner/software/CNVnator$ make
Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4\" -fopenmp -I/home/rcf-proj3/ajd/pwiner/software/build/include      -Isamtools -c cnvnator.cpp -o obj/cnvnator.o
In file included from AliParser.hh:10:0,
                 from cnvnator.cpp:13:
samtools/sam.h:28:24: fatal error: htslib/sam.h: No such file or directory
 #include "htslib/sam.h"
                        ^
compilation terminated.
make: *** [obj/cnvnator.o] Error 1

Any idea why? I also completed installation of root and it works fine.

**Comment by suvakov** [comment]
Hi,
You probably did not compile samtools with htslib. Try to download latest samtools release from:
https://github.com/samtools/samtools/releases
After extracting files and compiling with
./configure
make
replace "samtools" symbolic link in your CNVnator folder with new samtools folder.
