### ISSUE TITLE
CNVnator e-val2

### ISSUE THREAD

**Issue by hzjsxu** [abyzovlab/CNVnator#156]
Dear professor Alexej Abyzov,
Hello, in my results I could get really large e-vals (>>1) as follows. I have difficulty understanding what each one of the four e-vals indicates..... do you by any chance have idea what are they trying to test for each of the e-vals? And the e-val2 which >>1 is wrong or how to solve it?
![cnv_output](https://user-images.githubusercontent.com/45815139/60708475-bc74b800-9f40-11e9-9b84-52375cb0f846.png)

Thanks in advance for your reply.
jsxu

**Comment by abyzov** [comment]
Hi,
there are two ways to calculate e-vals. If either e-val1 or e-val2 pass significance CNVnator reports such a call.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by hzjsxu** [comment]
> Hi, there are two ways to calculate e-vals. If either e-val1 or e-val2 pass significance CNVnator reports such a call. Alexej Abyzov, Ph.D. Senior Associate Consultant, Assistant Professor of Biomedical Informatics, Department of Health Sciences Research, Center for Individualized Medicine, Mayo Clinic ----------------------------- Mayo Clinic, 200 1st street SW, Harwick 3-12 Rochester, MN 55905 [www.abyzovlab.org<http://www.abyzovlab.org](http://www.abyzovlab.org<http://www.abyzovlab.org)> tel: +1-(507)-538-0978 fax: +1-(507)-284-0745

ok thanks. that's to say,  if one of e-val1 or e-val2 passes the significance, then I can consider it reasaonable. Right?

**Comment by abyzov** [comment]
Yes.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
