### ISSUE TITLE
something of selection of bin size

### ISSUE THREAD

**Issue by hzjsxu** [abyzovlab/CNVnator#157]
Hi,
&emsp; &emsp; I have ~6X WGS data with read length around 150bp, and ~20X WGS data with read length around 90bp.  In order to make the ratio of average RD and standard deviation 4-5, I found bin_sizes of two cases are around 4kb and 2kb.  I think they are large , is it normal? 
&emsp; &emsp; Can I use smaller bin size such as 500bp or 1kb to call CNVs?

Thanks for your reply!
jsxu

**Comment by abyzov** [comment]
Hi,
yes 2-4 kbp bins seems reasonable for such a coverage. Using smaller bins may lead to overfragmented calls.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
