### ISSUE TITLE
Can't parse sequence for chromosome

### ISSUE THREAD

**Issue by osowiecki** [abyzovlab/CNVnator#158]
perl ./cnvnator2VCF.pl -reference ./genome.fasta ./cnv/CF_36_100.cnvnator

Can't parse sequence for chromosome AAEX03026064.1.
AAEX03026064.1  1       CNVnator_del_21231      N       <DEL>   .       PASS    END=2300;SVTYPE=DEL;SVLEN=-2300;IMPRECISE;natorRD=0.333395;natorP1=1.88475e-08;natorP2=1.99843e-10;natorP3=199186;natorP4=9.10435e+06;natorQ0=0.886228        GT:CN   0/1:1
Can't parse sequence for chromosome AAEX03026066.1.
AAEX03026066.1  1       CNVnator_del_21232      N       <DEL>   .       PASS    END=2100;SVTYPE=DEL;SVLEN=-2100;IMPRECISE;natorRD=0.32629;natorP1=0.0191186;natorP2=3.53692e+07;natorP3=1;natorP4=1;natorQ0=0.531915  GT:CN   0/1:1
Can't parse sequence for chromosome AAEX03026067.1.
AAEX03026067.1  1       CNVnator_del_21233      N       <DEL>   .       PASS    END=2000;SVTYPE=DEL;SVLEN=-2000;IMPRECISE;natorRD=0.417231;natorP1=2.53331e-05;natorP2=0.00122585;natorP3=1;natorP4=1;natorQ0=0.931429        GT:CN   0/1:1
Can't parse sequence for chromosome AAEX03026069.1.
AAEX03026069.1  1       CNVnator_del_21234      N       <DEL>   .       PASS    END=1800;SVTYPE=DEL;SVLEN=-1800;IMPRECISE;natorRD=0.336189;natorP1=2.73864e-05;natorP2=3.96749e-09;natorP3=1;natorP4=1;natorQ0=1      GT:CN   0/1:1
Can't parse sequence for chromosome AAEX03026070.1.
AAEX03026070.1  1       CNVnator_del_21235      N       <DEL>   .       PASS    END=1700;SVTYPE=DEL;SVLEN=-1700;IMPRECISE;natorRD=0;natorP1=9.37485e-11;natorP2=3.99004e-68;natorP3=1;natorP4=1;natorQ0=-1    GT:CN   1/1:0
Can't parse sequence for chromosome AAEX03026071.1.
AAEX03026071.1  1       CNVnator_del_21236      N       <DEL>   .       PASS    END=1600;SVTYPE=DEL;SVLEN=-1600;IMPRECISE;natorRD=0.362952;natorP1=0.00275305;natorP2=0.0040231;natorP3=1;natorP4=1;natorQ0=1 GT:CN   0/1:1
Can't parse sequence for chromosome AAEX03026072.1.
AAEX03026072.1  1       CNVnator_del_21237      N       <DEL>   .       PASS    END=1200;SVTYPE=DEL;SVLEN=-1200;IMPRECISE;natorRD=0.295593;natorP1=0.293226;natorP2=0.0018533;natorP3=1;natorP4=1;natorQ0=0.434211    GT:CN   0/1:1

Can you explain the source of this error and potential consequences?
I can still see these variants in the resulting file.

**Comment by abyzov** [comment]
Hi,
in this case the script can’t locate file AAEX03026064.1.fa, which it needs to parse the reference sequence.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by osowiecki** [comment]
I use "genome.fasta" file which has an entire genome sequence inside including
>AAEX03026064.1 dna_sm:scaffold scaffold:CanFam3.1:AAEX03026064.1:1:2250:1 REF
GTGacaagatattccagggctaagtgataccactcttatgccagatcaagaatcagccat ...
along with the entire sequence. That's why I asked.

**Comment by abyzov** [comment]
Please use per chromosome .fa files.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
