### ISSUE TITLE
Read depth not normalized to 1? 

### ISSUE THREAD

**Issue by osowiecki** [abyzovlab/CNVnator#159]
Shouldn't RD_value come between 0 and 1 after dividing the genotype value by 2?
I used bin size of 200 in this example. The 10:3799001-3800000 region has one large positive RD outlier.

>10:3799001-3800000 genotype
Genotype 10:3799001-3800000 /data/CF_6916.root 2235.65 2201.77
>10:20001-25000 genotype
Genotype 10:20001-25000 /data/CF_6916.root 4.76189 4.68972
>10:449195-450225 genotype
Genotype 10:449195-450225 /data/CF_6916.root 0.779528 0.767713

I was tracking the source code this night and I still don't know how it got to 2201.77.
I'm trying to use CNVnator genotyping tool and cnvnator2VCF.pl code to give some kind of GT field to the "ERDS" result vcf file.

[EDIT] : 

I can see in :

https://github.com/abyzovlab/CNVnator/issues/153

That I can treat genotype RD value as estimated CNV number. 
This makes sense and gives similar copy number counts to ERDS.
This pretty much solves my problem, yet I would still like to know if normalized RD value calculation behaves normally when generating such large values above 1.

**Comment by abyzov** [comment]
Hi,
genotype can be of any value.
You can use -view functionality to check RD in the region of interest.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
