### ISSUE TITLE
 run the 'Extract read mapping' step concurrently 

### ISSUE THREAD

**Issue by jazberna1** [abyzovlab/CNVnator#160]
Hello,

is it possible to run the 'Extract read mapping' step concurrently? I mean run all the chromosomes in parallel, writing on the same root file.

Thanks so much!
Jorge

**Comment by abyzov** [comment]
Hi,
yes you can extraction per chromosome in parallel. But currently is not any faster than doing on single extractions for all chromosomes.
Please request adding this feature (parallel read extraction) at GitHub.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On Jul 22, 2019, at 6:26 AM, Jorge Zamora <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

is it possible to run the 'Extract read mapping' step concurrently? I mean run all the chromosomes in parallel, writing on the same root file.

Thanks so much!
Jorge
