### ISSUE TITLE
extract depth information from .root file

### ISSUE THREAD

**Issue by seoldh** [abyzovlab/CNVnator#161]
Hello I am a beginner in bioinformatics.

While studying CNV, I want to calculate Vst value from my data.

It seems to be using the variance of depth,

but how can I extract depth information from the specific region that is not CNV region?

Or is there any other easy way to calculate it?

Also, when I use '-view' command, I get the following error

cnvnator -root output.root -view 300
>1:100-1000
Error in <TString::AssertElement>: out of bounds: i = -1, Length = 0

How can I fix it?

Thank you.

**Comment by abyzov** [comment]
Hi,
do you specifically need coverage or genotype is good enough?
There is currently no function to return coverage for a given region. You can use -genotype functionality to estimate copy number.
You can also consider using -eval functionality to estimate average RD and its variance.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
