### ISSUE TITLE
 the meaning of genotype "./1"

### ISSUE THREAD

**Issue by SixPlusSeven** [abyzovlab/CNVnator#162]
I found that the vcf file output by CNVnator contains the genotype './1', which I have not seen in the GATK results before. What does the './1' mean?
```
GWHAAEV00000001 4799801 CNVnator_dup_21 T       <DUP>   .       PASS    END=4803500;SVTYPE=DUP;SVLEN=3700;IMPRECISE;natorRD=3.08695;natorP1=0;natorP2=1.20077e-19;natorP3=0.0128775;natorP4=0.00026256;natorQ0=0.00286944       GT:CN   ./1:3
GWHAAEV00000001 5065201 CNVnator_del_22 T       <DEL>   .       PASS    END=5070800;SVTYPE=DEL;SVLEN=-5600;IMPRECISE;natorRD=0.113962;natorP1=2.84594e-11;natorP2=2.29196e-09;natorP3=4.42701e-11;natorP4=0.00666371;natorQ0=0.425532   GT:CN   1/1:0
GWHAAEV00000001 5600701 CNVnator_dup_23 T       <DUP>   .       PASS    END=5607000;SVTYPE=DUP;SVLEN=6300;IMPRECISE;natorRD=2.58689;natorP1=0;natorP2=8.94537e-10;natorP3=0;natorP4=0.000670899;natorQ0=0.164047        GT:CN   ./1:3
```

Thanks!
Alex

**Comment by abyzov** [comment]
Hi,
in this can copy number is too high, so it is ambiguous whether a dup is homozygous or heterozygous.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by SixPlusSeven** [comment]
Thanks for your answer!
