### ISSUE TITLE
Error parsing cram

### ISSUE THREAD

**Issue by jjfarrell** [abyzovlab/CNVnator#163]
Using this command: 
cnvnator -root $ROOT_FILE -chrom chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr
21 chr22 chrX chrY   -tree $CRAM  -genome GRCh38

The following error occurs. Any suggestions? 

Parsing file /restricted/projectnb/casa/wgs.hg38/adni/cram/ADNI_002_S_0413.hg38.realign.bqsr.cram ...
Allocating memory ...
Done.
[E::cram_get_ref] Failed to populate reference for id 0
[E::cram_decode_slice] Unable to fetch reference #0 9998..30506
[E::cram_next_slice] Failure to decode slice
Filling and saving tree for 'chr1' ...
Filling and saving tree for 'chr2' ...
Filling and saving tree for 'chr3' ...
Filling and saving tree for 'chr4' ...
Filling and saving tree for 'chr5' ...
Filling and saving tree for 'chr6' ...
Filling and saving tree for 'chr7' ...
Filling and saving tree for 'chr8' ...
Filling and saving tree for 'chr9' ...
Filling and saving tree for 'chr10' ...
Filling and saving tree for 'chr11' ...
Filling and saving tree for 'chr12' ...
Filling and saving tree for 'chr13' ...
Filling and saving tree for 'chr14' ...
Filling and saving tree for 'chr15' ...
Filling and saving tree for 'chr16' ...
Filling and saving tree for 'chr17' ...
Filling and saving tree for 'chr18' ...
Filling and saving tree for 'chr19' ...
Filling and saving tree for 'chr20' ...
Filling and saving tree for 'chr21' ...
Filling and saving tree for 'chr22' ...
Filling and saving tree for 'chrX' ...
Filling and saving tree for 'chrY' ...
Writing histograms ...
Total of 0 reads were placed.

**Comment by jjfarrell** [comment]
To read a cram, the reference genome fasta is needed.  CNVnator does not have a parameter to pass the reference. That is what is causing the error I believe.  As a work around, is it possible to read from stdin. In that case samtools view could be used to read the cram and pass it to cnvnator.

**Comment by kelepiradam** [comment]
If you can set the REF_PATH and REF_CACHE as indicated in the samtools manual cnvnator is able to parse cram directly without issues.
