### ISSUE TITLE
Issue at Compile Time: vcf.h no such file or directory 

### ISSUE THREAD

**Issue by vaderhhh** [abyzovlab/CNVnator#165]
Compiling with parallel (OpenMP) support
g++ -O3 -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11 -DCNVNATOR_VERSION=\"v0.4.1\" -fopenmp -I/u/local/apps/cern_root/6.12.06/icc-17.0.1/include/root -Isamtools -c HisMaker.cpp -o obj/HisMaker.o
In file included from HisMaker.cpp:7:0:
VcfParser.hh:8:17: fatal error: vcf.h: No such file or directory
 #include "vcf.h"
                 ^
compilation terminated.
make: *** [obj/HisMaker.o] Error 1

I have cern_root, samtools installed but I can't seem to find the vcf.h file? Is this a dependency issue or did I compile it incorrectly?

**Comment by suvakov** [comment]
Did you install samtools from release (with htslib) and make symbolic link to samtools dir in CNVnator? You can find install instructions here:
https://github.com/abyzovlab/CNVnator/blob/master/INSTALL

**Comment by karthick37** [comment]
I got the same issue. I didn't find any issues with samtools..

**Comment by suvakov** [comment]
Do you have samtools compiled from release or cloned from GitHub?
