### ISSUE TITLE
IO.cpp:41:23: error: invalid use of incomplete type ‘class TKey’

### ISSUE THREAD

**Issue by lisaxplin** [abyzovlab/CNVnator#166]
Dear All,

I am getting error when trying to compile CNVnator_v0.4.1, with root/6.10.04, gcc/4.9.4 and samtools/1.9. I ran into following error (removed full path prefix after "-I"). Any help will be appreciated. Thanks.

g++ -O3 -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11 -DCNVNATOR_VERSION=\"v0.4.1\" -fopenmp -I/.../root-6.10.04//include -I/.../samtools/samtools-1.9 -I/.../samtools/samtools-1.9/htslib-1.9 -I/.../samtools/samtools-1.9/htslib-1.9/htslib -c IO.cpp -o obj/IO.o
IO.cpp: In constructor ‘IO::IO(std::string)’:
IO.cpp:41:23: error: invalid use of incomplete type ‘class TKey’
     TObject *obj = key->ReadObj();
                       ^
In file included from /software/root/root-6.10.04/include/TROOT.h:28:0,
                 from IO.hh:20,
                 from IO.cpp:1:
/...../root-6.10.04/include/TDirectory.h:31:7: error: forward declaration of ‘class TKey’
 class TKey;
       ^
IO.cpp: In member function ‘void IO::cptrees(std::string, std::string*, int)’:
IO.cpp:441:23: error: invalid use of incomplete type ‘class TKey’
     TObject *obj = key->ReadObj();
                       ^
In file included from /..../root-6.10.04/include/TROOT.h:28:0,
                 from IO.hh:20,
                 from IO.cpp:1:
/.../root-6.10.04/include/TDirectory.h:31:7: error: forward declaration of ‘class TKey’
 class TKey;
       ^
make: *** [obj/IO.o] Error 1

**Comment by suvakov** [comment]
We think that we have fixed the problem. You can try to downlad release and compile it again. Please let us know does it work.

**Comment by lisaxplin** [comment]
Hi,
I downloaded the source with "git clone https://github.com/abyzovlab/CNVnator.git" and was able to compile cnvnator successfully with "make LIBS="-lcrypto".
Thanks for fixing the problem.
