### ISSUE TITLE
Failed stat step

### ISSUE THREAD

**Issue by asmariyaz23** [abyzovlab/CNVnator#167]
Hello,

I am running CNVnator in the following manner:

#Extracting reads
```
cnvnator -root ./file.root -tree 0480_001.sorted.dup.recal.final.bam -chrom 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y
Parsing file 0480_001.sorted.dup.recal.final.bam ...
Allocating memory ...
Done.
Filling and saving tree for '1' ...
Filling and saving tree for '2' ...
Filling and saving tree for '3' ...
Filling and saving tree for '4' ...
Filling and saving tree for '5' ...
Filling and saving tree for '6' ...
Filling and saving tree for '7' ...
Filling and saving tree for '8' ...
Filling and saving tree for '9' ...
Filling and saving tree for '10' ...
Filling and saving tree for '11' ...
Filling and saving tree for '12' ...
Filling and saving tree for '13' ...
Filling and saving tree for '14' ...
Filling and saving tree for '15' ...
Filling and saving tree for '16' ...
Filling and saving tree for '17' ...
Filling and saving tree for '18' ...
Filling and saving tree for '19' ...
Filling and saving tree for '20' ...
Filling and saving tree for '21' ...
Filling and saving tree for '22' ...
Filling and saving tree for 'X' ...
Filling and saving tree for 'Y' ...
Writing histograms ... 
Total of 682966990 reads were placed.
```
#Histogram
```
cnvnator -root file.root -his 1000 -chrom 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y -fasta genome.fa.gz 
Allocating memory ...
Done.
```
#Stats 
```
cnvnator -root file.root -stat 1000
Can't find directory 'bin_1000' in file '/scratch/wgs/cnv/CNVnator/file.root'.
```

I would like to call CNVs later on. Is there something wrong with the histogram step?

Thank you,
Asma

**Comment by suvakov** [comment]
Can you list chromosomes in genome.fa.gz? You can use zgrep:
    zgrep "^>" genome.fa.gz
or samtools:
    samtools faidx genome.fa.gz
    cat genome.fa.gz.fai

**Comment by asmariyaz23** [comment]
zgrep "^>" genome.fa.gz
>1
>2
>3
>4
>5
>6
>7
>8
>9
>10
>11
>12
>13
>14
>15
>16
>17
>18
>19
>20
>21
>22
>X
>Y
>MT

**Comment by abyzov** [comment]
Hi,
is it all output that you get from -his step. If so, then something went wrong during making histograms.
You should get output something like

Allocating memory ...
Done.
Calculating histograms with bin size of 200 for 'chr1' ...
Making GC histogram for 'chr1' ...
Done.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
