### ISSUE TITLE
plotcircular.py and plotrdbaf.py issue with ROOT

### ISSUE THREAD

**Issue by kelepiradam** [abyzovlab/CNVnator#168]
Hi

I am having an issue with these two plot routines both have very similar problems. 

`(gatk) sky@GOKALP:/mnt/e/Wes759_CNVnator$ DISPLAY=localhost:0.0 plotcircular.py -chrom $(seq -s "," 1 22)X,Y -bs 1000 -o deneme2.png Wes759_root.root
256
Traceback (most recent call last):
  File "/mnt/d/scripts/CNVnator/plotcircular.py", line 54, in <module>
    snp = iof.get_signal(c, bs, "SNP maf",snpflag)[1]
  File "/mnt/d/scripts/CNVnator/pytools/io.py", line 122, in get_signal
    n = his.GetSize()
AttributeError: 'TObject' object has no attribute 'GetSize'
(gatk) sky@GOKALP:/mnt/e/Wes759_CNVnator$`

This was tried using different root versions both precompiled and from source however the problem persists. plotbaf.py and regular plotting via view option works fine but these two scrips are failing. 

Any comments?

Regards.

**Comment by kelepiradam** [comment]
Looks like a bad debug message from python. It is solved.

**Comment by ilaydabozan** [comment]
Hi, I'm getting the same error;

256
Traceback (most recent call last):
  File "/home/ilaydab/scratch/CNVnator/plotcircular.py", line 54, in <module>
    snp = iof.get_signal(c, bs, "SNP maf",snpflag)[1]
  File "/lustre04/scratch/ilaydab/CNVnator/pytools/io.py", line 121, in get_signal
    his = self.file.Get("bin_" + str(bin_size)).Get(self.signal_name(chr, bin_size, signal, flags))
AttributeError: 'TObject' object has no attribute 'Get'

I am not able to solve it. How did you solve it?
Thank you

**Comment by suvakov** [comment]
Plotcircular tool assumes that root file has precomputed RD and BAF histograms for default bin size 100k for all autosomes. It looks that some of them are missing.

You can create them using "-his 100000" and "-baf 100000" cnvnator step/option.

If you want to use different bin size use plotcircular with option -bs (baf bins - default=100000) and -rdbs (rd bins - default=100000).

**Comment by saphiecor** [comment]
I created RD and BAF his for 10000 and ran with the option -bs 10000 -rdbs 10000. But I get the same error as the others.

The ratio of mean/sdev where I can get 4 is bin_size 130.

**Comment by suvakov** [comment]
Can you please list content of root file (./cnvnator -root file.root -ls) and send me (suvakov at gmail) or post here. Thanks.
