### ISSUE TITLE
non-human genome RD signal issues

### ISSUE THREAD

**Issue by aliciab15** [abyzovlab/CNVnator#17]
Hello,

I am currently running CNVnator on a fish genome. the programme seems to be running fine but when it tries to get RD it comes up with the "Fit data empty" message. It then carries on and seems to be working fine but does not correct for GC content. 
Is there something I am doing wrong? Is it because I am using a  non-human genome? 
Any comments would be helpful. Thank you. 

(where I have written ** etc... ** just means that the programme has run through all the chromosomes).

Parsing file fish.bam ...
Allocating memory ...
Done.
Filling and saving tree for 'chr1' ...
**etc....**
Writing histograms ... 
Total of 127933939 reads were placed.
histogram
Allocating memory ...
Done.
Calculating histograms with bin size of 200 for 'chr1' ...
Making directory bin_200 ...
Making GC histogram for 'chr1' ...
**etc...**
Making statistics for chr1 ...
**etc...**
Average RD per bin (1-22) is 11.5863 +- 6.77279 (before GC correction)
Warning in <Fit>: Fit data is empty 
Warning in <Fit>: Fit data is empty 
Average RD per bin (X,Y)  is 0 +- 0 (before GC correction)
Correcting counts by GC-content for 'chr1' ...
Correcting counts by GC-content for 'chr2' ...
Zero value of GC average.
Bin 36874 with center 7.3747e+06 is not corrected.
Zero value of GC average.
Bin 309564 with center 6.19127e+07 is not corrected.
Correcting counts by GC-content for 'chr3' ...
Correcting counts by GC-content for 'chr4' ...
Correcting counts by GC-content for 'chr5' ...
Zero value of GC average.
**etc..**
Making statistics for chr1 after GC correction ...
**etc...**
Average RD per bin (1-22) is 10.8082 +- 6.0048 (after GC correction)
Warning in <Fit>: Fit data is empty 
Warning in <Fit>: Fit data is empty 
Average RD per bin (X,Y)  is 0 +- 0 (after GC correction)
partition
Partitioning RD signal for 'chr1' with bin size of 200 ...
Average RD per bin is 10.8082 +- 6.0048
Bin band is 2
Bin band is 3
Bin band is 4
Bin band is 5
Bin band is 6
**etc...**

**Comment by abyzov** [comment]
Hello,
from the output you sent it is clear that “Fit data empty” are for chromosomes X and Y. I’m guessing you don’t have X and Y chormosome (or there are not data for them).


Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
