### ISSUE TITLE
compile error with CNVnator 0.4.1

### ISSUE THREAD

**Issue by mwaldron104** [abyzovlab/CNVnator#173]
I downloaded and compiled latest samtools (1.9), but I'm getting what looks like a samtools-related error when compiling CNVnator:

$ ▶ make
Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4.1\" -fopenmp -I/usr/include/root -Isamtools -c cnvnator.cpp -o obj/cnvnator.o
In file included from cnvnator.cpp:14:0:
AliParser.hh:18:3: error: ‘samfile_t’ does not name a type
   samfile_t   *file;
   ^
AliParser.hh:19:3: error: ‘bam_index_t’ does not name a type
   bam_index_t *index;
   ^
AliParser.hh: In member function ‘std::string AliParser::getQueryName()’:
AliParser.hh:98:69: error: ‘bam1_qname’ was not declared in this scope
   inline string getQueryName() { return (record) ? bam1_qname(record) : ""; }
                                                                     ^
make: *** [obj/cnvnator.o] Error 1

**Comment by mwaldron104** [comment]
I was able to resolve this by making some edits to the Makefile, so that it could properly find my samtools, htslib and root files.

**Comment by lunalvan** [comment]
Hi! I am having the same issue when trying to install CNVnator. Do you by any chance know what edits you made to the Makefile?

**Comment by ChengQin0** [comment]
+1

**Comment by abyzov** [comment]
Please consider switching to CNVpytor https://github.com/abyzovlab/cnvpytor
Thanks.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 7-91
Rochester, MN 55905
www.abyzovlab.org
<http://www.abyzovlab.org>tel: +1-(507)-538-0978
