### ISSUE TITLE
 genotyping : Can't find directory 'bin_1000'

### ISSUE THREAD

**Issue by bijinpeng** [abyzovlab/CNVnator#174]
Hi: 
  When I used genotyping function to detect multiple regions, the following prompt appears :
Can't find directory 'bin_1000'.  I tried lots of different parameters of bin_size, but the error  has always been.  

cnvnator -root 11DM124.root -genotype 100 <<EOF
> chr1:1-401
> chr1:401-35900
> chr1:35900-57901
> chr1:57901-67300
> chr1:67300-91500
> chr1:91500-96101
> chr1:96101-119800
> chr1:119801-126500
> chr1:126501-139701
> exit
> EOF
Can't find directory 'bin_1000'.
Can't find directory 'bin_1000'.
Genotype chr1:1-401   11DM124.root 3.11413 -1
Can't find directory 'bin_1000'.
Can't find directory 'bin_1000'.
Genotype chr1:401-35900  11DM124.root 213.509 -1
Can't find directory 'bin_1000'.
Can't find directory 'bin_1000'.
Genotype chr1:35900-57901  11DM124.root 5.10456 -1
Can't find directory 'bin_1000'.
Can't find directory 'bin_1000'.
Genotype chr1:57901-67300  11DM124.root 4.79509 -1
Can't find directory 'bin_1000'.
Can't find directory 'bin_1000'.
Genotype chr1:67300-91500  11DM124.root 2.69153 -1

**Comment by abyzov** [comment]
Hi,
this does not affect performance. This is cause by a hardcoded behavior to print genotype for 1000 kbp bins. If histograms for such bins are not available the program will print -1 at the end of each line.
To avoid this problem you just have to conduct previous step for 1000 kbp bins.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
