### ISSUE TITLE
Copy number of reference genome given normalized read depth of the test sample

### ISSUE THREAD

**Issue by chirrie** [abyzovlab/CNVnator#177]
Hii,

I am wondering if it is correct  to calculate the copy number of the reference genome given the normailized read depth of the test sample.

Take for example after carrying out CNV analysis using CNVnator; in this case I am comparing  one sample of the test genome and the reference genome then I get the CNV calls.
So if in a given region the normalized read depth is 4.644, will be correct to do an inverse of this number to give the copy of the reference? In this case the inverse will be 0.215 meaning  the reference genome has zero copies(homozygous deletion).

If I take a case of deletion in the test sample and the normalized read depth is 0.168292 for example, then by getting its inverse 5.942 which rougly be equal to 6 copies in the reference relative to test sample.

Is this reasoning correct?  Or how to get the number of copies in reference genome given the copies in teest sample based CNVnator analysis?  I am working on one test sample then comparing it with one reference genome....

**Comment by abyzov** [comment]
Hi,
genotype of 4.644 means that this region roughly have 5 copies
genotype of 0168 means that this region roughly have 0 copies

The references genome is always one copy.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by chirrie** [comment]
Hii Prof Abyzov,
For the case of the number of copies in the test sample given the normalized read depth is clear to me, just like you mentioned that if normalized RD is 4.644 I will have 5 copies and if <0.25 I will have zero copies.
So what I am not getting is how to get the number of copies of the reference genome relative to test sample. (Consider a case I am working on one sample each  for the reference and the test).
My understanding of CNV is the gain or loss of genomic regions (>1000 bp) between genomes.
So if we have (0.168)=zero copies  in the test sample, then it implies that the reference genome has more copies than the test sample right? Meaning if the reference genome has 4 copies while then test has 1..then the 4 copies in the reference is distributed across the 1 in test sample resulting in low read coverage in a given region and vice versa for the copy gain events.

My assumption was that it is not always that the reference as one copy, but rather it can  have one or more copies relative to the test sample, which means if I take the inverse of normalized rd  it will give me copies in the reference genome... From the brief answers you have provided it seems this is wrong? I would like to know how to get the number of copies in the reference genome relative to test sample given the normalized RD of the test sample

Basing on your answer that the reference genome always has one copy. So if the normailized read depth of test sample is 0.4 it will imply that it has one copy...meaning both reference and test has one copies?
From the CNVnator manual they suggested that <0.25 could imply homozygous deletion meaning zero copies while something between 0.25-0.75 imply heterozygous deletion hence 1 copy.

**Comment by abyzov** [comment]
It seems to me that you are comparing two genome. In such a case you can compare genotypes of CNV calls between two samples.
We did such analysis in our 2012 Nature paper, PMID:23160490

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by chirrie** [comment]
Dear Prof.  Abyzov, 
I am comparing two genomes. One is the test sample and the other is the reference genome. I have read the paper but I am not getting a clear answer to my question.
I would like to know from CNVnator results is there a way to know the number of copies in the reference genome relative to the test sample or we always have to make an assumption that the reference genome as one copy(haploid) or two copies(diploid). 
From your previous answers, this is what I understand; of the normalized RD of the test sample is 0.25
it implies it has one copy(haploid) which is more of the same with the reference genome(1 copy), but if the test sample normalized RD is 0.11 then it has Zero copies(haploid) relative to the reference genome which has 1.

What if the reference genome has 4 copies, while the test sample has 12 copies for example? How to explain that?

**Comment by abyzov** [comment]
Hi,
please use option -genotype it prints estimated number of copies for inputed regions.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org/>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by chirrie** [comment]
Dear Prof Abyzov,
I  already have  the number of copies of the inputed regions which I believe it gives the number of copies in the test sample. What I would to know is the number of copies in the reference genome relative to the test sample?  Or should I just assume that the reference genome always have one copy(haploid genome)?

**Comment by abyzov** [comment]
If you have data for both samples then use option -genotype to get the estimate of CN in each sample.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by chirrie** [comment]
Perhaps I could explain the data I have with me.
For reference genome I am using publically available genome data of the domestic goat,,,... then I have sequenced another goat species. My aim was to find copy number variation between my sequenced goat species and the domestic goat(publically available data).
Using CNVnator I can get the number of copies of my study species using the genotype option or by rounding off the normalized rd*2.  So what I have been aiming to get now is the number of copies of the reference genome relative to the test sample.
So I am not getting how I will get it from using genotype option, since it only gives one value which belongs to the sample

**Comment by abyzov** [comment]
Hi,
the reference genome represents one single haplotype.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
