### ISSUE TITLE
GT and CN information

### ISSUE THREAD

**Issue by lee039** [abyzovlab/CNVnator#179]
I have questions related to GT and CN output from CNVnator.

I ran CNVnator on one sample and I inspected the GT:CN outputs.
For deletions, possible GT:CN are either 0/1:1 or 1/1:0. I understood these as heterozygous and homozygous deletions, respectively. Copy number 1 and 0 are also matching with the genotypes.

When it comes to duplication, things seem a bit more complicated. 
Firstly I see 0/1:2 and 1/1:2. This makes to me is a bit confusing. it the GT stands for het_dup and hom_dup, respectively, should CN be 3 and 4 respectively?

Also, from other postings I read that GT=./1 indicates that a high level duplication. Does it mean that CN comes after ./1 is not trustworthy?  For instance, does ./1:4 mean duplication locus with 4 copies? sometimes I see './1:2', which indicates duplication with CN=2, and I am not sure how to interpret this.

Thanks a lot in advance!

Lim

**Comment by abyzov** [comment]
Hi,
in the output 1 represents alternative allele, while 0 represents reference allele.
For a homozygous duplication (copy number 4) 1/1 would mean that each haplotype has duplication. This is the most likely case.

For duplication with higher number of copies we don’t know how the copies are distributed on haplotypes and thus genotype is ./1

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by jazberna1** [comment]
Dear Alexej,

I was wondering if you could please help me to understand the DUP calls with GT:CN 1/1:2. As it is a duplication of both alleles I would presume that the CN would be 4. Interestingly I don't seem to find  any homozygous duplication (1/1) where the CN is 4, all of them are CN 2.

Many thanks
Jorge

**Comment by abyzov** [comment]
Hi,
sorry for later replay.
I think it is a bug.
Just to confirm. The expectation for DUP is the following GT:CN 1/1:4 or GT:CN 0/1:3, right?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by jazberna1** [comment]
Hello Alexej,

Thanks so much for replying.

Yes, those are my expectations.

Many thanks
Jorge

**Comment by abyzov** [comment]
As I see from history at github this was implemented by ‘dnil’.
I wonder whether we can direct you question to him to confirm that this need to be fixed.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by xixifa** [comment]
Dear Alexej,
According to the instructions, I get the results, but the Copy Number(CN) in the generated VCF file is not the same as the copy number in result obtained from -genotype function. So what's the meaning of the copy number in vcf file ?

Thank you

**Comment by abyzov** [comment]
Hello,
could you give an example of the difference that you see.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by xixifa** [comment]
Hello,
The following two figures are screenshots of  the VCF file and the output of -genotype  function., respectively.The red box indicates the number of copies.The blue box and the last one represent the different copy numbers of the two screenshots.Which result is accurate in this case?What are the reasons for this phenomenon?
![1vcf](https://user-images.githubusercontent.com/76728696/109902104-eca3c980-7cd4-11eb-81bb-efcd5948e066.png)
![genotype](https://user-images.githubusercontent.com/76728696/109902122-f0cfe700-7cd4-11eb-863a-1a869f61bf1d.png)

Many thanks

**Comment by abyzov** [comment]
Hi,
sorry for late response. When CN is high (like almost 6 in you example) we don’t have a good guess how copies are located on haplotypes. In fact, because of disperse duplication theoretically there can be multiple haplotypes. That is why genotypes are shown in such a way.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by xixifa** [comment]
Hello，
Thanks so much for replying. I understand what you mean.

Many thanks
