### ISSUE TITLE
Installation error: AliParser.hh:18:3: error: ‘samfile_t’ does not name a type; did you mean ‘samFile’?

### ISSUE THREAD

**Issue by Arun-George-Zachariah** [abyzovlab/CNVnator#180]
While executing make, I encounter the below exception. How do I resolve this issue?

```
Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4.1\" -fopenmp -I/mnt/HDDrive/soumya/CNVnator/root/include      -Isamtools -c cnvnator.cpp -o obj/cnvnator.o
In file included from cnvnator.cpp:14:0:
AliParser.hh:18:3: error: ‘samfile_t’ does not name a type; did you mean ‘samFile’?
   samfile_t   *file;
   ^~~~~~~~~
   samFile
AliParser.hh:19:3: error: ‘bam_index_t’ does not name a type; did you mean ‘bam_hdr_t’?
   bam_index_t *index;
   ^~~~~~~~~~~
   bam_hdr_t
AliParser.hh: In member function ‘std::__cxx11::string AliParser::getQueryName()’:
AliParser.hh:98:52: error: ‘bam1_qname’ was not declared in this scope
   inline string getQueryName() { return (record) ? bam1_qname(record) : ""; }
                                                    ^~~~~~~~~~
AliParser.hh:98:52: note: suggested alternative: ‘bam_set_qname’
   inline string getQueryName() { return (record) ? bam1_qname(record) : ""; }
                                                    ^~~~~~~~~~
                                                    bam_set_qname
Makefile:69: recipe for target 'obj/cnvnator.o' failed
make: *** [obj/cnvnator.o] Error 1
```
Samtools Version used was 1.9

**Comment by abyzov** [comment]
Hi,
not sure but may be samtools version make a difference. I’m currently using samtools 1.8.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by Arun-George-Zachariah** [comment]
Hi Alexej,

Thanks for the update.

It looks like a htslib version issue. Can you kindly confirm the htslib version being used?

**Comment by abyzov** [comment]
Hi,
sorry, on one other computer I”m using 1.9 and seems to be fine.

[abyzov@ CNVnator]$ samtools/samtools --version
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.


Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
