### ISSUE TITLE
Read counts not normalizing to 1

### ISSUE THREAD

**Issue by jamez-eh** [abyzovlab/CNVnator#181]
Hi,

I have read the documentation and ran cnvnator on some of my files and will find I have deletions called 

deletion        chr6:123127601-123144800        17200   446016  0.0666392       4.79643e-43   0.113718        5.02936e-37     0

The docs day that the 4th column should be the read count normalized to one, but that does not seem to be the case.  

Similarly the case for a duplication is also absurd: 

duplication     chr6:123144801-123161500        16700   736759  2.50404e-05     1.53485e-41     0.00122091      1.60939e-35     0

Any idea what is going wrong here?

**Comment by abyzov** [comment]
Hi,
not sure what could be an issue.
Perhaps, you can try to visualize and genotype the regions to see what the tool reports.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
