### ISSUE TITLE
create a new release based upon improvements in installation?

### ISSUE THREAD

**Issue by scalavision** [abyzovlab/CNVnator#182]
Thanks for creating this amazing tool!

Would it be possible to create a release 0.4.2 to include the new improvements made on installation? I was not able to build with the Makefile of relaese 0.4.1, but it worked with the newer version.

It would be nice to refer to an actual release version, when we will use this tool.

**Comment by abyzov** [comment]
Hi,
we’ll make 0.4.2 version but it will take 2-3 weeks, as we are currently working on realizing python version of CNVnator.
Hope this is fine.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by scalavision** [comment]
Thanks a lot !! looking forward to it :-)
