### ISSUE TITLE
WXS CNV command

### ISSUE THREAD

**Issue by brianyiktaktsui** [abyzovlab/CNVnator#183]
Hi I am wondering if there is a tutorial showing how to call whole exome sequencing data using CNVnator? 

Thanks a lot!

**Comment by abyzov** [comment]
Hi,
CNVnator is not intended to be used with exome data. According, there is no such a tutorial.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by brianyiktaktsui** [comment]
Thanks for your reply!
