### ISSUE TITLE
CNVnator Conda environment?

### ISSUE THREAD

**Issue by soungalo** [abyzovlab/CNVnator#185]
Hello,
Are there any plans to make a conda env that will be deposited in anaconda cloud?
Since installation of CNVnator doesn't always go smoothly, it might be a good solution that will save lots of trouble to many users.

**Comment by daynefiler** [comment]
I would give a big second to this!

**Comment by daynefiler** [comment]
Another reason for doing this: I, and I imagine many others, manage samtools & htslib using conda. However, I cannot seem to get the installation to work with conda-installed versions.

This is almost certainly related to #122, #145, #147, #154, & #171.

**Comment by ramiroricardo** [comment]
+1 for the conda package

**Comment by abyzov** [comment]
Thank you all for you input.
We considered this suggestion. It seems not straightforward to make such a package. While we are still thinking to provide such package some time later, currently we are focusing on other higher priority things.
Particularly, we are transitioning to CNVpytor (https://github.com/abyzovlab/CNVpytor), which should be much easier to install compare to CNVnator.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by daynefiler** [comment]
Hi Alexej, do you plan on making a conda distribution of the new CNVpytor?

**Comment by abyzov** [comment]
May be.
Is it necessary? Currently CNVpytor can be installed by pip.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by daynefiler** [comment]
@abyzov  It would go a long way for easily building & sharing reproducible analytic pipelines, e.g. with Snakemake. Can you clarify which aspects of building a conda distribution were not straightforward?

**Comment by christopher-schroeder** [comment]
I agree, that using snakemake and conda is superior to any alternative. So I added cnvpytor to bioconda, which is now available.
I tried to do this also for cnvnator, which is not that hard in princple. But I cannot get make to compile it. This
```
git clone https://github.com/abyzovlab/CNVnator.git

cd CNVnator

ln -s /path/to/src/samtools samtools

make
```
does not work for me and I couldn't fix it.

**Comment by christopher-schroeder** [comment]
I finally also created a conda recipe for cnvnator in bioconda.
You can now install cnvnator by

conda install cnvnator -c bioconda -c conda-forge

**Comment by abyzov** [comment]
Thank you!

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On Apr 30, 2020, at 1:13 AM, Christopher Schröder <notifications@github.com<mailto:notifications@github.com>> wrote:



I finally also created a conda recipe for cnvnator in bioconda.
You can now install cnvnator by

conda install cnvnator -c bioconda -c conda-forge
