### ISSUE TITLE
Detecting CNV for target sequensingdata

### ISSUE THREAD

**Issue by Rostamabd** [abyzovlab/CNVnator#187]
Hello,
I'm using CNVnator to call CNV for a specific region of genome (targeted sequencing data) located on chromosome 8. I don't see any error in running the CNVnator, but the CNV results do not make sense.
Here is the output:
[abdollahiarp@i21a-s2 CNVnator]$ cat SAMPLE.chr8.tsv 
deletion        8:1-67213000    6.7213e+07      9.51699e-05     2.37116e-15     0       2.37123e-15     0       -1
duplication     8:67213001-77212000     9.999e+06       14.3563 0       0       0       0       1
deletion        8:77212001-113320000    3.6108e+07      1.11573e-05     4.41377e-15     0       4.41402e-15     0       1

the header of chr8.fa file:
>8
GAGAGAGATCCAGGTGACAGCTTGAAAGAACATGTATCTGTTGCTGTTGGATGAAGTGAA
CTATAGATTCACAGATGCATTGACTGATGTGTTGTTGAGCTAACTAGAATCTTACTGATT

The header of *.bam file: samtools view -h ../chr8_target.bam|head
@HD     VN:1.5  GO:none SO:coordinate
@SQ     SN:1    LN:158534110
@SQ     SN:2    LN:136231102
@SQ     SN:3    LN:121005158
@SQ     SN:4    LN:120000601
@SQ     SN:5    LN:120089316
@SQ     SN:6    LN:117806340
@SQ     SN:7    LN:110682743
@SQ     SN:8    LN:113319770

I think something is wrong with my *.bam file. The targeted region was extracted by samtools using the following command:
samtools  view input.bam  8:67212333-77212333  -b > chr8_target.bam

the depth of sequencing for target region is   ~40X and coverage is %99.

Looking forward to your help.
Thanks very much in advance,

Rostam,

**Comment by abyzov** [comment]
Hi,
CNVnator is only intended to be used with WGS data. I can’t predict what kind of results it will produce for targeted sequencing.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
