### ISSUE TITLE
Bug in plotrdbaf.py

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVnator#188]
Hi, I'm getting this error:
root@a1a1ae2b281d:/home/dnanexus# /home/dnanexus/CNVnator/plotrdbaf.py -bs 50000 -rdbs 50000 -o /home/dnanexus/in/plotrdbaf.pdf -t chr22 /home/dnanexus/in/UDP-2501_genome.cnvnator.chr22.root chr22:1-50818468
Traceback (most recent call last):
  File "/home/dnanexus/CNVnator/plotrdbaf.py", line 40, in <module>
    for e in t:
TypeError: 'TObject' object is not iterable

Seems like a bug. The root file otherwise works fine for everything else.

**Comment by gevro** [comment]
Anybody able to help?

**Comment by suvakov** [comment]
Thanks

**Comment by yeroslaviz** [comment]
How did you solve it?

what is an annotaed vcf file in this case?

thanks
