### ISSUE TITLE
How to set bin size

### ISSUE THREAD

**Issue by yeswzc** [abyzovlab/CNVnator#19]
As the title.
The best bin sizeto call CNV may be affected by the sequencing depth and genome size and etc..How to quicckly determine a ideal bin size which is very close to the best bin size?

**Comment by abyzov** [comment]
You can use option ‘-eval’ which will print average RD and standard deviation. We recommend to chose bin size such that the ratio is around 4.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by standielpls** [comment]
I am a little confused about the -eval option because I have to state a bin size in order to run it, which means I would have had to select for a bin size beforehand. 

You also said the bin size should not be comparable to read length, what would you recommend for wholge genome sequencing data with read length around 150 bp and read depth around 80 (estimation).

**Comment by abyzov** [comment]
Hi,
yes you have to precalculate histogram to use -eval option.
In your case using small bins size is OK. Just be away that small CNV calls are not trustful as signal in neighboring bins are not  independent.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by amaiacc** [comment]
Hi,
I've run the -eval option after precalculating the histogram, as described above. However, -eval doesn't prompt any message, nor create any files.
I've tried running it on a different binsize which I didn't calculate a histogram for, and that gave an error (`Can't find directory 'bin_50'.`), suggesting that it is doing something, but I seem to be unable to find the output.
Thanks,
amaia 

```
>cnvnator -root sample.root -eval 100
>cnvnator -root sample.root -eval 50\n
Can't find directory 'bin_50'.
```

**Comment by amaiacc** [comment]
Just realized I need to run -stat before running the -eval option.
Sorry for any inconveniences,
amaia

**Comment by yeswzc** [comment]
Thank you!
And,
Could you give a simple explain on why you 'recommend to chose bin size such that the ratio is around 4' ?

**Comment by abyzov** [comment]
Hi,
please read the original paper. It should explain it.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by Jonathan-Abrahams** [comment]
Hi @abyzov ,

Could you possibly provide some psuedocode (or R or python) for how you calculated the ratio of standard deviation to mean? I did find the C++ code you have used in CNVnator but it was too wrapped up in functions for me to really understand it. Clearly this makes it more efficient, but in terms of understanding how to replicate it is harder!

I am looking to test windows of 100,200,300 etc upto 1000 for 3000 bacterial isolates. To run CNVnator 30k times is too much on a modest server.

I have found my estimates differ from yours a small amount. For example mine will be 5 and yours is 6, quite a large difference at times.

In the CNVnator supplementary materials this was written:

> To avoid time consuming calculation to determine the optimal bin size, i.e. comparing CNVs predicted when using different ones, we provide an empirical observation, from analysis of the six individuals, that the optimal bin size is the one at which ratio of average RD signal to its standard deviation (both values are calculated from Gaussian fit) is roughly 4-5

I think my miscalculation stems from my lack of knowledge about how the Guassian fit is related here.

Thanks for your continued support of CNVnator! I am getting very good results for it generally, just need to balance specificity and sensitivity abit more to make the predictions less fractured.

**Comment by huhumiily** [comment]
Hi，
1.
cnvnator -root sample.root -eval 100：
Average RD per bin (1-22) is 13.6645 +- 4.25658 3.21021
Average RD per bin (X,Y)  is 0 +- 0 -nan
2.
cnvnator -root sample.hist.root -eval 100：
Average RD per bin (1-22) is 13.9302 +- 4.68816 2.97135
Average RD per bin (X,Y)  is 0 +- 0 -nan

Could you please tell me which of the above result (sample.root/sample.hist.root) should I use, and does this result satisfy the the requirement (the ratio is around 4)?Thanks a lot!

**Comment by Jonathan-Abrahams** [comment]
@huhumiily 
The last number is the ratio.

> Average RD per bin (1-22) is 13.6645 +- 4.25658 3.21021
Average RD per bin (X,Y) is 0 +- 0 -nan

In your first example, the average coverage is "13.6645", the standard deviation is "4.25658" and therefore  the equation: 13.6645 /4.25658 gives us the final number: 3.21021

Therefore in the first example, the final ratio is 3.21021. The advice is (probably) therefore to continue to experiment with the window size, making it larger probably.

**Comment by huhumiily** [comment]
> @huhumiily
> The last number is the ratio.
> 
> > Average RD per bin (1-22) is 13.6645 +- 4.25658 3.21021
> > Average RD per bin (X,Y) is 0 +- 0 -nan
> 
> In your first example, the average coverage is "13.6645", the standard deviation is "4.25658" and therefore the equation: 13.6645 /4.25658 gives us the final number: 3.21021
> 
> Therefore in the first example, the final ratio is 3.21021. The advice is (probably) therefore to continue to experiment with the window size, making it larger probably.

ok，Thanks for your advice .

**Comment by abyzov** [comment]
Hi,
sorry for delay. Function -eval print the ration to a screen. Looks like have already resolved this.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
