### ISSUE TITLE
what‘s the difference between with -genome parameter or not in the calling workflow？ 

### ISSUE THREAD

**Issue by MaoSihong** [abyzovlab/CNVnator#190]

**Comment by abyzov** [comment]
Hi,
option -genome is only necessary is genome is not described in bam header.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
