### ISSUE TITLE
plotrdbaf.py - no $DISPLAY environment variable

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVnator#191]
Hi,
plotrdbaf.py is giving the error below. Any advice?

Thanks.

root@3958e3cdffa7:/home/dnanexus# /home/dnanexus/CNVnator/plotrdbaf.py -b 100 -rdbs 100 -res 1000 -o output.chr22.pdf -t output output.rootchr22 chr22:18000000-20000000
/home/dnanexus/CNVnator/plotrdbaf.py:142: RuntimeWarning: invalid value encountered in double_scalars
  ng2.append(1.0*m[i][res/2]/m1)
Traceback (most recent call last):
  File "/home/dnanexus/CNVnator/plotrdbaf.py", line 144, in <module>
    fig=plt.figure(1,figsize=(12, 8), dpi=150, facecolor='w', edgecolor='k')
  File "/miniconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/miniconda/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/miniconda/lib/python2.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/miniconda/lib/python2.7/lib-tk/Tkinter.py", line 1825, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by suvakov** [comment]
X display environment is missing. If you are using ssh, try with -X or -Y option (X11 forwarding). What OS you are using?

**Comment by gevro** [comment]
I am running it on a docker Ubuntu image. Why is X display needed? Because it is supposed to output (-o option) to PDF. So X display should not be necessary.

**Comment by suvakov** [comment]
You are right. Matplotlib should detect there is no display before creating backend. I am not sure what could be the reason.

**Comment by gevro** [comment]
Could this help?
https://stackoverflow.com/questions/4931376/generating-matplotlib-graphs-without-a-running-x-server

**Comment by gevro** [comment]
I fixed the bug. You need to add this to plotrdbaf.py:
import matplotlib as mpl
mpl.use('Agg')

Add this before this line:
import matplotlib.pyplot as plt
