### ISSUE TITLE
-vcf annotation

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVnator#192]
Hi,
How does the -vcf option of cnvnator handle multi-sample VCF files?
Is there a way to specify which samples to use for the annotation?

**Comment by suvakov** [comment]
Hi, current version is not working with multi-sample VCF files. Option -vcf reads first sample in this case. You can use vcf-subset to extract one sample from  multi-sample VCF. If there is no specified filename with -vcf option, cnvnator reads standard input (stdin). This way you can pipe output from vcf-subset command to cnvnator without creating additional files.
