### ISSUE TITLE
plotrdbaf.py: options unclear

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVnator#194]
Hi,
For plotrdbaf.py, what is the difference between bins, rdbs, and resolution? This is not clearly documented.
Thanks.

**Comment by suvakov** [comment]
First one is bin size for BAF (SNP B-allele frequency) signal:
   - size of bins (default 100,000): -bs BINSIZE, --binsize BINSIZE
Second one is bin size for RD (read-depth) signal:
   - size of bins for RD signal (default 100,000): -rdbs RDBINSIZE, --rdbinsize RDBINSIZE
Third one is likelihood function resolution:
   -  likelihood function resolution (default 100): -res RESOLUTION, --resolution RESOLUTION

Before using plotrdbaf.py, root file should have RD and BAF bins pre-calculated for specified bin sizes (options -his and -baf). Likelihood function for BAF level is calculated numerically on interval [0,1] with a given resolution (number of points).

**Comment by gevro** [comment]
Thanks. That helps. But two more questions:
1) How do we optimize BAF bin size?
2) Can you provide more information on what the likelihood function is doing exactly and how to choose the resolution?

**Comment by suvakov** [comment]
1. BAF bin size should be optimized regarding the SNP frequency. There should be at least few SNPs in average bin. My suggestion is to use 10k and 100k. Only if searching for chromosomal size events you can go with 1M bin size.

2. Likelihood function provides likelihood for un-phased BAF level. Resolution should be at least 100 to detect 1% change in BAF level.
