### ISSUE TITLE
plotrdbaf.py  - plot documentation and customization

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVnator#195]
Hi,
The BAF vs MAF plots are not clear. Could you please clarify the following?
1) As far as I know, BAF and MAF mean the same thing. What definition do you use exactly for BAF and for MAF? What is the difference between the plots?

2) The MAF plot does not match the documentation. The plot shows up with orange and blue lines, but the documentation describes green dots and blue error bars.

3) Is there a way to change the plot RD bins for the plot regardless of which size bins were used to call the CNVs in the ROOT file?

4) You don't define how the RD plot is drawn.

5) Is there any way to customize the RD plot? It is not useful currently with thick lines and y-axis that is not normalized or transformed. It looks like just raw read depth, which isn't useful.

Thanks.

**Comment by suvakov** [comment]
1. In the second plot the BAF value for each SNP is calculated as number of alternative reads over the total number of reads. In normal (diploid) genomic region it will be randomly (binomially) distributed around 0.5. When there is an event, e.g., duplication, it will split into two branches around 1/3 and 2/3 depending on haplotype. Here MAF is defined as min(BAF,1-BAF) and on the last plot averaged MAF in bins is plotted.

2. Strange. Colors probably depend on matplotlib backend. Thanks for letting us know.

3. Steps -his, -stat, and -baf can be run for multiple bin sizes and some of them use to call CNVs, and some other to make plots using plotcircular.py. In the case of plotrdbaf.py, only RD bin size (-rdbs) from root file is used, and data regarding to SNPs is calculated inside python script, so you can use any bin size for -bs no mater what is inside root (same for plotbaf.py).

4. It is just read-depth (number of read middle points within bin) vs. position.

5. No. The only way is to edit python script.
