### ISSUE TITLE
why some scaffolds reports a failure while making the GC histogram statistics?

### ISSUE THREAD

**Issue by MaoSihong** [abyzovlab/CNVnator#197]
note outputs as follows:
Correcting counts by GC-content for 'scaffold1750' ...
No histogram with GC content for 'scaffold1750' found.
No correction made.

**Comment by abyzov** [comment]
Hi,
hard to say what happened without knowing the command you run. I’m guessing you didn’t provide the file with the reference genome.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by MaoSihong** [comment]
yes, I run the basic pipeline to draw the cnvcalls with only *.bam file as input to make the transit root file. what really confused me is that some scaffolds are also parsed successfully while some are not.

**Comment by abyzov** [comment]
What was the command that you run?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by MaoSihong** [comment]
well，my command was used in a python script as follows：		
os.system("cnvnator -root %s -tree %s" % (rfile,bfile))
os.system("cnvnator -root %s -his 100" % rfile)
os.system("cnvnator -root %s -stat 100" % rfile)
os.system("cnvnator -root %s -partition 100" % rfile)
os.system("cnvnator -root %s -call 100 > %s" % (rfile,callfile))

**Comment by abyzov** [comment]
For -his command one need to specify a file or a directory with sequences for chromosome.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by MaoSihong** [comment]
does it make sense that a *.fq.gz file including whole individual genome data be used as an parameter in -fasta option?

**Comment by abyzov** [comment]
Yes, this is the way to run it.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
