### ISSUE TITLE
Can I use pacbio or nanopore long reads for CNV calling？

### ISSUE THREAD

**Issue by forrwill** [abyzovlab/CNVnator#200]

**Comment by abyzov** [comment]
Yes, you can but it is inefficient as # of reads determine power to find CNVs. With long reads the coverage by reads is not that high.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
