### ISSUE TITLE
Error during installing cnvnator

### ISSUE THREAD

**Issue by biocai** [abyzovlab/CNVnator#203]
I install cnvnator using command conda install cnvnator -c bioconda -c conda-forge.
It reports an error "cnvnator: error while loading shared libraries: libreadline.so.8: cannot open shared object file: No such file or directory".
When I search for libreadline.so, only libreadline.so.7 is found. The system is Ubuntu 18.04.

How to fix this?

**Comment by raydai** [comment]
Hi @biocai , 
I had the same problem before, and I found some issues for the root module under python=2.7.  Thus I decided to create a new environment with python=3.8, and after that, I let the environment solver do the work of determining the remaining dependencies.

`time conda create -n cnvn_env -c conda-forge python=3.8 --yes --quiet  #took ~1 minute`
`source activate cnvn_env`
`time conda install -c pwwang root=6.20.4 cnvnator=0.4.1 --yes --quiet  #took 4min 20sec
cnvnator`

> Not enough parameters.

> CNVnator v0.4.1
> 
> Usage:
> cnvnator -root out.root [-genome name] [-chrom 1 2 ...] -tree file1.bam ... [-lite]
> cnvnator -root out.root [-genome name] [-chrom 1 2 ...] -merge file1.root ...
> cnvnator -root file.root [-genome name] [-chrom 1 2 ...] -vcf [file.vcf.gz | file.vcf] [-rmchr] [-addchr]
> cnvnator -root file.root [-genome name] [-chrom 1 2 ...] -idvar [file.vcf.gz | file.vcf] [-rmchr] [-addchr]
> cnvnator -root file.root [-genome name] [-chrom 1 2 ...] -mask strict.mask.file.fa.gz [-rmchr] [-addchr]
> cnvnator -root file.root [-genome name] [-chrom 1 2 ...] [-d dir | -fasta file.fa.gz] -his bin_size
> cnvnator -root file.root [-genome name] [-chrom 1 2 ...] -baf bin_size [-hap] [-useid] [-nomask]
> cnvnator -root file.root [-chrom 1 2 ...] -stat   bin_size
> cnvnator -root file.root         -eval   bin_size
> cnvnator -root file.root [-chrom 1 2 ...] -partition bin_size [-ngc]
> cnvnator -root file.root [-chrom 1 2 ...] -call   bin_size [-ngc]
> cnvnator -root file.root -genotype bin_size [-ngc]
> cnvnator -root file.root -view  bin_size [-ngc]
> cnvnator -pe file1.bam ... -qual val(20) -over val(0.8) [-f file]
> cnvnator-root file.root [-chrom 1 2 ...] -cptrees newfile.root
> cnvnator-root file.root -ls
> 
> Valid genomes (-genome option) are: NCBI36, hg18, GRCh37, hg19, mm9, hg38, GRCh38
>

**Comment by moldach** [comment]
Can @raydai 's solution please be included in the steps for Install in the README?

None of the other solutions worked...
