### ISSUE TITLE
Large number with CN 

### ISSUE THREAD

**Issue by swu13** [abyzovlab/CNVnator#204]
Hi,

I runed cnvnator for samples, and I got GT:CN results as below. Some CNVs seem to have very large number, like 10958. Is the result correct? And How to explain the results?

Thank you! Any help is appreciate.

0/1:1
0/1:2
./1:10
1/1:0
./1:103
./1:10958
./1:11
./1:112
./1:11570
./1:119
1/1:2
./1:13
./1:130
./1:14213
./1:14391
./1:14684
./1:148013
./1:17
./1:17124
./1:19398
./1:19788
./1:2
./1:21276
./1:21426
./1:22
./1:22930
./1:23
./1:23416
./1:23594
./1:247
./1:25540
./1:2615
./1:273
./1:27958
./1:28621
./1:29
./1:2935090
./1:3
./1:31114
./1:32472
./1:4
./1:40109
./1:40251
./1:5
./1:50434
./1:6
./1:63
./1:6307
./1:66
./1:7
./1:73
./1:79
./1:8
./1:9
./1:9671

**Comment by abyzov** [comment]
Hi,
the results could be correct depending on the reference genome, coverage, bin size, etc.
Any specifics about your analysis?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On May 11, 2020, at 12:38 PM, swu13 <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi,

I runed cnvnator for samples, and I got GT:CN results as below. Some CNVs seem to have very large number, like 10958. Is the result correct? And How to explain the results?

Thank you! Any help is appreciate.

0/1:1
0/1:2
./1:10
1/1:0
./1:103
./1:10958
./1:11
./1:112
./1:11570
./1:119
1/1:2
./1:13
./1:130
./1:14213
./1:14391
./1:14684
./1:148013
./1:17
./1:17124
./1:19398
./1:19788
./1:2
./1:21276
./1:21426
./1:22
./1:22930
./1:23
./1:23416
./1:23594
./1:247
./1:25540
./1:2615
./1:273
./1:27958
./1:28621
./1:29
./1:2935090
./1:3
./1:31114
./1:32472
./1:4
./1:40109
./1:40251
./1:5
./1:50434
./1:6
./1:63
./1:6307
./1:66
./1:7
./1:73
./1:79
./1:8
./1:9
./1:9671
