### ISSUE TITLE
Bin size is not relate to read depth

### ISSUE THREAD

**Issue by PhanNgan** [abyzovlab/CNVnator#205]
Hello,
I have Illumina sequences of 13 populations. I tried several bin size for each sample and get the final bin zise (has ratio RD/SD between 4-5) as the table below:
Sample	Read_length Coverage	Bin_size	Average_RD                   RD/SD 
Sample1		150		60		3000	1227.77 +- 303.412		4.0465
Sample2		150		43		3000	890.766 +- 203.868		4.3693
Sample3		100		32		300		96.574 +- 23.4525		4.1178
Sample4		125		33		700		177.871 +- 42.7231 	4.1633
Sample5		150		42		800		230.661 +- 57.4412		4.0156
Sample6		125		22		300		551.759 +- 128.425		4.2963
Sample7		125		18		2300	361.157 +- 86.8223 	4.1693
Sample8		100		21		800		171.675 +- 42.4138		4.0476
Sample9		100		34		300		104.066 +- 25.813		4.0315
Sample10	100		35		400		135.697 +- 33.4487		4.0568
Sample11	100		37		400		145.903 +- 35.066		4.1608
Sample12	100		33		300		103.922 +- 24.972		4.1615
Sample13	150		32		900		199.828 +- 48.2463		4.1418
I have some questions below:
1. Why all samples have coverage from 18x-60x  should have bin size of 100bp (as suggested in the article) but here the estimated bin size is much more larger?
2. Why Sample 1, sample 2 and sample 7 have good genome coverage but the bin sizes are too large  (3kb and 2.3kb) compare to others? 
3. Is it ok if I use different bin sizes for different populations to search SNVs? 

Could anyone can help me with these questions? Is there any problem with my data?
Thank you very much!

**Comment by abyzov** [comment]
Hi,
ratio of average to sd depends on coverage and data quality. If your coverage is non-uniform (for whatever reason) you have to use large bin size.
Using different bin size is OK but you should be aware that sensitivity to discover CNVs can be different.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On May 12, 2020, at 11:50 AM, PhanNgan <notifications@github.com<mailto:notifications@github.com>> wrote:



Hello,
I have Illumina sequences of 13 populations. I tried several bin size for each sample and get the final bin zise (has ratio RD/SD between 4-5) as the table below:
Sample Read_length Coverage Bin_size "Average_RD_per_bin_(after_GC_correction) Ratio_RD/SD
Sample1 150 60 3000 1227.77 +- 303.412 4.0465
Sample2 150 43 3000 890.766 +- 203.868 4.3693
Sample3 100 32 300 96.574 +- 23.4525 4.1178
Sample4 125 33 700 177.871 +- 42.7231 4.1633
Sample5 150 42 800 230.661 +- 57.4412 4.0156
Sample6 125 22 300 551.759 +- 128.425 4.2963
Sample7 125 18 2300 361.157 +- 86.8223 4.1693
Sample8 100 21 800 171.675 +- 42.4138 4.0476
Sample9 100 34 300 104.066 +- 25.813 4.0315
Sample10 100 35 400 135.697 +- 33.4487 4.0568
Sample11 100 37 400 145.903 +- 35.066 4.1608
Sample12 100 33 300 103.922 +- 24.972 4.1615
Sample13 150 32 900 199.828 +- 48.2463 4.1418

I have some questions below:

  1.  Why all samples have coverage from 18x-60x should have bin size of 100bp (as suggested in the article) but here the estimated bin size is much more larger?
  2.  Why Sample 1, sample 2 and sample 7 have good genome coverage but the bin sizes are too large (3kb and 2.3kb) compare to others?
  3.  Is it ok if I use different bin sizes for different populations to search SNVs?

Could anyone can help me with these questions? Is there any problem with my data?
Thank you very much!
