### ISSUE TITLE
Resource control

### ISSUE THREAD

**Issue by srx3001** [abyzovlab/CNVnator#208]
Hi I ran CNVnator on a relatively small bam file and get this error::

Resources requested (8 procs, 25 GB) are greater than maximum allowed (8 procs, 21.8220596313477 GB))) 

Obviously it asks more than what I have but I dont remember any steps that give it a threading or RAM parameter. I am on a personal desktop with 8 cores / 24GB RAM and sadly dont have access to anything better.
How  can I tell it how many threads /RAM to use?

**Comment by abyzov** [comment]
Hi,
this is the first time we see such an error.
Could you elaborate which command you ran to get this message.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On Jun 21, 2020, at 10:41 AM, Srdjan K <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi I ran CNVnator on a relatively small bam file and get this error::

Resources requested (8 procs, 25 GB) are greater than maximum allowed (8 procs, 21.8220596313477 GB)))

Obviously it asks more than what I have but I dont remember any steps that give it a threading or RAM parameter. I am on a personal desktop with 8 cores / 24GB RAM and sadly dont have access to anything better.
How can I tell it how many threads /RAM to use?

**Comment by srx3001** [comment]
Hello,

I am really sorry, this was my mistake, the error was not generated by
CNVnator, but the environment itself, it's just that the logs were a bit
confusing.
CNVnator works perfectly.

The issue should be closed, sorry for the inconvenience.

Srdjan
