### ISSUE TITLE
Explanation of genotype output

### ISSUE THREAD

**Issue by sestaton** [abyzovlab/CNVnator#21]
I issue the following command to get genotypes and it gives some warnings, along with some numerical assignments:

    cnvnator -root cnvnator_merged_unique.root -genotype 100 -ngc
    >4:174602340-174608711
    Can't find directory 'bin_1000'.
    Can't find directory 'bin_1000'.
    Genotype 4:174602340-174608711 cnvnator_merged_unique.root 2.48289 -1

First, are the warnings about 'bin_1000' of concern and is there a solution to this issue? My main question is what do the numbers mean? It is not clear if this is the expected output or what it means exactly.

What I would like is to extract per sample copy number estimates from the called CNV region. Is this possible?

Thanks.

**Comment by abyzov** [comment]
Hi,
warnings are not the issue. By default CNVnator estimates CN (last two number in each line) using bin size that you provided and bins of 1 kbp. If histogram for 1 kbp bins don’t exist then the software prints the warning.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by sestaton** [comment]
Okay, do the copy numbers correspond to those bins? The first one is given since the histogram for 100bp bin exists and -1 is for 1000bp bin since it doesn't exist?

**Comment by abyzov** [comment]
Yes, this is correct.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by ggg3** [comment]
Hi,
I get the following error when running the command for creating histogram. The reference fasta file is in the same folder as test.root with permissions -rwxrwxrwx

$ cnvnator -root test.root -chrom chrI -his 100 -genome Scer3.fa

Allocating memory ...
Done.
Calculating histograms with bin size of 100 for 'chrI' ...
Making GC histogram for 'chrI' ...
Can't open file with chromosome sequence.
No chromosome/contig information parsed.
Sequence length (0) is different from expectation (230218) for 'chrI'.
Doing nothing!
Done.

**Comment by abyzov** [comment]
Hi,
in your case CNVnator tries to find file chrI.fa in the current directory. But seems like it does not exist.
Please provide the files or specify directory with the file using option -d

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by ggg3** [comment]
The directory should be same as ?

**Comment by abyzov** [comment]
Not sure what you are asking.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by ggg3** [comment]
You were right. It worked!
Ignore my earlier comment.

**Comment by sestaton** [comment]
I just want to follow up on my question and then we can close this issue. Is there a way to get the copy number (or inferred depth) per sample, or will CNVnator only report the CNV region?

**Comment by abyzov** [comment]
Hi,
I missed your question before. Yes, you can get genotype, please use option -genotype described in README file.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by sestaton** [comment]
I was asking if you can get per sample information (from a single merged root file) whereas the -genotype option seems to give depth/copy per region information only, not by sample. Maybe the way is to create separate root files and call -genotype on each, is that the suggestion?

**Comment by abyzov** [comment]
Hi,
yes, this is correct. One needs to create a .root file for each sample.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by sestaton** [comment]
Thanks for the response.
