### ISSUE TITLE
add #include <set> in the IO.cpp

### ISSUE THREAD

**Issue by xiaotiqingzz** [abyzovlab/CNVnator#215]
It's may be a bug

cd CNVnator_v0.4.1/src && make
```
Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4.1\" -fopenmp -I/home/biosoft/root//include      -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c IO.cpp -o obj/IO.o
IO.cpp: In member function ‘void IO::cptrees(std::string, std::string*, int)’:
IO.cpp:420:3: error: ‘set’ was not declared in this scope
   set<string> userchr;
   ^
IO.cpp:420:14: error: expected primary-expression before ‘>’ token
   set<string> userchr;
              ^
IO.cpp:420:16: error: ‘userchr’ was not declared in this scope
   set<string> userchr;
                ^
make: *** [obj/IO.o] Error 1

```
IO.cpp line 420 code `set <string> userchr`， but unfind `#include <set>` in IO.cpp
When I add  `#include <set>` in IO.cpp, it OK and no error.

**Comment by abyzov** [comment]
Thanks for letting us know.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On Jul 23, 2020, at 10:42 PM, xiaotiqingzz <notifications@github.com<mailto:notifications@github.com>> wrote:



It's may be a bug

cd CNVnator_v0.4.1/src && make

Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4.1\" -fopenmp -I/home/biosoft/root//include      -Isamtools -Isamtools/htslib-1.9 -Isamtools/htslib-1.9/htslib -c IO.cpp -o obj/IO.o
IO.cpp: In member function ‘void IO::cptrees(std::string, std::string*, int)’:
IO.cpp:420:3: error: ‘set’ was not declared in this scope
   set<string> userchr;
   ^
IO.cpp:420:14: error: expected primary-expression before ‘>’ token
   set<string> userchr;
              ^
IO.cpp:420:16: error: ‘userchr’ was not declared in this scope
   set<string> userchr;
                ^
make: *** [obj/IO.o] Error 1



IO.cpp line 420 code set <string> userchr， but unfind #include <set> in IO.cpp
When I add #include <set> in IO.cpp, it OK and no error.

**Comment by xin8you** [comment]
Hi @xiaotiqingzz 
How did you solve this error?

**Comment by xiaotiqingzz** [comment]
> Hi @xiaotiqingzz
> How did you solve this error?

**Comment by xiaotiqingzz** [comment]
> Hi @xiaotiqingzz
> How did you solve this error?

add `#include <set>` in IO.cpp

**Comment by xin8you** [comment]
@xiaotiqingzz 
 thanks for your help!
Best!
Xin
