### ISSUE TITLE
CNVnator failed to install : HisMaker.hh:15:20: fatal error: TFrame.h: No such file or directory

### ISSUE THREAD

**Issue by nitha26** [abyzovlab/CNVnator#222]
Hi,

I am not able to install CNVnator in centos7.

As described in the installation file, I tried to install install "root"  as said by in this link "https://root.cern/install/#centos" by yum install root command and the package was successfully installed. After that when trying to install CNVnator getting these following errors. 

``src]# ln -s /home/cbran/softwares/CNVnator_v0.4.1/src/samtools samtools
ln: failed to create symbolic link ‘samtools/samtools’: File exists
src]# make
Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4.1\" -fopenmp -I/include      -Isamtools -Isamtools/htslib-1.10 -Isamtools/htslib-1.10/htslib -c cnvnator.cpp -o obj/cnvnator.o
In file included from cnvnator.cpp:15:0:
HisMaker.hh:15:20: fatal error: TFrame.h: No such file or directory
 #include <TFrame.h>
                    ^
compilation terminated.
make: *** [obj/cnvnator.o] Error 1``

Tried using " src]# make OMP=no" but still the same error exists.  

Root installation was fine and was able to execute.
``home]# root  

  | Welcome to ROOT 6.22/02                        https://root.cern |
  | (c) 1995-2020, The ROOT Team; conception: R. Brun, F. Rademakers |``

How can I solve this error and install CNVnator?

Thank you for your help.
Nitha

**Comment by abyzov** [comment]
Hi,
looks like you don’t have ROOTSYS variable set.
Most likely you can fix this by running thisroot.sh (or thisroot.csh) in the bin dir within the ROOT installation.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by nitha26** [comment]
I had run thisroot.sh. but still, I am getting following errors

[root@bratatilab src]# make
Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4.1\" -fopenmp -I/home/cbranu/softwares/build/include      -Isamtools -Isamtools/htslib-1.10 -Isamtools/htslib-1.10/htslib -c cnvnator.cpp -o obj/cnvnator.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4.1\" -fopenmp -I/home/cbranu/softwares/build/include      -Isamtools -Isamtools/htslib-1.10 -Isamtools/htslib-1.10/htslib -c EXOnator.cpp -o obj/EXOnator.o
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4.1\" -fopenmp -I/home/cbranu/softwares/build/include      -Isamtools -Isamtools/htslib-1.10 -Isamtools/htslib-1.10/htslib -c IO.cpp -o obj/IO.o
IO.cpp: In member function ‘void IO::cptrees(std::string, std::string*, int)’:
IO.cpp:420:3: error: ‘set’ was not declared in this scope
   set<string> userchr;
   ^
IO.cpp:420:13: error: expected primary-expression before ‘>’ token
   set<string> userchr;
             ^
IO.cpp:420:15: error: ‘userchr’ was not declared in this scope
   set<string> userchr;
               ^
Could you please point out where exactly I am making mistakes?

Thanks.

**Comment by nitha26** [comment]
@abyzov the above command is when i just did thisroot.sh.

Today when I did source  **thisroot.ch** observed the following output

``I had tried to install root package from  
[root@bratatilab bin]# source thisroot.csh  
-bash: /home/cbranu/softwares/root/obj/bin/thisroot.csh: line 17: syntax error near unexpected token `('  
-bash: /home/cbranu/softwares/root/obj/bin/thisroot.csh: line 17: `set ARGS=($_)'  ``

how to fix the CNVnator issues  ?
Thanks

**Comment by nitha26** [comment]
@abyzov

**Comment by nitha26** [comment]
@abyzov the above command is when i just did thisroot.sh.

Today, when I did source thisroot.ch, observed the following output

I had tried to install root package from [root@bratatilab bin]# source thisroot.csh -bash: /home/cbranu/softwares/root/obj/bin/thisroot.csh: line 17: syntax error near unexpected token `(' -bash: /home/cbranu/softwares/root/obj/bin/thisroot.csh: line 17: `set ARGS=($_)'

how to fix the CNVnator issues?
Thanks

**Comment by abyzov** [comment]
Hi,
may be it is an inconsistency between the shell you are using and script you are running?
The script has extension csh but the error message seems to mention bash.
Could you try excecuting thisroot.sh

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by nitha26** [comment]
Hi,

I tried it using source thisroot.sh. but still, I am getting the following errors while I am doing make in CNVnator

```[root@bratatilab src]# make
Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4.1\" -fopenmp -I/home/cbranu/softwares/root/obj/include      -Isamtools -Isamtools/htslib-1.10 -Isamtools/htslib-1.10/htslib -c IO.cpp -o obj/IO.o  
IO.cpp: In member function ‘void IO::cptrees(std::string, std::string*, int)’:  
IO.cpp:420:3: error: ‘set’ was not declared in this scope    
   set<string> userchr;  
   ^
IO.cpp:420:13: error: expected primary-expression before ‘>’ token  
   set<string> userchr;  
             ^
IO.cpp:420:15: error: ‘userchr’ was not declared in this scope  
   set<string> userchr;  
               ^
make: *** [obj/IO.o] Error 1  ``

-------------------------------------
Please give me a solution to fix this CNVnator in centos7.

Thanks

**Comment by abyzov** [comment]
Hello,
I believe this issue of incompatibility with some compiler was solved. Current code from github shouldn’t have this issue.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by Alpha-nek** [comment]
Hello, I'm having a similar problem: I have installed root from source and changed it to c++17 (since that was an initial error with lower c++), I have run thisroot.sh, I've confirmed my ROOTSYS path and library path, I've included samtools and htslib and sam.h in the CNVnator file, and downloaded the latest version of CNVnator (0.4.1), I've also tried to download it via Conda:bioconda with same error. 

Here's what I get when I run $ROOTSYS:
"$ROOTSYS
-bash: /workspace/bin/rootinstall: Is a directory"

Here's the root -config --cflags and --version and --libs:
"-pthread -std=c++17 -m64 -I/workspace/bin/rootinstall/include 6.32.08 -L/workspace/bin/rootinstall/lib -lCore -lImt -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lROOTVecOps -lTree -lTreePlayer -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -lROOTDataFrame -Wl,-rpath,/workspace/bin/rootinstall/lib -pthread -lm -ldl -rdynamic"

It seems that it can't find one of the graph core class (which I believe is in the root library above ^) from root which is needed the CNVnator file HisMaker.hh

This is the error:
"Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4.1\" -fopenmp -I/workspace/bin/rootinstall/include      -Isamtools -Isamtools/htslib-1.21 -Isamtools/htslib-1.21/htslib -c cnvnator.cpp -o obj/cnvnator.o
In file included from cnvnator.cpp:15:
HisMaker.hh:15:10: fatal error: TFrame.h: No such file or directory
   15 | #include <TFrame.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:70: obj/cnvnator.o] Error 1"

Any help would be appreciated, I have spent an embarrassing amount of time trying to fix this. Thanks

Solved:
Download root via conda, download CNVnator via bioconda, all set. thanks

**Comment by abyzov** [comment]
Hi,
looks like path to header files is incorrect.
This is where I find TFrame.h on my system


/Users/abyzov/bin/root-v6.34.02/include/TFrame.h


My $ROOTSYS is /Users/abyzov/bin/root-v6.34.02

Alexej Abyzov, Ph.D., Consultant
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 7-91
Rochester, MN 55905
www.abyzovlab.org
<http://www.abyzovlab.org>tel: +1-(507)-538-0978
