### ISSUE TITLE
Running CNVnator using scaffolds

### ISSUE THREAD

**Issue by chirrie** [abyzovlab/CNVnator#223]
Dear Prof Abyzov,

I intend to use a genome that has scaffolds in place of chromosomes as reference for copy number variation detection using CNVnator. I have read the CNVnator manual at it seems it only accepts chromosomes.  I am wondering if there is a way to tailor it to work with scaffolds.

**Comment by abyzov** [comment]
Hello,
CNVnator parses genome information from bam header. So, you should be able to work with scaffolds.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
