### ISSUE TITLE
How to get the real copy number(CN)?

### ISSUE THREAD

**Issue by omG0-hub** [abyzovlab/CNVnator#224]
I want to know how to get the Copy Number(CN) from normalized_RD to 1 (by using -call option)
I saw the -call option normalized RD to 1, I run the -call option (binsize:100, X30 human WGS data) and got the CNV data.

Q1.
If i get the RD (normalized to 1) below 1 ( RD < 1), it indicates "deletion" ? while i get the RD over 1 ( RD > 1 ), it represent "duplication" ?

Q2.
If this is correct, how to get the Copy number from the RD (normalized to 1)? 
Is it right to obtain the real copy number of all CNV positions, applied the following calculation method
estimated real copy number = round( normalized_RD *2 ) ?

I found some exceptional examples in my CNV data, 
ex) 
CNV type --- normalized RD
duplication --- 1.23617
deletion --- 0.750961
if i applied above calculation method, it represent CN = 2 (round (1.23617 * 2)). I think CN =2 means is not a duplication type.
Likewise, in case of deletion above, deletion type of CNV, it calculated CN =2 (round (0.750961 * 2)).

(#153 ), (#213 ), (#216 )
I referenced many posting, but I could not fully understand about getting real CN value.
I sincerely want to get the CN method.

Thank you,

**Comment by abyzov** [comment]
Hi,
please use -genotype function.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by xiucz** [comment]
cnvnator version 0.4.1 still gives the `-1` genotype if the bin size is not 1000.

**Comment by abyzov** [comment]
Hello,
not sure which version you are using but, perhaps, you should use -unique option when doing first step of parsing bam file.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by xiucz** [comment]
@abyzov 
I am sorry for missing your last comment.
Today, I meet the same quesiton, the CNVnator version I use is **v0.4.1**. When I try to use 
```
~/CNVnator/cnvnator -root 17.file.root -unique -chrom chr17 -tree sorted.bam
```
It reports waring:
```
Unknown option '-unique'.
```
After checking other issues, the newest version use this option by default, So do I ignore `-unique' option in my extracting step? 
And one of the result is:
```
duplication	chr17:19050001-20045000	995000	1.35952	0	473.693	0	473.693	0.0753048
```
and the genotype file is
```
Genotype chr17:19050001-20045000 17.file.root 2.71904 -1
```
I want to know what the real copy number is.

Thank you very much.
Xiucz

**Comment by abyzov** [comment]
Hi,
-unique option is no default and don’t need to specify it.
In your case the estimated CN 2.71904, which can be rounded off to 3 if you believe you have gremline (or constitutional) CNV.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by jingydz** [comment]
I have the same question.
You said,"you should use -unique option when doing first step of parsing bam file."
But in CNVnator v0.4.1, adding the -unique option will report "Unknown option '-unique'.".
I am so confused.

**Comment by xiucz** [comment]
@jingydz 
I use https://github.com/abyzovlab/CNVpytor now.
