### ISSUE TITLE
remove read from a bam or not?

### ISSUE THREAD

**Issue by QuanLG** [abyzovlab/CNVnator#226]
Hi,
    Does cnvnator uses all the reads from a mark duplicated BAM for  calling or does it remove the mark duplicated reads if BAM is mark duplicated?
Thanks

**Comment by abyzov** [comment]
Hi,
yes, please remove duplicated reads.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
