### ISSUE TITLE
Capturing large scale CNVs

### ISSUE THREAD

**Issue by yasin-uzun** [abyzovlab/CNVnator#229]
I am specifically interested in discovering focal (1-3 Mb) and chromosomal arm level (tens of Mb size) deletions and duplications. How should I run CNVnator in this context? Should I decrease the resolution by choosing large values for -his or -part parameters? Or what else I can do? 

Related with this issue, is there any additional documentation in addition to the read me page (https://github.com/abyzovlab/CNVnator), which can guide about parameter settings? 

I will appreciate if you can guide. Thanks.

**Comment by abyzov** [comment]
Hi,
for higher coverage one can chose smaller bins size. Small bin size will result in better resolution of small CNVs.
Please read the original CNVnator publication about the recommendation on selecting bin size for a particular coverage.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
