### ISSUE TITLE
Help diagnosing CNVnator error

### ISSUE THREAD

**Issue by rachelzoeb** [abyzovlab/CNVnator#23]
I am trying to run CNVnator to obtain a file with normalized read depth values for SNP locations.  I installed root and CNVnator as instructed and am attempting to run the first step (extracting read mapping from the bam file).  The command I used is here:

cnvnator -root HR1204.root -genome /home/blumhagenr/Chromosomes/chr1.fa -chrom chr1 -tree reduced_filtered_HR1204.bam

However, I get this as output and am having trouble diagnosing the error message.  Can you help me determine what may be the cause and how best to proceed?

Error: cannot open file "iostream"  (tmpfile):2:
**\* Interpreter error recovered ***
Parsing file reduced_filtered_HR1204.bam ...
Allocating memory ...
Done.
Filling and saving tree for 'chr1' ...
Fatal in TVirtualStreamerInfo::Factory: Cannot find the plugin handler for TVirtualStreamerInfo! However $ROOTSYS/etc/plugins/TVirtualStreamerInfo is accessible, Check the content of this directory!
aborting
Error in TUnixSystem::StackTrace script /etc/root/gdb-backtrace.sh is missing
Aborted

**Comment by abyzov** [comment]
Hi,
with bam file you don’t need to specify genome (genome is described in bam header). So, you command should looks like

cnvnator -root HR1204.root -chrom chr1 -tree reduced_filtered_HR1204.bam

I’m not sure but this could be the root of the problem. Another possiblity is that something went wrong with ROOT installation. Are you able to run ROOT normally/

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by rachelzoeb** [comment]
We reinstalled ROOT v6 and cnvnator and it seems to be working now, I think the problem was ROOT was not properly installed initially.  Thank you for your help.
