### ISSUE TITLE
How can I interpret E1 of 0 ?

### ISSUE THREAD

**Issue by Nifaste** [abyzovlab/CNVnator#230]
Hi,
I noticed that most of the CNV events identified by CNVnator (v0.4.1) have a pvalue (E1) equal to 0.
How can I interpret such a result ?
Are CNVs with E1 if 0 significants ?

Here is an example :
`
    duplication	ref_wt:1-19800	19800	1.47946	0	38.2639	0	238.929	0.0489594

    duplication	ref_wt:25201-32800	7600	1.35124	0	2.52677	1.49298e-07	610.356	0.0872155

    duplication	ref_wt:65801-75400	9600	1.29228	0	0.00511354	5.24252e-09	1.43382	0.0679411

    duplication	ref_wt:3766601-3771200	4600	1.27729	5.81987e-06	6732.16	0.107267	1.88768e+06	0

    duplication	ref_wt:3866201-3888300	22100	1.44663	0	3.56663e-27	0	6.33359e-24	0.0451221

    duplication	ref_wt:3988701-3993500	4800	1.47856	3.98431e-10	100547	0.000829207	0.375793	0

    duplication	ref_wt:4073201-4128400	55200	1.25118	0	14.926	0	29.7915	0.0274079
`

**Comment by abyzov** [comment]
Hello,
yes they are significant.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
