### ISSUE TITLE
Except_Frame_T error when running make

### ISSUE THREAD

**Issue by neharajkumar** [abyzovlab/CNVnator#232]
When I try to run make I get the following error. I have the root package installed, but I'm still getting it. Any help is greatly appreciated. Thank you!

Compiling with parallel (OpenMP) support
g++ -O3 -std=c++17 -DCNVNATOR_VERSION=\"v0.4.1\" -fopenmp -I/u/home/n/neharajk/miniconda3/include      -Isamtools -c cnvnator.cpp -o obj/cnvnator.o
In file included from /u/home/n/neharajk/miniconda3/include/assert.h:5,
                 from /u/home/n/neharajk/miniconda3/include/TCollection.h:33,
                 from /u/home/n/neharajk/miniconda3/include/TSeqCollection.h:25,
                 from /u/home/n/neharajk/miniconda3/include/TObjArray.h:25,
                 from /u/home/n/neharajk/miniconda3/include/TClass.h:29,
                 from /u/home/n/neharajk/miniconda3/include/TKey.h:17,
                 from HisMaker.hh:16,
                 from cnvnator.cpp:15:
/u/home/n/neharajk/miniconda3/include/except.h:15:32: error: conflicting declaration 'typedef struct Except_Frame_T* Except_Frame_T'
   15 | typedef struct Except_Frame_T *Except_Frame_T;
      |                                ^~~~~~~~~~~~~~
/u/home/n/neharajk/miniconda3/include/except.h:15:16: note: previous declaration as 'struct Except_Frame_T'
   15 | typedef struct Except_Frame_T *Except_Frame_T;
      |                ^~~~~~~~~~~~~~
/u/home/n/neharajk/miniconda3/include/except.h:17:18: error: field 'prev' has incomplete type 'Except_Frame_T'
   17 |   Except_Frame_T prev;
      |                  ^~~~
/u/home/n/neharajk/miniconda3/include/except.h:16:8: note: definition of 'struct Except_Frame_T' is not complete until the closing brace
   16 | struct Except_Frame_T {
      |        ^~~~~~~~~~~~~~
make: *** [obj/cnvnator.o] Error 1

**Comment by abyzov** [comment]
Hi,
looks like the error in assert.h file which is not part of CNVnator neither of ROOT. Not sure what causes this error.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
