### ISSUE TITLE
Compilation error CNVnator

### ISSUE THREAD

**Issue by assane-mbodj** [abyzovlab/CNVnator#236]
hi 
I am new in programming and I was trying to install CNVnator but as error:
make
Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.4.1\" -fopenmp -I/afs/cern.ch/sw/lcg/external/root/vers/arch/root/include      -Isamtools -c cnvnator.cpp -o obj/cnvnator.o
cc1plus: warning: samtools: not a directory
In file included from cnvnator.cpp:14:
AliParser.hh:10:10: fatal error: sam.h: Aucun fichier ou dossier de ce type
   10 | #include "sam.h"
      |          ^~~~~~~
compilation terminated.
make: *** [Makefile:70 : obj/cnvnator.o] Erreur 1

And I also wanted to know if we can use CNVnator on Vegetal data 
Thanks

**Comment by abyzov** [comment]
Hi,
looks like you don’t a link to samtools dir.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by BiMo88** [comment]
Hi, I've create a symbolic link to samtools in the CNVnator folder but I have the same error message

**Comment by abyzov** [comment]
Is there sam.h file in samtools folder

>ls samtools/sam.h
samtools/sam.h

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by BiMo88** [comment]
> hi
> I am new in programming and I was trying to install CNVnator but as error:
> make
> Compiling with parallel (OpenMP) support
> g++ -O3 -std=c++11 -DCNVNATOR_VERSION="v0.4.1" -fopenmp -I/afs/cern.ch/sw/lcg/external/root/vers/arch/root/include -Isamtools -c cnvnator.cpp -o obj/cnvnator.o
> cc1plus: warning: samtools: not a directory
> In file included from cnvnator.cpp:14:
> AliParser.hh:10:10: fatal error: sam.h: Aucun fichier ou dossier de ce type
> 10 | #include "sam.h"
> | ^~~~~~~
> compilation terminated.
> make: *** [Makefile:70 : obj/cnvnator.o] Erreur 1
> 
> And I also wanted to know if we can use CNVnator on Vegetal data
> Thanks

I think you have created a symbolic link to the samtools program, you should create the symbolic link to the samtools folder
