### ISSUE TITLE
CNVnator Genotype

### ISSUE THREAD

**Issue by biozzq** [abyzovlab/CNVnator#24]
Dear all,

Recently, I want to do CNV association study on population scale. I have run CNVnator and get the raw CNV regions for each sample.  I removed CNVs overlapped with genome gap region and the `q0` value over 0.5 for each sample. To get the population CNV regions, I required a reciprocal overlap of CNVs more than 90% of their lengths. After above processes, I got a location database and used this database to genotype for each sample. But when I compared the RD value, I found it will have a big difference between the RD reported by call and the RD reported by genotype when their boundaries have a little differences. I just  doubt that the RD in call has been normalized to one but the RD in genotype are two copies based. Is this right?

Any suggestions will be appreciated!

Best

**Comment by abyzov** [comment]
Hi,
yes this is correct. The results of calling is RD signal normalized to 1, while genotyping returns estimated number of copies, which is 2 for all germline chromosomes except for X and Y in males.


Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
