### ISSUE TITLE
Parallelization in partition step?

### ISSUE THREAD

**Issue by apregier** [abyzovlab/CNVnator#25]
I am trying to understand what parallelization is available in the partition step.  I am using someone's wrapper to an older version of cnvnator, and they extract each chromosome to a separate root file and run partition in parallel, then serially merge it back to the original root file.  Is this still necessary, or have you added inherent parallelization to the partition step?

**Comment by abyzov** [comment]
Hi,
no there is not need to do this anymore. The new version can utilize as many CPUs as available for partitioning.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by apregier** [comment]
Thank you!  How about the tree creation step?  Is it safe to run multiple tree creation processes at once on the same root file?  Or do they need to be written to different root files and then merged?

**Comment by abyzov** [comment]
Hi,
I wouldn’t recommend to write multiple processes into the same files. We haven’t tested it I’m afraid this can create issues.
Reading per chromosome and merging is a possible solution. Though I’m not sure this will give substantial speed up compare to parsing .bam files with one thread. Multiple processes can suffer from I/O delay when querying the same files.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
