### ISSUE TITLE
Exporting CNV calls as VCFs

### ISSUE THREAD

**Issue by FerFrancis** [abyzovlab/CNVnator#254]
Hi Abyzov,

Hope you are well.

I have the called CNV by cnvnator for the whole BAM of WGS, for 214 subjects but Ia need to reduce the CNVs pool cause there are some that are the same in the sample (is a family sample), so I am going to use intersect (https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html), but the input need to be in VCF format. 
I am working in a cluster environment, it has CNVnator v0.4.1, but the  cnvnator2VCF.pl in not available. 
Is there any way to obtain the called CNV by cnvnator in a VCF format without using cnvnator2VCF.pl? Or how can I do to make cnvnator2VCF.pl work?

Thanks in advance for the response.

**Comment by abyzov** [comment]
Hello,
may be you can get that script from other version of CNVnator.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
