### ISSUE TITLE
Questions on CNV calling results

### ISSUE THREAD

**Issue by XinyiZhu1007** [abyzovlab/CNVnator#26]
Hello,

I am a new-comer in bioinformatics and recently while I am using CNVnator v0.3.2 for a project I bump into questions when trying to make sense of results from CNV calling.
1. I saw in many literatures people filter their raw CNV calls using p=0.05 as cut-off, however the output i'm seeing contains 4 e-vals instead of p-vals. Is it the case that the e-vals are converted from the p-vals (which is calculated from the t-test)? or the e-vals and the p-vals in the output can be treated interchangeably?
2. for e-val2, what does it mean by "the region to be in the tail of Gaussian distribution"? Can I interpret this value as the significance of the call being a CNV?
3. for e-val3 and e-val4, what does it mean by "for the middle of CNV" and what's the purpose of looking specifically in the middle of CNV? 
Thank you in advance for comments and help!

**Comment by abyzov** [comment]
Hi,
e-values show how many regions with such RD one can find across whole genome by chance.
First e-values is more conservative.
You can ignore e-val3 and e-val4.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by XinyiZhu1007** [comment]
Hello, 

Thank you very much for your comment!
If I understand it correctly, the e-vals in CNVnator can be seen similar to the e-values in BLAST?

Xinyi

**Comment by abyzov** [comment]
I guess so.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745







On Jun 17, 2016, at 11:15 AM, XinyiZhu1007 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

Thank you very much for your comment!
If I understand it correctly, the e-vals in CNVnator can be seen similar to the e-values in BLAST?

Xinyi
