### ISSUE TITLE
"Assuming male individual!" output

### ISSUE THREAD

**Issue by lgmgeo** [abyzovlab/CNVnator#265]
Hi,

During the CNV call step:
```
$cnvnatorPATH/cnvnator -root sample.root -call 1000 > sample_cnvnator.out
```
CNVnator (V0.4.1) returns the following message on my male samples:
```
Assuming male individual!
```

With female samples, CNVnator returns no message.

Can you explain how CNVnator assumes the gender of the sample (correctly in my samples)?

Many thanks,

Véronique

**Comment by abyzov** [comment]
Hi,
it is based on coverage of autosomes and sex chromosomes.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978

**Comment by lgmgeo** [comment]
Ok, thanks.
PS: Could be nice to also have "Assuming female individual!" in the output

**Comment by lgmgeo** [comment]
gender normalization: cf #129
