### ISSUE TITLE
Use of the "-genome" option?

### ISSUE THREAD

**Issue by lgmgeo** [abyzovlab/CNVnator#266]
Hi,

I wonder what is the use of the "-genome" option in CNVnator:
![image](https://user-images.githubusercontent.com/49909073/164027334-d6601c85-080f-450a-8b7e-8ea14c3bfa12.png)

Does CNVnator use this information in its code? 
Or is it just carried over to the output files?

Many thanks in advance,

Véronique

**Comment by abyzov** [comment]
Hi,
with bam files containing header this option is not necessary.
It is only needed for sam files without header.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978

**Comment by lgmgeo** [comment]
Got it.

Thanks!!
