### ISSUE TITLE
Cling error

### ISSUE THREAD

**Issue by rernst** [abyzovlab/CNVnator#27]
I am getting an error about cling and missing libraries when running CNVnator v0.3.2 using the following bash script:

``` bash
source /path/to/root-6.06.02/bin/thisroot.sh
/path/to/CNVnator_v0.3.2/src/cnvnator -root out.root -tree bamfile.bam
```

This is the full error message:

```
ERROR in cling::CIFactory::createCI(): cannot extract standard library include paths!
Invoking:
    echo | LC_ALL=C c++  -pipe -m64 -Wall -W -Woverloaded-virtual -fsigned-char -fPIC -pthread -std=c++11 -Wno-deprecated-declarations -Wno-comment -Wno-unused-parameter -Wno-maybe-uninitialized -Wno-unused-but-set-variable -Wno-missing-field-initializers  -fPIC -fvisibi
results in
with exit code 256
input_line_1:1:10: fatal error: 'new' file not found
#include <new>
         ^
input_line_3:38:10: fatal error: 'string' file not found
#include <string>
         ^
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
```

I am running this on centos7 and root 6.06.02. Both cnvnator and root are build from source.  Any idea how to solve this?

**Comment by bintriz** [comment]
Is your root running well? It happens usually when root hasn’t been installed correctly. Check the installed root first.

Thanks,

**Comment by rernst** [comment]
Yes root is running fine, this error occurs both with the binary distribution and the source build of root.

```bash
source /path/to/root-6.06.02/bin/thisroot.sh
root
 ----------------------------------------------------------------
  | Welcome to ROOT 6.06/02                    http://root.cern.ch |
  |                                   (c) 1995-2014, The ROOT Team |
  | Built for linuxx8664gcc                                        |
  | From heads/master@v6-07-02-437-gb06340c, Mar 02 2016, 19:01:57 |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'     |
   ----------------------------------------------------------------

root [0] .q
```

**Comment by bintriz** [comment]
Could you run another root script instead of cnvnator, for example, one of demo script included in root, in order to confirm that this is not the root issue?

**Comment by rernst** [comment]
Sure, I have run both .x demos.C and .x benchmarks.C in the tutorials folder of root. All demo's and benchmarks work fine without errors.

```
source /path/to/root-6.06.02/bin/thisroot.sh
root > .x demos.C
root > .x benchmarks.C
```

**Comment by rernst** [comment]
Do you have any clue what this could be? Besides root and samtools are there other dependencies that could be missing on our system?

I tried different versions of root but all give exactly the same error.

**Comment by abyzov** [comment]
Hi,
sorry for late reply.
I found similar issue discussed at https://root.cern.ch/phpBB3/viewtopic.php?t=19645
Some users claim that this is an issue of Xcode.
“Problem is due to not agreeing to the new licence agreement of Xcode and the SDK. For mee launching Xcode and accepting the (new) license agreement fixed the problem.”
Could you try this.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by rernst** [comment]
Xcode is apple mac osx specific right? We are running on centos 7.

The really weird and annoying thing about this problem is that it only seems to occur when running CNVnator, were other users report similar errors when building or starting root. I can run all demo scripts included with root without any errors.

**Comment by abyzov** [comment]
That is right.
I’m using root 6.04. Looks like this is platform dependent issue.

Would you try to run

 $ROOTSYS/bin/root-config —libs

then include output into Makefile for ROOTLIBS and then recompile CNVnator.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by rernst** [comment]
Yes seems like that. Just to be sure I am doing the right thing, I changed the following lines:

Line 5:
```
ROOTLIBS = -L$(ROOTSYS)/lib/root -lCore -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -pthread -lm -ldl -rdynamic
```
Line 7:
```
ROOTLIBS = -L$(ROOTSYS)/lib      -lCore -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -pthread -lm -ldl -rdynamic
```

I just changed them both to be sure, but I think only line 7 is used.

**Comment by abyzov** [comment]
Yes, adding to two line should work.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745







On Jun 17, 2016, at 5:32 AM, Robert Ernst <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes seems like that. Just to be sure I am doing the right thing, I changed the following lines:

Line 5:

ROOTLIBS = -L$(ROOTSYS)/lib/root -lCore -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -pthread -lm -ldl -rdynamic


Line 7:

ROOTLIBS = -L$(ROOTSYS)/lib      -lCore -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -pthread -lm -ldl -rdynamic


I just changed them both to be sure, but I think only line 7 is used.

**Comment by rernst** [comment]
Unfortunately I still get the same error after building again from source.

**Comment by abyzov** [comment]
Not sure but could you check that you have

 ${ROOTSYS}/lib

added to LD_LIBRARY_PATH and DYLD_LIBRARY_PATH environmental variables.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745







On Jun 17, 2016, at 11:22 AM, Robert Ernst <notifications@github.com<mailto:notifications@github.com>> wrote:


Unfortunately I still get the same error after building again from source.

**Comment by rernst** [comment]
Sorry for the late reply, I was out of office for three weeks. I can confirm that this is correctly setup (using the thisroot.sh script).

```
$ source /hpc/cog_bioinf/data/PROJECTS/test_CNV_callers/tools/root-6.06.04/bin/thisroot.sh
$ echo ${ROOTSYS}/lib
/hpc/cog_bioinf/data/PROJECTS/test_CNV_callers/tools/root-6.06.04/lib
$ echo $LD_LIBRARY_PATH
/hpc/cog_bioinf/data/PROJECTS/test_CNV_callers/tools/root-6.06.04/lib:/hpc/local/CentOS7/common/lang/Java/1.7.0_79/lib:/hpc/local/CentOS7/common/lang/R/3.2.2/lib64/R/include:/hpc/local/CentOS7/cog/lib:/opt/sge/lib/linux-x64:/opt/sge/lib/lx-amd64
$ echo $DYLD_LIBRARY_PATH 
/hpc/cog_bioinf/data/PROJECTS/test_CNV_callers/tools/root-6.06.04/lib
```

**Comment by abyzov** [comment]
Hi,
does it crash if you execute some other commend, for example,

./cnvnator -root aaa.root -view 1000
>chr1:1-1000000
Error in <TFile::TFile>: file aaa.root does not exist
Can't open file 'aaa.root'.
Error in <TFile::TFile>: file aaa.root does not exist
Can't open file 'aaa.root'.
Error in <TFile::TFile>: file aaa.root does not exist
Can't open file 'aaa.root'.
Error in <TFile::TFile>: file aaa.root does not exist
Can't open file 'aaa.root'.
Error in <TFile::TFile>: file aaa.root does not exist
Can't open file 'aaa.root'.
For file 'aaa.root'.
Can't find RD histogram for 'chr1'.
>


Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745







On Jul 12, 2016, at 9:14 AM, Robert Ernst <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry for the late reply, I was out of office for three weeks. I can confirm that this is correctly setup (using the thisroot.sh script).

$ source /hpc/cog_bioinf/data/PROJECTS/test_CNV_callers/tools/root-6.06.04/bin/thisroot.sh
$ echo ${ROOTSYS}/lib
/hpc/cog_bioinf/data/PROJECTS/test_CNV_callers/tools/root-6.06.04/lib
$ echo $LD_LIBRARY_PATH
/hpc/cog_bioinf/data/PROJECTS/test_CNV_callers/tools/root-6.06.04/lib:/hpc/local/CentOS7/common/lang/Java/1.7.0_79/lib:/hpc/local/CentOS7/common/lang/R/3.2.2/lib64/R/include:/hpc/local/CentOS7/cog/lib:/opt/sge/lib/linux-x64:/opt/sge/lib/lx-amd64
$ echo $DYLD_LIBRARY_PATH
/hpc/cog_bioinf/data/PROJECTS/test_CNV_callers/tools/root-6.06.04/lib

**Comment by rernst** [comment]
No it does not crash, I just get the same error as you posted above:

```bash
./cnvnator -root aaa.root -view 1000
>chr1:1-1000000
Error in <TFile::TFile>: file aaa.root does not exist
Can't open file 'aaa.root'.
Error in <TFile::TFile>: file aaa.root does not exist
Can't open file 'aaa.root'.
Error in <TFile::TFile>: file aaa.root does not exist
Can't open file 'aaa.root'.
Error in <TFile::TFile>: file aaa.root does not exist
Can't open file 'aaa.root'.
Error in <TFile::TFile>: file aaa.root does not exist
Can't open file 'aaa.root'.
For file 'aaa.root'.
Can't find RD histogram for 'chr1'.
```

**Comment by abyzov** [comment]
Then it seems to me that the problem could be related to how samtools library was compiled and linked to CNVnator.
Could you check linked libraries to your cnvnator executable.
‘ldd' command should be able to show this.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by rernst** [comment]
I followed the readme for samtools and cnvnator compilation.

This is the output of the ldd command, not sure what I should look for:
```bash
ldd cnvnator
        linux-vdso.so.1 =>  (0x00007ffe5e7e7000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f6919ec1000)
        libCore.so => /hpc/cog_bioinf/data/PROJECTS/Hartwig_CNV_validaties/tools/root-6.06.04/lib/libCore.so (0x00007f69198f1000)
        libRIO.so => /hpc/cog_bioinf/data/PROJECTS/Hartwig_CNV_validaties/tools/root-6.06.04/lib/libRIO.so (0x00007f691947d000)
        libNet.so => /hpc/cog_bioinf/data/PROJECTS/Hartwig_CNV_validaties/tools/root-6.06.04/lib/libNet.so (0x00007f69191bb000)
        libHist.so => /hpc/cog_bioinf/data/PROJECTS/Hartwig_CNV_validaties/tools/root-6.06.04/lib/libHist.so (0x00007f6918c54000)
        libGraf.so => /hpc/cog_bioinf/data/PROJECTS/Hartwig_CNV_validaties/tools/root-6.06.04/lib/libGraf.so (0x00007f6918923000)
        libGraf3d.so => /hpc/cog_bioinf/data/PROJECTS/Hartwig_CNV_validaties/tools/root-6.06.04/lib/libGraf3d.so (0x00007f691868e000)
        libGpad.so => /hpc/cog_bioinf/data/PROJECTS/Hartwig_CNV_validaties/tools/root-6.06.04/lib/libGpad.so (0x00007f69183f5000)
        libTree.so => /hpc/cog_bioinf/data/PROJECTS/Hartwig_CNV_validaties/tools/root-6.06.04/lib/libTree.so (0x00007f69180c4000)
        libRint.so => /hpc/cog_bioinf/data/PROJECTS/Hartwig_CNV_validaties/tools/root-6.06.04/lib/libRint.so (0x00007f6917ea0000)
        libPostscript.so => /hpc/cog_bioinf/data/PROJECTS/Hartwig_CNV_validaties/tools/root-6.06.04/lib/libPostscript.so (0x00007f6917c40000)
        libMatrix.so => /hpc/cog_bioinf/data/PROJECTS/Hartwig_CNV_validaties/tools/root-6.06.04/lib/libMatrix.so (0x00007f69178ff000)
        libPhysics.so => /hpc/cog_bioinf/data/PROJECTS/Hartwig_CNV_validaties/tools/root-6.06.04/lib/libPhysics.so (0x00007f69176ba000)
        libMathCore.so => /hpc/cog_bioinf/data/PROJECTS/Hartwig_CNV_validaties/tools/root-6.06.04/lib/libMathCore.so (0x00007f6917338000)
        libThread.so => /hpc/cog_bioinf/data/PROJECTS/Hartwig_CNV_validaties/tools/root-6.06.04/lib/libThread.so (0x00007f691710e000)
        libMultiProc.so => /hpc/cog_bioinf/data/PROJECTS/Hartwig_CNV_validaties/tools/root-6.06.04/lib/libMultiProc.so (0x00007f6916f00000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f6916cfc000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f69169f4000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f69166f2000)
        libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f69164da000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f69162c4000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f69160a8000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f6915ce6000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f6915a85000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f6915860000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f691a0f0000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007f69155f2000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f691520b000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f6914fd4000)
        libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f6914d2d000)
        libTreePlayer.so => /hpc/cog_bioinf/data/PROJECTS/Hartwig_CNV_validaties/tools/root-6.06.04/lib/libTreePlayer.so (0x00007f6914a18000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f69147cc000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f69144e6000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f69142e2000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f69140b0000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00007f6913eac000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f6913c9d000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f6913a99000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f691387e000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f6913659000)
```

**Comment by abyzov** [comment]
Hi,
sorry don’t know the reason for crash. Reading the following link https://root.cern.ch/phpBB3/viewtopic.php?t=20329 look like this could be a problem with compiler.
Perhaps, it is best to ask for help at ROOT forum.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by zhaoww7** [comment]
I meet the same problem though this is 2019 today.I try to install root in my deepin(a distribution linux based on debian)
![root_problem](https://user-images.githubusercontent.com/45501852/57582296-66156b00-74f5-11e9-945c-952e755cd240.png)
I search for many talking, some of them are talking about macos,but they are not solve this problem utill someone tell to "sudo apt-get install g++''.Well it works!
If you have not success,why not try this?
