### ISSUE TITLE
Bin size for 20x depth of coverage

### ISSUE THREAD

**Issue by zainabae** [abyzovlab/CNVnator#275]
Hello, I’m little bit confused about selecting the appropriate bin size. Actually I am not looking for specific CNV region, I want to get as much as possible CNV regions among my samples. 

I’m working on CamDro3 reference genome, 
My samples have approximately 20x depth of coverage and the reads lengths 15-150. 

The table here does not include bin size for 20X. 

![image](https://user-images.githubusercontent.com/42394514/201715091-8fe25086-bf8b-42da-837e-509c7cf36614.png)

And I found this page explaining the paper with different values other than those mentioned in the table (it is mentioned that with 20 and 30x the 100 bin size is appropriate)

However bin size of 100 is shorter than some of my reads lengths since I have reads (15-150)

http://avrilomics.blogspot.com/2013/01/using-cnvnator-to-find-copy-number.html?m=1

![image](https://user-images.githubusercontent.com/42394514/201715455-a472d649-5ecf-44d3-b08a-a8df4b9db0f0.jpeg)

So anyone can help me in selecting the appropriate bin size for my samples?

**Comment by abyzov** [comment]
Hi,
choice of bin size also depends on the variance in the data.
For you coverage and read length I’d suggest to start from 500 bp bins

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978

**Comment by zainabae** [comment]
@abyzov thank you 👍🏻
