### ISSUE TITLE
Can't load index file for cram file

### ISSUE THREAD

**Issue by ChristinaXu2017** [abyzovlab/CNVnator#276]
According to GitHub issues #33 and #34.  the latest CNVnator can read CRAM files.  Yes, it can read the CRAM file but not the CRAM index file. I got below error message: 
`Can't load index file for '/path/test.cram'. `

The command line I used is 
```
export REF_PATH=/reference/g/GRCh37_ICGC_standard_v2.fa;
./cnvnator -pe /path/test.cram -qual 40 -over 0.8 -root /path/test.rawresults.root  -f /path/test.rawresults.tsv 
```

The index file is created by samtools and renamed to
- /path/test.cram.crai;  
- /path/test.cram.bai; 
- /path/test.crai; 
- /path/test.bai.  

I doubt the error occurs on AliParser.cpp 
```
  if (loadIndex) {
      index = bam_index_load(fileName.c_str());
      if (!index) cerr<<"Can't load index file for '"<<fileName<<"'."<<endl;
    }
```

**Comment by ChristinaXu2017** [comment]
it can't load cram file, unless Change index file handle from bam_idx_ to hts_idx_t on AliParser.*.

-  AliParser.hh
`hts_idx_t *index; //bam_index_t *index;`

- AliParser.cpp 

```c
if (loadIndex) {
    //index = bam_index_load(fileName.c_str());
    samFile *hts = sam_open(fileName.c_str());
     index = sam_index_load2( hts, fileName.c_str(), NULL);
     ...
```  

The reason is 

- bam_index_load() defined inside  htslib/sam.h, can’t take cram file
- sam_index_load(fp,fn) defined inside htslib/sam.h can process cram file
- htslib/sam.h::sam_index_load(fp,fn) calls sam_index_load2( fp, fn, NULL), so here we use sam_index_load2 to process cram file

**Comment by abyzov** [comment]
Hi,
thanks for the info. Perhaps, it would be better to switch to CNVpytor (https://github.com/abyzovlab/CNVpytor) as it is better maintained.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 7-91
Rochester, MN 55905
www.abyzovlab.org
tel: +1-(507)-538-0978

**Comment by ChristinaXu2017** [comment]
thanks, will try it.
