### ISSUE TITLE
-his step takes too long

### ISSUE THREAD

**Issue by Seanduu** [abyzovlab/CNVnator#278]
Hi, when I run the -his step it takes so long that I can not finish my analysis in time with the command:
# Extract read mapping 
cnvnator -root AHHN.root -tree ../01.bams/AHHN.bam
# Generate histogram
cnvnator -root AHHN.root -his 400 -fasta Ljap_chr_v2.0_primary.fasta

My .fasta file's header is just like Chr7 Chr8 Chr9... same with the .bam files.
And there is neither output file nor error message, the command is just running and running.
What's wrong?

**Comment by Seanduu** [comment]
now the command is done, but still no output and the size of .root is unaltered.

then I ran cnvnator -root AHHN.root -stat 400

the error message is :
Can't find directory 'bin_400' in file 'AHHN.root'.
how can I fix this? Is my result correct?

**Comment by abyzov** [comment]
Hello,
I believe fasta file with genome should be gzipped.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 7-91
Rochester, MN 55905
www.abyzovlab.org
tel: +1-(507)-538-0978

On Apr 4, 2023, at 7:32 AM, Seanduuu ***@***.***> wrote:



now the command is done, but still no output and the size of .root is unaltered.

then I ran cnvnator -root AHHN.root -stat 400

the error message is :
Can't find directory 'bin_400' in file 'AHHN.root'.
how can I fix this? Is my result correct?

**Comment by Seanduu** [comment]
Thank you for replying so quick!
But the situation seems unchanged with the fasta file being gzipped (no output file and error).
And the log is still incomplete:

"Allocating memory ... "
"Done".

I just read some issues that are closed. Do I need to split my fasta file by chromosome or remove the contigs, sattellites from the fasta file? 

cnvnator -root AHHN.root -ls:

RD TREES: Chr7, Chr6, Chr1, Chr3, Chr4, Chr5, Chr2, Chr8, Chr9, Chr10, scaffold_10, scaffold_11, scaffold_12, scaffold_13, scaffold_14, scaffold_15, scaffold_16, scaffold_17, scaffold_18, scaffold_19, scaffold_20, scaffold_21, scaffold_22, scaffold_23, scaffold_24, scaffold_25, scaffold_26, scaffold_27, scaffold_28, scaffold_29, scaffold_30, scaffold_31, scaffold_32, scaffold_33, scaffold_34, scaffold_35, scaffold_36, scaffold_37, scaffold_38, scaffold_39, scaffold_40, scaffold_41, scaffold_42, scaffold_43, scaffold_44, scaffold_45, scaffold_46, scaffold_47, scaffold_48, scaffold_49, scaffold_50, scaffold_51, scaffold_52, scaffold_53, scaffold_54, scaffold_55, scaffold_56, scaffold_57, scaffold_58, scaffold_59, scaffold_60, scaffold_61, scaffold_62, scaffold_63, scaffold_64, scaffold_65, scaffold_66, scaffold_67, scaffold_68, scaffold_69, scaffold_70, scaffold_71, scaffold_72, scaffold_73, scaffold_74, scaffold_75, scaffold_76, scaffold_77, scaffold_78, scaffold_79, scaffold_80, scaffold_81, scaffold_82, scaffold_83, scaffold_84, scaffold_85, scaffold_86, scaffold_87, scaffold_88, scaffold_89, scaffold_90, scaffold_91, scaffold_92, scaffold_93, scaffold_94, scaffold_95, scaffold_96, scaffold_97, scaffold_98, scaffold_99, scaffold_100, scaffold_101, scaffold_102, scaffold_103, scaffold_104, scaffold_105, scaffold_106, scaffold_107, scaffold_108, scaffold_109, scaffold_110, scaffold_111, scaffold_112, scaffold_113, scaffold_114, scaffold_115, scaffold_116, scaffold_117, scaffold_118, scaffold_119, scaffold_120, scaffold_121, scaffold_122, scaffold_123, scaffold_124, scaffold_125, scaffold_126, scaffold_127, scaffold_128, scaffold_129, scaffold_130, scaffold_131, scaffold_132, scaffold_133, scaffold_134, scaffold_135, scaffold_136, scaffold_137, scaffold_138, scaffold_139, scaffold_140, scaffold_141, scaffold_142, scaffold_143, scaffold_144, scaffold_145, scaffold_146, scaffold_147, scaffold_148, scaffold_149, scaffold_150, scaffold_151, scaffold_152, scaffold_153, scaffold_154, scaffold_155, scaffold_156, scaffold_157, scaffold_158, scaffold_159, scaffold_160, scaffold_161, scaffold_162, scaffold_163, scaffold_164, scaffold_165, scaffold_166, scaffold_167, scaffold_168, scaffold_169, scaffold_170, scaffold_171, scaffold_172, scaffold_173, scaffold_174, scaffold_175, scaffold_176, scaffold_177, scaffold_178, scaffold_179, scaffold_180, scaffold_181, scaffold_182, scaffold_183, scaffold_184, scaffold_185, scaffold_186, scaffold_187, scaffold_188, scaffold_189, scaffold_190, scaffold_191, scaffold_192, scaffold_193, scaffold_194, scaffold_195, scaffold_196, scaffold_197, scaffold_198, scaffold_199, scaffold_200, scaffold_201, scaffold_202, scaffold_203, scaffold_204, scaffold_205, scaffold_206, scaffold_207, scaffold_208, scaffold_209, scaffold_210, scaffold_211, scaffold_212, scaffold_213, scaffold_214, scaffold_215, scaffold_216, scaffold_217, scaffold_218, scaffold_219, scaffold_220, scaffold_221, scaffold_222, scaffold_223, scaffold_224, scaffold_225, scaffold_226, scaffold_227, scaffold_228, scaffold_229, scaffold_230, scaffold_231, scaffold_232, scaffold_233, scaffold_234, scaffold_235, scaffold_236, scaffold_237, scaffold_238, scaffold_239, scaffold_240, scaffold_241, scaffold_242, scaffold_243, scaffold_244, scaffold_245, scaffold_246, scaffold_247, scaffold_248, scaffold_249, scaffold_250, scaffold_251, scaffold_252, scaffold_253, scaffold_254, scaffold_255, scaffold_256, scaffold_257, scaffold_258, scaffold_259, scaffold_260, scaffold_261, scaffold_262, scaffold_263, scaffold_264, scaffold_265, scaffold_266, scaffold_267, scaffold_268, scaffold_269, scaffold_270, scaffold_271, scaffold_272, scaffold_273, scaffold_274, scaffold_275, scaffold_276, scaffold_277, scaffold_278, scaffold_279, scaffold_280, scaffold_281, scaffold_282, scaffold_283, scaffold_284, scaffold_285, scaffold_286, scaffold_287, scaffold_288, scaffold_289, scaffold_290, scaffold_291, scaffold_292, scaffold_293, scaffold_294, scaffold_295, scaffold_296, scaffold_297, scaffold_298, scaffold_299, scaffold_300, scaffold_301, scaffold_302, scaffold_303, scaffold_304, scaffold_305, scaffold_306, scaffold_307, scaffold_308, scaffold_309, scaffold_310, scaffold_311, scaffold_312, scaffold_313, scaffold_314, scaffold_315, scaffold_316, scaffold_317, scaffold_318, scaffold_319, scaffold_320, scaffold_321, scaffold_322, scaffold_323, scaffold_324, scaffold_325, scaffold_326, scaffold_327, scaffold_328, scaffold_329, scaffold_330, scaffold_331, scaffold_332, scaffold_333, scaffold_334, scaffold_335, scaffold_336, scaffold_337, scaffold_338, scaffold_339, scaffold_340, scaffold_341, scaffold_342, scaffold_343, scaffold_344, scaffold_345, scaffold_346, scaffold_347, scaffold_348, scaffold_349, scaffold_350, scaffold_351, scaffold_352, scaffold_353, scaffold_354, scaffold_355, scaffold_356, scaffold_357, scaffold_358, scaffold_359, scaffold_360, scaffold_361, scaffold_362, scaffold_363, scaffold_364, scaffold_365, scaffold_366, scaffold_367, scaffold_368, scaffold_369, scaffold_370, scaffold_371, scaffold_372, scaffold_373, scaffold_374, scaffold_375, scaffold_376, scaffold_377, scaffold_378, scaffold_379, scaffold_380, scaffold_381, scaffold_382, scaffold_383, scaffold_384, scaffold_385, scaffold_386, scaffold_387, scaffold_388, scaffold_389, scaffold_390, scaffold_391, scaffold_392, scaffold_393, scaffold_394, scaffold_395, scaffold_396, scaffold_397, scaffold_398, scaffold_399, scaffold_400, scaffold_401, scaffold_402, scaffold_403, scaffold_404, scaffold_405, scaffold_406, scaffold_407, scaffold_408, scaffold_409, scaffold_410, scaffold_411, scaffold_412, scaffold_413, scaffold_414, scaffold_415, scaffold_416, scaffold_417, scaffold_418, scaffold_419, scaffold_420, scaffold_421, scaffold_422, scaffold_423, scaffold_424, scaffold_425, scaffold_426, scaffold_427, scaffold_428, scaffold_429, scaffold_430, scaffold_431, scaffold_432, scaffold_433, scaffold_434, scaffold_435, scaffold_436, scaffold_437, scaffold_438, scaffold_439, scaffold_440, scaffold_441, scaffold_442, scaffold_443, scaffold_444, scaffold_445, scaffold_446, scaffold_447, scaffold_448, scaffold_449, scaffold_450, scaffold_451, scaffold_452, scaffold_453, scaffold_454, scaffold_455, scaffold_456, scaffold_457, scaffold_458, scaffold_459, scaffold_460, scaffold_461, scaffold_462, scaffold_463, scaffold_464, scaffold_465, scaffold_466, scaffold_467, scaffold_468, scaffold_469, scaffold_470, scaffold_471, scaffold_472, scaffold_473, scaffold_474, scaffold_475, scaffold_476, scaffold_477, scaffold_478, scaffold_479, scaffold_480, scaffold_481, scaffold_482, scaffold_483, scaffold_484, scaffold_485, scaffold_486, scaffold_487, scaffold_488, scaffold_489, scaffold_490, scaffold_491, scaffold_492, scaffold_493, scaffold_494, scaffold_495, scaffold_496, scaffold_497, scaffold_498, scaffold_499, scaffold_500, scaffold_501, scaffold_502, scaffold_503, scaffold_504, scaffold_505, scaffold_506, scaffold_507, scaffold_508, scaffold_509, scaffold_510, scaffold_511, scaffold_512, scaffold_513, scaffold_514, scaffold_515, scaffold_516, scaffold_517, scaffold_518, scaffold_519, scaffold_520, scaffold_521, scaffold_522, scaffold_523, scaffold_524, scaffold_525, scaffold_526, scaffold_527, scaffold_528, scaffold_529, scaffold_530, scaffold_531, scaffold_532, scaffold_533, scaffold_534, scaffold_535, scaffold_536, scaffold_537, scaffold_538, scaffold_539, scaffold_540, scaffold_541, scaffold_542, scaffold_543, scaffold_544, scaffold_545, scaffold_546, scaffold_547, scaffold_548, scaffold_549, scaffold_550, scaffold_551, scaffold_552, scaffold_553, scaffold_554, scaffold_555, scaffold_556, scaffold_557, scaffold_558, scaffold_559, scaffold_560, scaffold_561, scaffold_562, scaffold_563, scaffold_564, scaffold_565, scaffold_566, scaffold_567, scaffold_568, scaffold_569, scaffold_570, scaffold_571, scaffold_572, scaffold_573, scaffold_574, scaffold_575, scaffold_576, scaffold_577, scaffold_578, scaffold_579, scaffold_580, scaffold_581, scaffold_582, scaffold_583, scaffold_584, scaffold_585, scaffold_586, scaffold_587, scaffold_588, scaffold_589, scaffold_590, scaffold_591, scaffold_592, scaffold_593, scaffold_594, scaffold_595, scaffold_596, scaffold_597, scaffold_598, scaffold_599, scaffold_600, scaffold_601, scaffold_602, scaffold_603, scaffold_604, scaffold_605, scaffold_606, scaffold_607, scaffold_608, scaffold_609, scaffold_610, scaffold_611, scaffold_612, scaffold_613, scaffold_614, scaffold_615, scaffold_616, scaffold_617, scaffold_618, scaffold_619, scaffold_620, scaffold_621, scaffold_622, scaffold_623, scaffold_624, scaffold_625, scaffold_626, scaffold_627, scaffold_628, scaffold_629, scaffold_630, scaffold_631, scaffold_632, scaffold_633, scaffold_634, scaffold_635, scaffold_636, scaffold_637, scaffold_638, scaffold_639, scaffold_640, scaffold_641, scaffold_642, scaffold_643, scaffold_644, scaffold_645, scaffold_646, scaffold_647, scaffold_648, scaffold_649, scaffold_650, scaffold_651, scaffold_652, scaffold_653, scaffold_654, scaffold_655, scaffold_656, scaffold_657, scaffold_658, scaffold_659, scaffold_660, scaffold_661, scaffold_662, scaffold_663, scaffold_664, scaffold_665, scaffold_666, scaffold_667, scaffold_668, scaffold_669, scaffold_670, scaffold_671, scaffold_672, scaffold_673, scaffold_674, scaffold_675, scaffold_676, scaffold_677, scaffold_678, scaffold_679, scaffold_680, scaffold_681, scaffold_682, scaffold_683, scaffold_684, scaffold_685, scaffold_686, scaffold_687, scaffold_688, scaffold_689, scaffold_690, scaffold_691, scaffold_692, scaffold_693, scaffold_694, scaffold_695, scaffold_696, scaffold_697, scaffold_698, scaffold_699, scaffold_700, scaffold_701, scaffold_702, scaffold_703, scaffold_704, scaffold_705, scaffold_706, scaffold_707, scaffold_708, scaffold_709, scaffold_710, scaffold_711, scaffold_712, scaffold_713, scaffold_714, scaffold_715, scaffold_716, scaffold_717, scaffold_718, scaffold_719, scaffold_720, scaffold_721, scaffold_722, scaffold_723, scaffold_724, scaffold_725, scaffold_726, scaffold_727, scaffold_728, scaffold_729, scaffold_730, scaffold_731, scaffold_732, scaffold_733, scaffold_734, scaffold_735, scaffold_736, scaffold_737, scaffold_738, scaffold_739, scaffold_740, scaffold_741, scaffold_742, scaffold_743, scaffold_744, scaffold_745, scaffold_746, scaffold_747, scaffold_748, scaffold_749, scaffold_750, scaffold_751, scaffold_752, scaffold_753, scaffold_754, scaffold_755, scaffold_756, scaffold_757, scaffold_758, scaffold_759, scaffold_760, scaffold_761, scaffold_762, scaffold_763, scaffold_764, scaffold_765, scaffold_766, scaffold_767, scaffold_768, scaffold_769, scaffold_770, scaffold_771, scaffold_772, scaffold_773, scaffold_774, scaffold_775, scaffold_776, scaffold_777, scaffold_778, scaffold_779, scaffold_780, scaffold_781, scaffold_782, scaffold_783, scaffold_784, scaffold_785, scaffold_786, scaffold_787, scaffold_788, scaffold_789, scaffold_790, scaffold_791, scaffold_792, scaffold_793, scaffold_794, scaffold_795, scaffold_796, scaffold_797, scaffold_798, scaffold_799, scaffold_800, scaffold_801, scaffold_802, scaffold_803, scaffold_804, scaffold_805, scaffold_806, scaffold_807, scaffold_808, scaffold_809, scaffold_810, scaffold_811, scaffold_812, scaffold_813, scaffold_814, scaffold_815, scaffold_816, scaffold_817, scaffold_818, scaffold_819, scaffold_820, scaffold_821, scaffold_822, scaffold_823, scaffold_824, scaffold_825, scaffold_826, scaffold_827, scaffold_828, scaffold_829, scaffold_830, scaffold_831, scaffold_832, scaffold_833, scaffold_834, scaffold_835, scaffold_836, scaffold_837, scaffold_838, scaffold_839, scaffold_840, scaffold_841, scaffold_842, scaffold_843, scaffold_844, scaffold_845, scaffold_846, scaffold_847, scaffold_848, scaffold_849, scaffold_850, scaffold_851, scaffold_852, scaffold_853, scaffold_854, scaffold_855, scaffold_856, scaffold_857, scaffold_858, scaffold_859, scaffold_860, scaffold_861, scaffold_862, scaffold_863, scaffold_864, scaffold_865, scaffold_866, scaffold_867, scaffold_868, scaffold_869, scaffold_870, scaffold_871, scaffold_872, scaffold_873, scaffold_874, scaffold_875, scaffold_876, scaffold_877, scaffold_878, scaffold_879, scaffold_880, scaffold_881, scaffold_882, scaffold_883, scaffold_884, scaffold_885, scaffold_886, scaffold_887, scaffold_888, scaffold_889, scaffold_890, scaffold_891, scaffold_892, scaffold_893, scaffold_894, scaffold_895, scaffold_896, scaffold_897, scaffold_898, scaffold_899, scaffold_900, scaffold_901, scaffold_902, scaffold_903, scaffold_904, scaffold_905, scaffold_906, scaffold_907, scaffold_908, scaffold_909, scaffold_910, scaffold_911, scaffold_912, scaffold_913, scaffold_914, scaffold_915, scaffold_916, scaffold_917, scaffold_918, scaffold_919, scaffold_920, scaffold_921, scaffold_922, scaffold_923, scaffold_924, scaffold_925, scaffold_926, scaffold_927, scaffold_928, scaffold_929, scaffold_930, scaffold_931, scaffold_932, scaffold_933, scaffold_934, scaffold_935, scaffold_936, scaffold_937, scaffold_938, scaffold_939, scaffold_940, scaffold_941, scaffold_942, scaffold_943, scaffold_944, scaffold_945, scaffold_946, scaffold_947, scaffold_948, scaffold_949, scaffold_950, scaffold_951, scaffold_952, scaffold_953, scaffold_954, scaffold_955, scaffold_956, scaffold_957, scaffold_958, scaffold_959, scaffold_960, scaffold_961, scaffold_962, scaffold_963, scaffold_964, scaffold_965, scaffold_966, scaffold_967, scaffold_968, scaffold_969, scaffold_970, scaffold_971, scaffold_972, scaffold_973, scaffold_974, scaffold_975, scaffold_976, scaffold_977, scaffold_978, scaffold_979, scaffold_980, scaffold_981, scaffold_982, scaffold_983, scaffold_984, scaffold_985, scaffold_986, scaffold_987, scaffold_988, scaffold_989, scaffold_990, scaffold_991, scaffold_992, scaffold_993, scaffold_994, scaffold_995, scaffold_996, scaffold_997, scaffold_998, scaffold_999, scaffold_1000, scaffold_1001, scaffold_1002, scaffold_1003, scaffold_1004, scaffold_1005, scaffold_1006, scaffold_1007, scaffold_1008, scaffold_1009, scaffold_1010, scaffold_1011, scaffold_1012, scaffold_1013, scaffold_1014, scaffold_1015, scaffold_1016, scaffold_1017, scaffold_1018, scaffold_1019, scaffold_1020, scaffold_1021, scaffold_1022, scaffold_1023, scaffold_1024, scaffold_1025, scaffold_1026, scaffold_1027, scaffold_1028, scaffold_1029, scaffold_1030, scaffold_1031, scaffold_1032, scaffold_1033, scaffold_1034, scaffold_1035, scaffold_1036, scaffold_1037, scaffold_1038, scaffold_1039, scaffold_1040, scaffold_1041, scaffold_1042, scaffold_1043, scaffold_1044, scaffold_1045, scaffold_1046, scaffold_1047, scaffold_1048, scaffold_1049, scaffold_1050, scaffold_1051, scaffold_1052, scaffold_1053, scaffold_1054, scaffold_1055, scaffold_1056, scaffold_1057, scaffold_1058, scaffold_1059, scaffold_1060, scaffold_1061, scaffold_1062, scaffold_1063, scaffold_1064, scaffold_1065, scaffold_1066, scaffold_1067, scaffold_1068, scaffold_1069, scaffold_1070, scaffold_1071, scaffold_1072, scaffold_1073, scaffold_1074, scaffold_1075, scaffold_1076, scaffold_1077, scaffold_1078, scaffold_1079, scaffold_1080, scaffold_1081, scaffold_1082, scaffold_1083, scaffold_1084, scaffold_1085, scaffold_1086, scaffold_1087, scaffold_1088, scaffold_1089, scaffold_1090, scaffold_1091, scaffold_1092, scaffold_1093, scaffold_1094, scaffold_1095, scaffold_1096, scaffold_1097, scaffold_1098, scaffold_1099, scaffold_1100, scaffold_1101, scaffold_1102, scaffold_1103, scaffold_1104, scaffold_1105, scaffold_1106, scaffold_1107, scaffold_1108, scaffold_1109, scaffold_1110, scaffold_1111, scaffold_1112, scaffold_1113, scaffold_1114, scaffold_1115, scaffold_1116, scaffold_1117, scaffold_1118, scaffold_1119, scaffold_1120, scaffold_1121, scaffold_1122, scaffold_1123, scaffold_1124, scaffold_1125, scaffold_1126, scaffold_1127, scaffold_1128, scaffold_1129, scaffold_1130, scaffold_1131, scaffold_1132, scaffold_1133, scaffold_1134, scaffold_1135, scaffold_1136, scaffold_1137, scaffold_1138, scaffold_1139, scaffold_1140, scaffold_1141, scaffold_1142, scaffold_1143, scaffold_1144, scaffold_1145, scaffold_1146, scaffold_1147, scaffold_1148, scaffold_1149, scaffold_1150, scaffold_1151, scaffold_1152, scaffold_1153, scaffold_1154, scaffold_1155, scaffold_1156, scaffold_1157, scaffold_1158, scaffold_1159, scaffold_1160, scaffold_1161, scaffold_1162, scaffold_1163, scaffold_1164, scaffold_1165, scaffold_1166, scaffold_1167, scaffold_1168, scaffold_1169, scaffold_1170, scaffold_1171, scaffold_1172, scaffold_1173, scaffold_1174, scaffold_1175, scaffold_1176, scaffold_1177, scaffold_1178, scaffold_1179, scaffold_1180, scaffold_1181, scaffold_1182, scaffold_1183, scaffold_1184, scaffold_1185, scaffold_1186, scaffold_1187, scaffold_1188, scaffold_1189, scaffold_1190, scaffold_1191, scaffold_1192, scaffold_1193, scaffold_1194, scaffold_1195, scaffold_1196, scaffold_1197, scaffold_1198, scaffold_1199, scaffold_1200, scaffold_1201, scaffold_1202, scaffold_1203, scaffold_1204, scaffold_1205, scaffold_1206, scaffold_1207, scaffold_1208, scaffold_1209, scaffold_1210, scaffold_1211, scaffold_1212, scaffold_1213, scaffold_1214, scaffold_1215, scaffold_1216, scaffold_1217, scaffold_1218, scaffold_1219, scaffold_1220, scaffold_1221, scaffold_1222, scaffold_1223, scaffold_1224, scaffold_1225, scaffold_1226, scaffold_1227, scaffold_1228, scaffold_1229, scaffold_1230, scaffold_1231, scaffold_1232, scaffold_1233, scaffold_1234, scaffold_1235, scaffold_1236, scaffold_1237, scaffold_1238, scaffold_1239, scaffold_1240, scaffold_1241, scaffold_1242, scaffold_1243, scaffold_1244, scaffold_1245, scaffold_1246, scaffold_1247, scaffold_1248, scaffold_1249, scaffold_1250, scaffold_1251, scaffold_1252, scaffold_1253, scaffold_1254, scaffold_1255, scaffold_1256, scaffold_1257, scaffold_1258, scaffold_1259, scaffold_1260, scaffold_1261, scaffold_1262, scaffold_1263, scaffold_1264, scaffold_1265, scaffold_1266, scaffold_1267, scaffold_1268, scaffold_1269, scaffold_1270, scaffold_1271, scaffold_1272, scaffold_1273, scaffold_1274, scaffold_1275, scaffold_1276, scaffold_1277, scaffold_1278, scaffold_1279, scaffold_1280, scaffold_1281, scaffold_1282, scaffold_1283, scaffold_1284, scaffold_1285, scaffold_1286, scaffold_1287, scaffold_1288, scaffold_1289, scaffold_1290, scaffold_1291, scaffold_1292, scaffold_1293, scaffold_1294, scaffold_1295, scaffold_1296, scaffold_1297, scaffold_1298, scaffold_1299, scaffold_1300, scaffold_1301, scaffold_1302, scaffold_1303, scaffold_1304, scaffold_1305, scaffold_1306, scaffold_1307, scaffold_1308, scaffold_1309, scaffold_1310, scaffold_1311, scaffold_1312, scaffold_1313, scaffold_1314, scaffold_1315, scaffold_1316, scaffold_1317, scaffold_1318, scaffold_1319, scaffold_1320, scaffold_1321, scaffold_1322, scaffold_1323, scaffold_1324, scaffold_1325, scaffold_1326, scaffold_1327, scaffold_1328, scaffold_1329, scaffold_1330, scaffold_1331, scaffold_1332, scaffold_1333, scaffold_1334, scaffold_1335, scaffold_1336, scaffold_1337, scaffold_1338, scaffold_1339, scaffold_1340, scaffold_1341, scaffold_1342, scaffold_1343, scaffold_1344, scaffold_1345, scaffold_1346, scaffold_1347, scaffold_1348, scaffold_1349, scaffold_1350, scaffold_1351, scaffold_1352, scaffold_1353, scaffold_1354, scaffold_1355, scaffold_1356, scaffold_1357, scaffold_1358, scaffold_1359, scaffold_1360, scaffold_1361, scaffold_1362, scaffold_1363, scaffold_1364, scaffold_1365, scaffold_1366, scaffold_1367, scaffold_1368, scaffold_1369, scaffold_1370, scaffold_1371, scaffold_1372, scaffold_1373, scaffold_1374, scaffold_1375, scaffold_1376, scaffold_1377, scaffold_1378, scaffold_1379, scaffold_1380, scaffold_1381, scaffold_1382, scaffold_1383, scaffold_1384, scaffold_1385, scaffold_1386, scaffold_1387, scaffold_1388, scaffold_1389, scaffold_1390, scaffold_1391, scaffold_1392, scaffold_1393, scaffold_1394, scaffold_1395, scaffold_1396, scaffold_1397, scaffold_1398, scaffold_1399, scaffold_1400, scaffold_1401, scaffold_1402, scaffold_1403, scaffold_1404, scaffold_1405, scaffold_1406, scaffold_1407, scaffold_1408, scaffold_1409, scaffold_1410, scaffold_1411, scaffold_1412, scaffold_1413, scaffold_1414, scaffold_1415, scaffold_1416, scaffold_1417, scaffold_1418, scaffold_1419, scaffold_1420, scaffold_1421, scaffold_1422, scaffold_1423, scaffold_1424, scaffold_1425, scaffold_1426, scaffold_1427, scaffold_1428, scaffold_1429, scaffold_1430, scaffold_1431, scaffold_1432, scaffold_1433, scaffold_1434, scaffold_1435, scaffold_1436, scaffold_1437, scaffold_1438, scaffold_1439, scaffold_1440, scaffold_1441, scaffold_1442

**Comment by abyzov** [comment]
He,
yes, please tray that. Overall, we recommend to switch to CNVpytor as, unlike CNVnator, it is being maintained and developed.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 7-91
Rochester, MN 55905
www.abyzovlab.org
tel: +1-(507)-538-0978

**Comment by Seanduu** [comment]
I will try.
Thank you for the support of all.
