### ISSUE TITLE
Could NOT find X11 (missing: Xpm Xft)

### ISSUE THREAD

**Issue by prabirbioinfo** [abyzovlab/CNVnator#288]
cmake ..
-- Building ROOT version 6.35.01
-- Found GCC. Major version 11, minor version 2
-- ROOT default compression algorithm: zlib
-- Checking internet connectivity
-- Checking internet connectivity - found
-- Looking for ZLib
-- Looking for Freetype
-- Looking for PCRE
-- Looking for LZMA
-- Looking for ZSTD
-- Looking for LZ4
-- Looking for X11
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find X11 (missing: Xpm Xft)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindX11.cmake:457 (find_package_handle_standard_args)
  cmake/modules/SearchInstalledSoftware.cmake:80 (_find_package)
  cmake/modules/SearchInstalledSoftware.cmake:421 (find_package)
  CMakeLists.txt:272 (include)

-- Configuring incomplete, errors occurred!

after installing xpm,xft same problem

**Comment by abyzov** [comment]
Hello,
thank you for interest to CNVnator.
We are not really maintaining the tool anymore and recommend everyone to switch to CNVpytor (https://github.com/abyzovlab/CNVpytor).

Alexej Abyzov, Ph.D., Consultant
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 7-91
Rochester, MN 55905
www.abyzovlab.org
<http://www.abyzovlab.org>tel: +1-(507)-538-0978

**Comment by prabirbioinfo** [comment]
Could you please take a look at the GitHub issue regarding the use of
CNVpytor.
issue #249 persistent issue after indexing BAM, and ref...


thank you
