### ISSUE TITLE
ERROR: cnvnator --his

### ISSUE THREAD

**Issue by tudui123** [abyzovlab/CNVnator#29]
Hello,

When I try to generate a histogram ($./cnvnator -root out.root -his 100) I get the following message, for all contigs:

Allocating memory ...
Can't determine length for 'chr17'.
No reference genome specified.
Done.
Calculating histograms with bin size of 100 for 'chr17' ..

my code:
1)./cnvnator -root NA12878-17.root -chrom chr17 -tree NA12878.chrom17.SLX.maq.SRP000032.2009_07.bam 
2)./cnvnator -genome ./hg19/chr17.fa -root NA12878-17.root -chrom chr17 -his 100

I'm not sure what the problem is. My input is .bam files. Your help would be appreciated!

Can I use the single chromosome as my .bam file? If I want to detect the single chromosome, what should i do? Could you please give me some advice? 

Thanks,
Madeline

**Comment by tudui123** [comment]
Hi, 
  Can I use the single chromsome as my .bam file? If I want to detect the single chromsome, what should i  do? Could you please give me some advice? 
Thank you!!!

**Comment by abyzov** [comment]
Hi,
did the step with -tree command complete? What was the output?
Looks like not info about chr17 was saved into .root file.


Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by abyzov** [comment]
Hi,
yes sure. You are doing it correct.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
