### ISSUE TITLE
Clarification on evalue1

### ISSUE THREAD

**Issue by jmonlong** [abyzovlab/CNVnator#32]
Hi, 

I'm a bit confused about the range of the e-value1 I'm getting. For the calls, I was expecting evalues below 1 and many below e.g. 0.05. However I see a lot of calls (~20%) with e-value1>100 and q0<.5. 

Is this normal ? 

I'm asking because I want to remove calls with low confidence and thought I would do something like:  q0<.5 and e-value1<.01. But then I see all these calls with {evalue1 > 100, q0<.5} so I'm wondering if I should I really remove all these calls ?

Thanks in advance,

Jean

**Comment by abyzov** [comment]
Hi,
by default CNVantor reports calls that are with <0.05 either for e-val1 or e-val2.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by jmonlong** [comment]
Thanks, I had missed this. Now it makes sense with what I get and I'll also play with eval1 and eval2 jointly to rank per significance.

Jean
