### ISSUE TITLE
CNVnator reads in CRAM

### ISSUE THREAD

**Issue by jeldred** [abyzovlab/CNVnator#33]
Is CNVnator able to use CRAM files as input?  In our local testing it does not seem to have that capability.  Is this a feature you might consider adding?
thanks
Jim Eldred
McDonnell Genome Institute

**Comment by abyzov** [comment]
Hi Jim,
yes we should definitely add it. Do you know whether CRAM has C/C++ API?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by indraniel** [comment]
I think this cheap fix to `AliParser.cpp` and linking against `samtools` and `htslib` version 1.3.1 will enable CNVnator to also work on CRAM files:

```
$ git diff -- AliParser.cpp
diff --git a/AliParser.cpp b/AliParser.cpp
index 47a38ed..bd20ed5 100644
--- a/AliParser.cpp
+++ b/AliParser.cpp
@@ -16,7 +16,8 @@ AliParser::AliParser(string fileName,bool loadIndex) : sam(false),
   int len = fileName.length();
   if (len == 0) {
     stdin = true;
-  } else if (fileName.substr(len - 3,3) == "bam") {
+  } else if (fileName.substr(len - 3,3) == "bam" ||
+             fileName.substr(len - 4,4) == "cram") {
     //cout<<"Assuming BAM file for "<<fileName<<endl;
     file = samopen(fileName.c_str(),"rb",NULL);
     if (!file) cerr<<"Can't open file '"<<fileName<<"'."<<endl;
```

I'm in the process of testing this out.  If things go successfully, I'll make a github pull request for the change in the next few days.

Please let me know if anyone thinks there are better ways to approach this problem.

**Comment by abyzov** [comment]
Sounds great!

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by indraniel** [comment]
My current tests using CNVnator on CRAM files seems to work with this change.   Additionally, I've incremented the CNVnator version to 0.3.3 to account for this new CRAM support feature.  Feel free to let me know if any further modifications are needed before merging in this new code update.

**Comment by MinocheAE** [comment]
Hi, thanks for creating and supporting such a robust tool! 

A note on the cram support. As our HPC environment does not have internet access for worker nodes, it would require to pass the reference flag with the fasta reference for samtools. For now I will just convert cram to bam prior, which is fast and simple, too.
