### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by pydupont** [abyzovlab/CNVnator#38]
Hello,

I compiled and installed Root (v6.06.06) without problem. I set the ROOTSYS variable to the appropriate path. I downloaded the last version of CNVNator (v0.3.3) via git. When I try to compile it, I have a list of errors that I can't solve.
They all look like this:

HisMaker.cpp:(.text+0x4300): undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

Could you help me, please?

I am using g++ 5.3.1

Cheers

**Comment by abyzov** [comment]
Hi,
looks like compilation incompatibility. Some users reported problems with new version of gcc. Could you try gcc 4.x?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by biocyberman** [comment]
FWIW, I can confirm that CNVnator can be compiled successfully on Ubuntu 14.04 with gcc 4.8.4 and Ubuntu 16.04 with gcc 5.4.0

**Comment by abyzov** [comment]
Thanks.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by dangpandora** [comment]
@pydupont  @biocyberman 
Hello, there! I am wondering how did you solve the problem?  i am using g++4.8.4 on ubuntu 14.04. 
i can run root using ./root command, but still many errors occurred just as  @pydupont described
