### ISSUE TITLE
CNVnator with control bam file

### ISSUE THREAD

**Issue by Fatima-Zare** [abyzovlab/CNVnator#39]
Hi, 
Is it possible that run CNVnator with two bam files? one of them is tumor bam file and another is control bam file.

**Comment by abyzov** [comment]
Hi,
it does not run directly. But you can do the following: i) call CNVs; ii) genotype them in your sample; iii) compare genotypes and call differences.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by Fatima-Zare** [comment]
Thank you Alexej.

**Comment by rahulkollipara** [comment]
Hi Alexej,

I have the similar problem like Fatima. I have Tumor and normal samples for CNV calling.

As you suggested, I called CNVs in both tumor and normal samples and genotyped them. Could you give me more details about how to compare the genotypes as the CNV region calls are different between tumor and normal samples.

Thanks,
Rahul


Hi,
it does not run directly. But you can do the following: i) call CNVs; ii) genotype them in your sample; iii) compare genotypes and call differences.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,

Center for Individualized Medicine, Mayo Clinic

Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by abyzov** [comment]
Hi,
for example you can define putative deletion if CNcancer < 1.5 && CNnormal > 1.5 && (CNnormal - CNcancer) > 0.5
Please also see our publication on how we detected mosaic CNVs Abyzov et al., Nature, 2012.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745



On Jun 27, 2017, at 8:00 PM, rahulkollipara <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Alexej,

I have the similar problem like Fatima. I have Tumor and normal samples for CNV calling.

As you suggested, I called CNVs in both tumor and normal samples and genotyped them. Could you give me more details about how to compare the genotypes as the CNV region calls are different between tumor and normal samples.

Thanks,
Rahul

Hi,
it does not run directly. But you can do the following: i) call CNVs; ii) genotype them in your sample; iii) compare genotypes and call differences.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,

Center for Individualized Medicine, Mayo Clinic

Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
