### ISSUE TITLE
contig autocasing breaks non human discovery

### ISSUE THREAD

**Issue by joelmartin** [abyzovlab/CNVnator#4]
ver 0.3 is much easier to run on nonhuman samples, but for some they have contigs named like
Chr01
which cnvnator changes to 'chr01' when trying to load the fasta file for that contig.
an option to disable that would be very useful.  the workarounds are very troublesome.

**Comment by abyzov** [comment]
Hi Martin,
I believe in the example above the issue is related to file naming rather than to chromosome/contig naming. The work around is to create symbolic links for each .fa file, e.g., ln -s Chr1.fa chr1.fa
Anyways, I have just updated the code which should keep original chromosome/contig names and expect corresponding .fa files.

**Comment by milyaskh** [comment]
hi abyzov, am i doing something wrong? how can i fix it..?

$ cnvnator -root out.root -genome /references/human/hg19/hg19.fa -chrom chr1 -his 100 file.bam 
Allocating memory ...
Done.
Calculating histograms with bin size of 100 for 'chr1' ...
Making GC histogram for 'chr1' ...
Can't open file './chr1.fa'.
No chromosome/contig information parsed.
Read sequence is of different length from expectation.
Doing nothing.

**Comment by abyzov** [comment]
Dear Muhammad,
the program can’t find file with chromosome

"Can't open file './chr1.fa’."

Please make sure the files exists or use option –d.

Alexej Abyzov, Ph.D.
Senior Associate Consultant, Mayo Clinic
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research, Mayo Clinic
-----------------------------
Harwick 3-12, 200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by milyaskh** [comment]
thank you abyzov, i noticed that later. :)
Another question, 
how can i convert cnvnator output into Plink format.

**Comment by abyzov** [comment]
We don’t have such feature at the moment. Please open an issue about it in the github.

Alexej Abyzov, Ph.D.
Senior Associate Consultant, Mayo Clinic
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research, Mayo Clinic
-----------------------------
Harwick 3-12, 200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
