### ISSUE TITLE
FitConfig stderr(maybe root problems) in cnvnator

### ISSUE THREAD

**Issue by sunxingqianggenedock** [abyzovlab/CNVnator#40]
I use the cnvnator 0.32 call CNV

here is commands
$genome=ucsc.hg19 
$chrom=chr1 chr2 ... chrX chrY chrM
```
cnvnator -root $rootname.root -chrom $chrom -genome $genome -tree $bam 2>err
cnvnator -root $rootname.root -chrom $chrom -his $bin_size -d /var/data/ 2>>err
cnvnator -root $rootname.root -chrom $chrom -stat $bin_size 2>>err
cnvnator -root $rootname.root -chrom $chrom -partition $bin_size  2>>err
cnvnator -root $rootname.root -chrom $chrom -call $bin_size  >$outputcnv 2>>err
```
the outputcnv’s lines are normal except the following:

> 

Number of free parameters from FitConfig = 3
Number of free parameters from Minimizer = 2
Number of free parameters from FitConfig = 3
Number of free parameters from Minimizer = 2

![qq20160912-0 2x](https://cloud.githubusercontent.com/assets/20854822/18433645/700cc1ea-791b-11e6-91db-a700a087fd4c.png)

**Comment by abyzov** [comment]
Hi,
it looks like there may be some problem with fitting gaussian function to RD distribution. This is done to normalized RD signal. Do you have enough RD coverage per bin? You can use command -eval to find this out.

Also, you don’t need to specify genome if it is described in the header of bam file.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by sunxingqianggenedock** [comment]
Thanks for your reply!
I am not sure whether every bin had  enough RD coverage.
But the command
```
-call $bin_size  >$outputcnv
```
the ouputcnv should not contain following:
```
Number of free parameters from FitConfig = 3
Number of free parameters from Minimizer = 2
Number of free parameters from FitConfig = 3
Number of free parameters from Minimizer = 2
```
if the bin didnot have enough RD coverage,would it concerned about the final result?
Many thanks!

**Comment by abyzov** [comment]
Please use
cnvnator -root file.root -eval bin_size

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745







On Sep 14, 2016, at 12:11 AM, sunxingqianggenedock <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for your reply!
I am not sure whether every bin had enough RD coverage.
But the command

-call $bin_size  >$outputcnv


the ouputcnv should not contain following:

Number of free parameters from FitConfig = 3
Number of free parameters from Minimizer = 2
Number of free parameters from FitConfig = 3
Number of free parameters from Minimizer = 2


if the bin didnot have enough RD coverage,would it concerned about the final result?
Many thanks!

**Comment by sunxingqianggenedock** [comment]
It works , Thanks a lot!
