### ISSUE TITLE
genotype almost all homozygous

### ISSUE THREAD

**Issue by aliciab15** [abyzovlab/CNVnator#41]
Hello,

I am currently trying to distinguish between heterozygous and homozygous deletions for my individuals. 
After filtering CNVs by q0 filter and pval1. I am running genotype on all deletion calls. 
If I understand the paper correctly (notably around figure 2). If a deletion's genotype is around 1.5 then it should be heterozygous and if it is around 0 it should be homozygous. 
I expect from my data a larger amount of heterozygous loci, however well over 95% of my calls genotyped are homozygous. (with almost all genotype values between 0 and 0.02)

Is this something you have encountered before? Or am I interpreting the results wrong? 

Any comments or suggestions would be greatly appreciated.

Thank you for your help,
Alicia

**Comment by abyzov** [comment]
Hi,
from the limited info that you provided it is hard for me to say what could have happen or went wrong.
Please make sure that for the bin size you are using the ratio of average to its sd is around 4-5.
Please also check whether homozygous call may represent gaps in the reference genome.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by aliciab15** [comment]
Hello,

Thank you for your advice. You were correct, I overlapped and discarded all deletions that fall within gaps of the genome. It removed almost half of deletion calls, all of which were homozygous. This explains and solves my problem.

Thank you for your help.
Alicia
