### ISSUE TITLE
No samtools, libbam.h no longer a samtools make target

### ISSUE THREAD

**Issue by datakid** [abyzovlab/CNVnator#44]
1. There's no longer a samtools folder, the installation instructions need updating.
2. Having samtools installed doesn't necessarily help - [libbam.a is no longer a samtools build target](https://github.com/samtools/samtools/issues/531)

**Comment by abyzov** [comment]
Hi,
thanks for the info. I haven’t realized this. We’ll work on fixing it.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by datakid** [comment]
NP

**Comment by biocyberman** [comment]
I simple solution is to make `samtools` and `htslib` git submodules of  `CNVnator`. I did this and update the `Makefile` a bit and could compile successfully. I can make a PR if needed. 

Or a more proper way, as I could read from the net, is to use CMake or CPM https://github.com/iauns/cpm . I haven't tried this so I can't say for sure.

**Comment by abyzov** [comment]
Thanks for the tip. Currently is a busy time. I’m planning to fix this over the holiday season.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
