### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by datakid** [abyzovlab/CNVnator#46]
To compile I had to:
- install cern-root, yeppp have them available
- git clone
- edit the Makefile to point to the samtools source code (not to the samtools I have installed) because access to libbam.a is needed:

```
#SAMDIR = samtools
SAMDIR = /config/source/samtools/samtools-1.3.1
```
- make returned an error

```
/usr/bin/ld: /config/source/samtools/samtools-1.3.1/htslib-1.3.1/libhts.a(plugin.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: note: 'dlclose@@GLIBC_2.2.5' is defined in DSO /lib64/libdl.so.2 so try adding it to the linker command line
/lib64/libdl.so.2: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
```
- so I compiled with: `LIBS=-ldl make` (thanks to [this post](http://askubuntu.com/questions/334884/while-compiling-truecrypt-i-get-undefined-reference-to-symbol-dlcloseglibc)) and it was successful.

**Comment by datakid** [comment]
FWIW, the resulting cnvnator binary didn't work, with error

./cnvnator: error while loading shared libraries: libyeppp.so: cannot open shared object file: No such file or directory
 
ldd cnvnator
        libyeppp.so => not found

I had to redo the process having done:
LD_LIBRARY_PATH = $YEPPPLIBDIR:$LD_LIBRARY_PATH

Now it works.

**Comment by abyzov** [comment]
Thanks!

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by abyzov** [comment]
Please use samtools 1.2 for now.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by Starry912** [comment]
I can't compile,need help.

In file included from cnvnator.cpp:8:0:
HisMaker.hh:11:20: fatal error: TFrame.h: 没有那个文件或目录
 #include <TFrame.h>
                    ^
compilation terminated.

**Comment by dangpandora** [comment]
@Starry912 
the ROOTSYS,  and LD_LIBRARY_PATH are not in correct setting
