### ISSUE TITLE
place v0.3.3 tag on the latest state of the code (master branch)

### ISSUE THREAD

**Issue by indraniel** [abyzovlab/CNVnator#47]
Is it possible to place a "v0.3.3" tag on the latest state of the master branch?  This reflects the version currently mentioned in the [`Makefile`](https://github.com/abyzovlab/CNVnator/blob/master/Makefile).

This can be done as follows:

    git clone https://github.com/abyzovlab/CNVnator
    cd CNVnator
    git tag v0.3.3
    git push origin --tags

Unfortunately, it seems that tags are [not part of a github pull request][1].

Thanks in advance!

[1]: http://stackoverflow.com/questions/12278660/adding-tags-to-a-pull-request

**Comment by abyzov** [comment]
Hi,
do you mean new release?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by indraniel** [comment]
Yes, if it is possible.

**Comment by abyzov** [comment]
Hi,
Taejeong made a new release yesterday.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by indraniel** [comment]
I see the 0.3.3 tag now on the https://github.com/abyzovlab/CNVnator github repo.  Thank you all very much!
