### ISSUE TITLE
Problem running -merge roots

### ISSUE THREAD

**Issue by 11rohit** [abyzovlab/CNVnator#48]
Hello

I am having a problem with running the merge function of CNVnator since I split the runs as I was running it on a non-model genome with >5000 scaffolds. The previous runs were successful with 100 scaffolds each time, and I was not sure if the output of each of these runs were the same as running them at once with the merged root file (the alignment file is the same for each run).

`chroms=$(cat ../input_all); merges=$(ls -1 roots/root_* | tr '\n' ' '); /opt/CNVnator/CNVnator-master/cnvnator -root out_all.root -chrom $chroms -merge $merges`

 
It breaks with the following error -

```
*** Break *** segmentation violation
 
===========================================================
There was a crash.
This is the entire stack trace of all threads:
 ===========================================================
 #0  0x00000033304ac2ce in __libc_waitpid (pid=<optimized out>, stat_loc=0x7ffff77afb10, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:32
 #1  0x000000333044107e in do_system (line=0x2022e78 "/usr/share/root/gdb-backtrace.sh 29566 1>&2") at ../sysdeps/posix/system.c:149
 #2  0x000000352f63cb0a in TUnixSystem::StackTrace (this=0x1c53530) at /usr/src/debug/root-5.28.00h/core/unix/src/TUnixSystem.cxx:2253
 #3  0x000000352f63f283 in TUnixSystem::DispatchSignals (this=0x1c53530, sig=kSigSegmentationViolation) at /usr/src/debug/root-5.28.00h/core/unix/src/TUnixSystem.cxx:1157
 #4  <signal handler called>
 #5  size (this=0x7ffff794e3d8) at /usr/src/debug/gcc-4.6.3-20120306/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:711
 #6  std::string::assign (this=0x7ffff794e3d8, __s=0x7ffff795bc4e "Lvir_1901", __n=9) at /usr/src/debug/gcc-4.6.3-20120306/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.tcc:264
 #7  0x00000000004083a8 in main ()
 ===========================================================
 
 
 The lines below might hint at the cause of the crash.
 If they do not help you then please submit a bug report at
 http://root.cern.ch/bugs. Please post the ENTIRE stack trace
 from above as an attachment in addition to anything else
 that might help us fixing this issue.
 ===========================================================
 #5  size (this=0x7ffff794e3d8) at /usr/src/debug/gcc-4.6.3-20120306/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:711
 #6  std::string::assign (this=0x7ffff794e3d8, __s=0x7ffff795bc4e "Lvir_1901", __n=9) at /usr/src/debug/gcc-4.6.3-20120306/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.tcc:264
 #7  0x00000000004083a8 in main ()
 ===========================================================
```

I have seen the issue of "segmentation violation" before, but increasing the number (N_CHROM_MAX) does not change anything. Can you please let me know what the problem might be?

P.S. The root I am using is quite old (5.28 to be exact), did not update it since CNVnator doesn't mention the version to be used - might this be the reason?

**Comment by biocyberman** [comment]
Just curious, have you tested with merging of only two root files? I guess you are stressing the software and the server with merging many files at once. Merging with two files can help to direct the thought.

**Comment by 11rohit** [comment]
Thanks for the tip. I tried to break up into 1000 scaffolds each time and it worked. But don't I have to get all the chromosomes together into a single file before running the histogram, partitioning and later steps?

**Comment by biocyberman** [comment]
That is above my experience with CNVnator, you can anyway first complete the merging, then run his, stat, and partition.

**Comment by abyzov** [comment]
Hi,
could you avoid using merge? This option is used infrequently and we are planning to remove it in the future.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
