### ISSUE TITLE
Using multi-cores for computation?

### ISSUE THREAD

**Issue by biocyberman** [abyzovlab/CNVnator#49]
I have 16 cores on my server and 192GB of RAM. I am running a test run and see CNVnator only use one core. Is it possible to setup CNVnator so that it uses multiple cores and more RAM to speed up calculation?

I may also try the OpenMP option, but still prefer running on one host first.

**Comment by abyzov** [comment]
Hi,
parallel calculation are implemented for the -partition step only. This is the most time consuming step.
Also, one have to use OpenMP option during compilation.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by biocyberman** [comment]
I see. I now come to the partitioning step and see that cnvnator is using multicore. A following up question though, I don't have any way to specify how many core I want to use. Will it be a problem when I want to avoid resource competition with other programs?

**Comment by abyzov** [comment]
I could. Current implementation utilizes all available cores. If you, however, submit a job trough job schedule you can typically limit number of cores to utilize.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by biocyberman** [comment]
That's true. I can do that.
Thanks for your support.
