### ISSUE TITLE
No chromosome/contig description given.

### ISSUE THREAD

**Issue by peng-gang** [abyzovlab/CNVnator#50]
When I run CNVnator0.3.3, there is alway an error:

./cnvnator -genome ~/ref/Homo_sapiens_assembly19.fasta -root ~/test/out.root -tree ~/data/test.BAM

Parsing file ~/test.BAM ...
No chromosome/contig description given.
No reference genome specified. Aborting parsing.
Writing histograms ... 

I have set the reference file. Do I need to set other chromosome/contig files? 

Thanks!

**Comment by biocyberman** [comment]
A quick look I can see that the value you gave to `-genome` is wrong. It should be only `hg19` in your case. Just type `./cnvnator` and you will see something like this at the end: 

`Valid genomes (-genome option) are: NCBI36, hg18, GRCh37, hg19, mm9`

**Comment by peng-gang** [comment]
I see. Thank you so much.

**Comment by abyzov** [comment]
Hi,
genome information is parsed from bam headers. You don’t need specify it unless header is missing.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by peng-gang** [comment]
I am not sure what kind of information needed from bam headers form CNVnator. The bam file is created by bwa and the duplicates are removed by picard. The first a few lines of header are:

_@HD	VN:1.4	GO:none	SO:coordinate
@SQ	SN:1	LN:249250621	UR:http://www.broadinstitute.org/ftp/pub/seq/references/Homo_sapiens_assembly19.fasta	AS:GRCh37	M5:1b22b98cdeb4a9304cb5d48026a85128	SP:Homo Sapiens
@SQ	SN:2	LN:243199373	UR:http://www.broadinstitute.org/ftp/pub/seq/references/Homo_sapiens_assembly19.fasta	AS:GRCh37	M5:a0d9851da00400dec1098a9255ac712e	SP:Homo Sapiens_

If I didn't specify genome, there is an error message:

_No chromosome/contig description given.
No reference genome specified. Aborting parsing.
Writing histograms ... 
Total of 0 reads were placed._


if I specify the genome as:

`./cnvnator -genome GRCh37 -root ~/test/out.root -tree ~/data/test.BAM`

The message is:

_Parsing file ~/data/test.BAM ...
No chromosome/contig description given.
Using GRCh37 as reference genome.
Allocating memory ...
Done.
Unknown chromosome/contig '?BC?1?}klYv^??l???V???j???\%?}Tݪ6eO??MQҨ???lf?zj?K?2I?x?82?36b{m?q?' for genome GRCh37._

Then after two days, it is still running...

**Comment by abyzov** [comment]
Hi, it looks like that either bam or executable file is corrupt. CNVnator is obviously not able to parse header and when parsing records get strange chromosome names. Hopefully recompiling could help. Are you using the same version of samtools when running standalon for parsing bam header and when compiling with CNVnator?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by peng-gang** [comment]
CNVnator works fine for some other bam files. For this bam file, I can process the data with GATK best practice without any error. 

I think CNVnator get information from SQ section in bam file header. The header looks fine for me when I check the header with samtools. It is a little weird.

I used the same version samtools (1.3.1).

**Comment by abyzov** [comment]
Well the problem seems to be related to bam header or the way CNVnator parses it. Would it be possible to create a small bam with header and ~100 aligned reads and send such bam to me. I can then use it for debugging.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by peng-gang** [comment]
It is something wrong with bam file. I regenerated bam file with 

`samtools view -bh old.bam > new.bam`

For new.bam, there is no error now. CNVnator works fine. The header is the same for old.bam and new.bam. The new.bam is 98G while the old.bam is 110G. No idea what happened.

**Comment by abyzov** [comment]
OK. Thanks for letting me know.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
