### ISSUE TITLE
Analyze multiple samples together or separated?

### ISSUE THREAD

**Issue by biocyberman** [abyzovlab/CNVnator#51]
Hi Abyzov, I am testing to see if CNVnator is sutitable for shallow sequencing data. We sequence them in batch of 6 - 12 samples on Ion Proton. The average coverage is 1X - 4X. 

I am not clear how should run CNVnator from the first step:

Should I run like this?
`cnvnator -genome hg19 -root batch1.root -tree sample1.bam sample2.bam sample3.bam ... sample12.bam`

or like this?
```
cnvnator -genome hg19 -root sample1.root -tree sample1.bam
...
cnvnator -genome hg19 -root sample12.root -tree sample12.bam
```

**Comment by abyzov** [comment]
Hi,
the info about genome is taken from bam header.
Also, you have to run root per sample, not per batch.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
