### ISSUE TITLE
Lots of deletions

### ISSUE THREAD

**Issue by P4sm** [abyzovlab/CNVnator#52]
Hi,

I have low-coverage WGS data (~1x) with many sequencing gaps, i.e. fragments where no reads are found. CNVnator classifies these as deletions, and I get considerably more deletions compared to other CNV detection algorithms. Other tools just discard these regions where no reads are found. Is there any way to get rid of this feature? I am using the default parameters.

**Comment by abyzov** [comment]
Hi,
for such shallow coverage you should use large bins. What bin size are you currently using? There is no default values for it.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by P4sm** [comment]
I have tried both 50,000 and 100,000.

**Comment by abyzov** [comment]
I see. Now I got what you are asking. There is no feature as you are asking.
You have to filter out calls in such region after calling.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
