### ISSUE TITLE
Add test cases

### ISSUE THREAD

**Issue by hmontenegro** [abyzovlab/CNVnator#54]
It would be really useful if CNVnator included a number of small test cases, which could be run quickly and help troubleshoot installation problems.

**Comment by AJ23ZX** [comment]
I agree. If we encounter some problems in the process, we can identify the impact on the results. Test cases are  also examples to guide us filter the results. It is very useful.

**Comment by abyzov** [comment]
Thanks. This is a good suggestion. Would you suggest that distribution should include a small bam file that one can test the software on?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by AJ23ZX** [comment]
Yes, I think the tutorial data can help us to find the problems in the CNV calling process and filter the results in different ways. Also you can add some explanations of representative exceptions so if we encounter some time, we can refer them. Thank you.

**Comment by abyzov** [comment]
OK. We’ll add in a couple month.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
