### ISSUE TITLE
whole scaffold is deleted

### ISSUE THREAD

**Issue by shl198** [abyzovlab/CNVnator#55]
Hello,
I run CNVnator for an organism with over 50,000 scaffolds, and in the result for some scaffolds it reports the whole scaffold is deleted. Is it because CNVnator compare the coverage of this scaffold to the background which is calculated using the whole genome?
thanks

**Comment by abyzov** [comment]
Hi,
yes this is correct. Distinction of deletions and duplication is made on average across chromosome 1-22 and XY.
In case of your organism the comparison will be made to genomewide average. So, yes it is totally possible that an entire scaffold is deleted.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
