### ISSUE TITLE
Which versions work?

### ISSUE THREAD

**Issue by wiedenhoeft** [abyzovlab/CNVnator#56]
Hi,

could someone please post which combination of versions for CNVnator and ROOT work together? I've tried to follow instructions given here, the CERN ROOT website and various versions of http://seqanswers.com/forums/showthread.php?t=16665, but so far, no success. I've tried recent versions as well as those ROOT versions from around the time of the publication.

The closest I could get to an installation was using
```
#!/usr/bin/env bash

CNVNATORVERSION=0.3
ROOTVERSION=5.30.06
INSTALLDIR=$HOME

# ROOT
ROOTPATH=${INSTALLDIR}/root
cd ${INSTALLDIR}
wget -nc https://root.cern.ch/download/root_v${ROOTVERSION}.source.tar.gz
tar -zxvf root_v${ROOTVERSION}.source.tar.gz
cd ${ROOTPATH}
source ${ROOTPATH}/bin/thisroot.csh
./configure
make


#CNVnator
echo "Getting CNVnator..."
cd ${INSTALLDIR}
wget -nc http://sv.gersteinlab.org/cnvnator/CNVnator_v${CNVNATORVERSION}.zip
unzip -o ${INSTALLDIR}/CNVnator_v${CNVNATORVERSION}.zip
SRCDIR=${INSTALLDIR}/CNVnator_v${CNVNATORVERSION}/src

echo "Making samtools..."
cd ${SRCDIR}/samtools
make

printf "\nExporting variables...\n\n"
ROOTSYS=${ROOTPATH}
export ROOTSYS
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${ROOTSYS}/lib
export LD_LIBRARY_PATH
source ${ROOTPATH}/bin/thisroot.sh
printf "\nROOTSYS is ${ROOTSYS}\n"
printf "\nLD_LIBRARY_PATH is ${LD_LIBRARY_PATH}\n\n"

printf "\nMaking CNVnator...\n\n"
cd ${SRCDIR}
make
echo ${ROOTSYS}
```

I had to remove -lPhysics -lGraph3D (which doesn't sound like it'd cause problems) from the Makefile, and manually link to pthread. At Ieast that compiled, but I got a segfault for any bam file I tried. 

Any help would be greatly appreciated.

**Comment by bintriz** [comment]
Hi,

Could you try to compile very recent version of Convertor with ROOT6. I can download v0.3.3 from https://github.com/abyzovlab/CNVnator/releases.

Thanks,

TJ

**Comment by wiedenhoeft** [comment]
Thanks for the quick reply :-) ROOT has switched to CMake, but still seems to support ./configure. Which way would you recommend?

**Comment by wiedenhoeft** [comment]
Okay, I found a way that compiles and install without manual tinkering:
`#!/usr/bin/env bash

CNVNATORVERSION=0.3
ROOTVERSION=6.08.00

INSTALLDIR=$HOME

ROOTDIR=${INSTALLDIR}/cern-root
ROOTBUILDDIR=${ROOTDIR}/build
ROOTSOURCEDIR=${ROOTDIR}/source

mkdir -p ${ROOTBUILDDIR}
mkdir -p ${ROOTSOURCEDIR}

# ROOT
cd ${INSTALLDIR}
wget -nc https://root.cern.ch/download/root_v${ROOTVERSION}.source.tar.gz
tar -xvf root_v${ROOTVERSION}.source.tar.gz -C${ROOTSOURCEDIR} --strip 1

# according to ROOT installation instructions:
cd ${ROOTSOURCEDIR}
rm -r CMakeFiles
rm CMakeCache.txt

cd ${ROOTBUILDDIR}
cmake ${ROOTSOURCEDIR}
make -j

cd ${INSTALLDIR}
wget -nc http://sv.gersteinlab.org/cnvnator/CNVnator_v${CNVNATORVERSION}.zip
unzip -o ${INSTALLDIR}/CNVnator_v${CNVNATORVERSION}.zip
SRCDIR=${INSTALLDIR}/CNVnator_v${CNVNATORVERSION}/src

echo "Making samtools..."
cd ${SRCDIR}/samtools
make -j

printf "\nExporting variables...\n"
ROOTSYS=${ROOTBUILDDIR}
export ROOTSYS
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${ROOTBUILDDIR}/lib:${ROOTSOURCEDIR}
export LD_LIBRARY_PATH
source ${ROOTBUILDDIR}/bin/thisroot.sh
printf "\nROOTSYS is ${ROOTSYS}\n"
printf "\nLD_LIBRARY_PATH is ${LD_LIBRARY_PATH}\n\n"

printf "\nMaking CNVnator...\n\n"
cd ${SRCDIR}
make

cd $HOME
`

However, I immediately get a segfault when I try to run it.

**Comment by abyzov** [comment]
Hi,
not sure for the cause. I myself is still using ROOT5. I wonder when do you get segmentation fault, when running CNVnator or when running ROOT?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by fifdick** [comment]
Hey Im having the same problems. The installation was successfull for me with root6, root works fine by itself. Executing the following command leads to "Segmentation fault (core dumped)" error.
>cnvnator -root out.root -chrom 20 -tree /path/to/sample.bam

**Comment by abyzov** [comment]
Hi,
not sure about the reason. On some system heap size is limited. You may try to decrease value for N_CHROM_MAX in the header of HisMaker.cpp, recompile, and rerun.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by fifdick** [comment]
this worked thanks!
