### ISSUE TITLE
Do I need all the bam files？

### ISSUE THREAD

**Issue by Yang-Beijing-China** [abyzovlab/CNVnator#57]
Hello,
    Recently, I used the CNVnator software to predict CNV calls on hundreds of individuals for Populus tomentosa (a plant). For comparisons of CNVs among multiple individuals, we merged all overlapping calls into unique CNVRs using the BEDTools. In total, 5300 CNVRs were detected among the population of P. tomentosa. To compare gene copy number (CN) between individuals, we want to use the “-genotype” option to infer the average CN across the gene length. But I have no idea what data or files are needed to do this procedure. I only have the reference genome sequences and the outputs of each individual CNV files in my hands (In other words, the Chromosome names, coordinates, length of genes or CNVRs are clear and detailed). If I run the commands on “–genotype” option, do I need all the bam files, which included the original reads of each resequencing individuals? In addition, could you kindly tell me the specific commands about the “-genotype”? Is this “./cnvnator –root file.root –genotype bin_size (or coordinates of genes) [-ngc]” ?
     Thank you very much for taking time to read my issue. I look forward to your reply at your earliest convenience.

Best wishes to you.

**Comment by abyzov** [comment]
Hi,
for -genotype option you need .root files for each individual.

You can use the following unix command to quickly genotype all calls (please change bins size as necessary)

awk '{ print $2 } END { print "exit" }' calls.cnvnator | ./cnvnator -root NA12878.root -genotype 100


Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
