### ISSUE TITLE
FitConfig Minuit minimizer issue, but still output

### ISSUE THREAD

**Issue by vcaropr1** [abyzovlab/CNVnator#58]
Hi,

I have been trying to run an installation of cnvnator (v0.3.3) with ROOT (v6.08.00) and the first error/warning I encounter is with calculating statistics. 

The command I run is: cnvnator -root Sample.root -stat 100

It looks like in the log after all the "Making statistics for " stages a warning/error comes up:
**Making statistics for NC_007605 ...
Making statistics for hs37d5 ...
Warning in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit minimizer. Try using the minimizer Minuit2
Error in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit2 minimizer
Error in <ROOT::Math::Fitter::FitFCN>: Minimizer cannot be created
Warning in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit minimizer. Try using the minimizer Minuit2
Error in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit2 minimizer
Error in <ROOT::Math::Fitter::FitFCN>: Minimizer cannot be created
Average RD per bin (1-22) is 19.9705 +- 16.687 (before GC correction)**

But, the output seems valid and I can continue on to the next steps (with other errors, but want to address the first one first).  My questions are: what kind of downstream issues could this error cause?  What is cnvnator using Minuit from root for?  Is it important?

**Comment by abyzov** [comment]
Hi,
the warnings definitely come from ROOT. Not sure what the cause. Looks like it is for hs37d5 file.
I, typically, exclude all chromosomes except 1-22, X, and Y.  I think this will also eliminate warnings in your case.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by vcaropr1** [comment]
Thanks for the response.  
Even if I try to only use 1-22,X, and Y the following error persists: 
Partitioning RD signal for '1' with bin size of 100 ...
Warning in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit minimizer. Try using the minimizer Minuit2
Error in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit2 minimizer
Error in <ROOT::Math::Fitter::FitFCN>: Minimizer cannot be created
Warning in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit minimizer. Try using the minimizer Minuit2
Error in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit2 minimizer
Error in <ROOT::Math::Fitter::FitFCN>: Minimizer cannot be created
Average RD per bin is 19.1366 +- 16.4367

Are these two errors relating to a single issue that isn't just sequence dependent?

**Comment by abyzov** [comment]
I’m worried that this could cause problems. Looks like ROOT can’t run function to perform fitting. Fitting is used by CNVnator to approximate RD distribution with Gaussian function.

Is reported RD of 19.13 reads per bin is expected? Standard deviation (16.43) seem to be too large.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by vcaropr1** [comment]
I don't believe the RD should be that low considering the overall average for the bam file is 26.59 (calculated by samtools depth) unless there might be a better way of comparing the RD to validate if they are similar or not.

**Comment by abyzov** [comment]
Do you have the same behavior if you use larger bin size (e.g., 1000 bp)?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by vcaropr1** [comment]
Looks like the same behavior when I attempted to use two different runs (bin size 1000 and 200).  The RD per bin seemed to be higher, but also a higher SD associated with it.  

e,g. : 
**Partitioning RD signal for '21' with bin size of 200 ...
Warning in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit minimizer. Try using the minimizer Minuit2
Error in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit2 minimizer
Error in <ROOT::Math::Fitter::FitFCN>: Minimizer cannot be created
Warning in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit minimizer. Try using the minimizer Minuit2
Error in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit2 minimizer
Error in <ROOT::Math::Fitter::FitFCN>: Minimizer cannot be created
Average RD per bin is 37.8188 +- 21.9788**

**Comment by abyzov** [comment]
Hi,
while CNVnator returns results I’m concerned that SD is so high.

You'd better conduct manual check of the data:
1) start ROOT
2) open browser by typing “new TBrowser”
3) Open .root file by double clicking
4) Open directory with histograms, i.e., bin_100 or bin_200
5) Visualize distributions by clicking on rd_p_GC_100 or rd_p_GC_200
6) Inspect visually and fit manually by right click on distribution and choosing “Fit” option.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by vcaropr1** [comment]
The installation we have on site doesn't have the X11 install.  So we do not have the gui available for root.  Do you happen to know the command line equivalent for this?

**Comment by vcaropr1** [comment]
I was able to get the installation working to use TBrowser.  Still is showing mean 37.82 and RMS 43.96.  

![image](https://cloud.githubusercontent.com/assets/13681254/24305435/55527376-1093-11e7-84ab-9befe5252e6c.png)

**Comment by abyzov** [comment]
Could you try to fit it with Gaussian function (right click on the distribution and then Fit) and see which mean and SD it will return.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by vcaropr1** [comment]
I did that and there was no return.  When I click Fit it prompts me with a box and 5 values to enter for a formula.  But, after hitting OK nothing returns.  

![image](https://cloud.githubusercontent.com/assets/13681254/24308574/d8a974b2-109e-11e7-82d6-427e1652da84.png)

**Comment by abyzov** [comment]
Hi,
you should type “gaus” for the formula.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by vcaropr1** [comment]
Thanks (never used ROOT before)
The return mean is 38.99 +/- 0.00

![image](https://cloud.githubusercontent.com/assets/13681254/24356134/b87726a6-12c6-11e7-9d78-e47a5781283c.png)

**Comment by abyzov** [comment]
Hi, this looks very good! Mean is ~39 with SD of ~8. Results returned by CNVnator give much higher SD, so I’m guessing CNVnator was not able to run Fit function for some reason. Could you check whether -eval command gives the same results

./cnvnator -root your.root -eval 200

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by vcaropr1** [comment]
Looks like the same error and a lower RD and higher SD.

./cnvnator -root your.root -eval 200
**Warning in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit minimizer. Try using the minimizer Minuit2
Error in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit2 minimizer
Error in <ROOT::Math::Fitter::FitFCN>: Minimizer cannot be created
Warning in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit minimizer. Try using the minimizer Minuit2
Error in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit2 minimizer
Error in <ROOT::Math::Fitter::FitFCN>: Minimizer cannot be created
Average RD per bin (1-22) is 37.8188 +- 21.9788 1.72069
Warning in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit minimizer. Try using the minimizer Minuit2
Error in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit2 minimizer
Error in <ROOT::Math::Fitter::FitFCN>: Minimizer cannot be created
Warning in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit minimizer. Try using the minimizer Minuit2
Error in <ROOT::Math::FitConfig::CreateMinimizer>: Could not create the Minuit2 minimizer
Error in <ROOT::Math::Fitter::FitFCN>: Minimizer cannot be created
Average RD per bin (X,Y)  is 23.998 +- 17.3758 1.38112**

**Comment by abyzov** [comment]
Right. Not sure about the source. It is something related to ROOT. Which root version are you using?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by vcaropr1** [comment]
I am using root-6.08.00

**Comment by abyzov** [comment]
I would suggest to try ROOT v5.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
