### ISSUE TITLE
A tiny question

### ISSUE THREAD

**Issue by GuannanW** [abyzovlab/CNVnator#6]
Hi abyzov

Just a really tiny question. I am currently working on nonhuman genome analysis. And I have tried CNVnator these days to identify the CNV in my samples. But when I convert my cnv files into VCF files, in the headers, I see "##reference=1000GenomesPhase3_decoy-GRCh37". It still shows the human genome reference. 
So now, I am not quite sure whether it is able to call cnv in nonhuman genome(although I am sure there are some people doing this)? why it still shows human reference genome in the vcf file,even if I used nonhuman reference genome? And how should I use cnvnator for nonhuman genome cnv calling? Is it different from what's in the README file?
Thank you!

Nan

**Comment by abyzov** [comment]
Dear GuannanW,
please change the relevant line in converting script to genome of your choice in resulting vcf. Yes, CNVnator can call CNVs for non-human genome. Info about chromosomes is parsed from bam header. With correct bam you can use CNVnator with any genome. The only assumption CNVnator makes is that genome is diploid (except X and Y). Please keep this in mind.
