### ISSUE TITLE
Trouble Visualizing Specified Regions

### ISSUE THREAD

**Issue by km4htc** [abyzovlab/CNVnator#62]
I'm having trouble when trying to visualize a particular region. When I enter the command as given, I'm prompted to type my specified region; after I enter that it continues to prompt me to enter a specified region again and again. I've tried all of the variations of how to input the region of interest, but continue to get the prompt (with no errors). 

>cnvnator -root my.root -view 100
> '>chr11:150988001-150996400
> '>##here is where it continues to prompt after I've entered a region

Any insight would be appreciated!
Thanks!

**Comment by abyzov** [comment]
Hi,
if you are using cnvnator via connection to a remote site (e.g., a server) you have to make sure that the connection enables graphics.
For example, for ssh connection one have to use -X option: ssh -X user@host
If the problem occurs on you personal machine please make sure you can start ROOT with graphics.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
