### ISSUE TITLE
CNVnator q0 results

### ISSUE THREAD

**Issue by dovivi** [abyzovlab/CNVnator#63]
I've read that I should filter CNV calls by q0 < 0.5
My CNV calls have either 1 or -1 q0 value, I first wonder if this is a clear signal of a bad run (maybe wrong bin size?) and second if the q0 values are OK, should I only keep those with -1 q0 value (~ 7 out of 1000 calls)?

Below a small sample of the cnv calls I've got:

deletion	scaffold_175:1-2000	2000	0	3.17685e-06	205591	1	1	-1
deletion	scaffold_154:1-2750	2750	0	5.79536e-11	5736.13	591.689	8.01028e+07	-1
deletion	scaffold_207:1-1250	1250	0.00906204	0.0308282	8.42022e+06	1	1	-1
deletion	scaffold_223:1-2750	2750	0.0977095	0.00036926	49101.9	1094.67	9.30538e+07	1
deletion	scaffold_236:1-2500	2500	0.0344404	8.2648e-05	114949	39361.2	2.64105e+08	1
deletion	scaffold_277:1-2500	2500	0.0579412	0.00291712	247346	377180	4.41659e+08	1

An additional question is, to which e-value should I pay more attention for filtering?

Thanks

**Comment by abyzov** [comment]
Hi,
-1 for q0 means it couldn’t be calculated. The likely reason is that no reads were mapped in that region. Not sure why you get 1 for other regions. Could you check bams to make sure those regions have uniquely mapped reads.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by dovivi** [comment]
OK, +1 q0 regions don't have uniquely mapped reads, I guess that's the problem then. 
For the -1 q0 value it's true that these are regions with no mapped reads.

Thanks for your reply!

**Comment by fakedrtom** [comment]
I'd like to follow up on this as I am confused. I am comparing CNVnator results to SVs called by Lumpy on whole genome data, specifically I am comparing deletions called by both methods. I have a dozen or so deletions for a sample that are called by both methods that I have analyzed on IGV. They look about as real as any CNV can look, but they all have q0 of 1. I know that you recommend filtering out q0 > 0.5, but these look real and I wouldn't want to toss them. Not sure why they have a q0 of 1 as every read I have inspected has a very high mapping quality (MQ > 30, most around 60). They were aligned with BWA. I've attached a screenshot from IGV of an example. 

Thanks!

![image](https://cloud.githubusercontent.com/assets/27868365/25974706/adda3976-3667-11e7-8c59-3979e81d084c.png)

**Comment by abyzov** [comment]
Hi,
yes, they should all have very small q0. May be cnvnator returns incorrect values. I’m wondering whether you have events on chromosomes 20, 21 or 22 and make a bam file that I can download for one of them.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by fakedrtom** [comment]
Thank you for your response. I apologize for creating an issue as I have discovered that I was having an unexpected format issue with some of my downstream analysis using the cnvnator output and  mistakenly thought that the q0's were all near 1. I've corrected this and the q0's are now below 0.5 as expected. Sorry!

**Comment by moshl** [comment]
I meet the same problem as you. But my q0 results is zero or -1.  This is why? How I should to solve this?
my code :
O=/pnas/liuxin_group/moshl/NR_yangjy/Results/CNVnator/Lxf
I=/pnas/liuxin_group/moshl/NR_yangjy/Results/BQSR/Lxf
ref=/pnas/liuxin_group/moshl/Ref/bwa-0.7.10/hg19.fa
ref_dir=/pnas/wangqf_group/database/RefDB/hg19/
cnvnator=/pnas/liuxin_group/moshl/software/CNVnator-0.3.3/cnvnator

#extract reads from bam to root file

$cnvnator -root $O/Lxf_1D0.root -genome $ref -tree $I/Lxf_1D0.dedup.recal.BQSR.bam -unique > $O/Lxf_1D0_extract.out

#create histograms
$cnvnator -root $O/Lxf_1D0.root -genome $ref -d $ref_dir -his 100 > $O/Lxf_1D0.histogram.out

#calculate statistics
$cnvnator -root $O/Lxf_1D0.root -stat 100 > $O/Lxf_1D0.stats.out

#rd signal partitioning
$cnvnator -root $O/Lxf_1D0.root -partition 100 > $O/Lxf_1D0.partition.out

#cnv calling
$cnvnator -root $O/Lxf_1D0.root -call 100 > $O/Lxf_1D0.cnvout.txt

my results(parts):
deletion        chr1:1-13000    13000   0.0142559       1.22594e-11     1.62128e-158    1.44884e-11     8.7166e-133     0
deletion        chr1:13501-14600        1100    0.103018        0.014695        0.00109037      1       1       0
deletion        chr1:16601-17300        700     0.149361        4.91145 3.05658e-05     1       1       0
deletion        chr1:17501-51300        33800   0.0971046       4.71516e-12     2.871e+09       5.01171e-12     2.8629e+09      0
deletion        chr1:53301-53900        600     0.00759224      0.000754006     9.9825e-14      1       1       0
deletion        chr1:59601-60200        600     0.0988811       17.7128 7.91071e-05     1       1       0
deletion        chr1:65101-65800        700     0.0198011       6.4932e-05      1.93653e-17     1       1       0
deletion        chr1:67701-68100        400     0.116291        662.521 0.00610872      1       1       0
deletion        chr1:68601-73000        4400    0.291572        1.62647e-06     2.86718e+09     0.0990328       2.86892e+09     0
deletion        chr1:75101-75700        600     0.0231497       0.00384644      1.11169e-13     1       1       0
deletion        chr1:78301-78900        600     0.0152407       0.0255061       4.65264e-12     1       1       0
duplication     chr1:85601-88800        3200    1.80481 8.75752e-07     0.00274719      50.0237 0.00817683      0
deletion        chr1:90301-90800        500     0.0566719       140.887 0.00199538      1       1       0
deletion        chr1:93401-98300        4900    0.331211        9.41073e-05     2.87017e+09     7.15871 2.87051e+09     0

**Comment by abyzov** [comment]
Hi,
they calls you are listing seems homozygous deletions, which is why q0 is 0 or -1. May be bin of 100 bp is too small for the coverage that you have?


Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by moshl** [comment]
thanks your reply. But I am very confused.Do you mean that bin size effects q0? My data is WGS 30X and the length of reads is 150pb.So ,How I can choose the bin size?  I read the "how to set bin size (https://github.com/abyzovlab/CNVnator/issues/19)" , I run the code by the suggestion, 
the code is : 
./cnvnator -root out1.root -genome /pnas/liuxin_group/moshl/Ref/bwa-0.7.10/hg19.fa -tree /pnas/liuxin_group/moshl/NR_yangjy/Results/BQSR/Lxf/Lxf_1D0.dedup.recal.BQSR.bam -unique
./cnvnator -root out1.root -genome /pnas/liuxin_group/moshl/Ref/bwa-0.7.10/hg19.fa -d /pnas/wangqf_group/database/RefDB/hg19/ -his 100
./cnvnator -root out1.root -stat 100
./cnvnator -root out1.root -eval 100

the output is :
File out1.root
Average RD per bin (1-22) is 21.7807 +- 5.82742 3.73763
Average RD per bin (X,Y)  is 11.1595 +- 4.13733 2.69727
So , What is the optional bin size? why? thanks again.

**Comment by abyzov** [comment]
If bin size is too small you can have strange numbers and behaviors because of small statistics. In your can bin size seem to be fine.
For homozygous deletion q0 could be -1 if not reads are mapped.
Is there a problem with q0 equal to 0? Those seems like regions with confident read mappings.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by FanruiMeng** [comment]
I meet the same problem, I use the bin size 100 and the mean to sigma is  4.3, I think it's ok, but my q0 is just -1 or 1, what should I do to solve this problem? My results of CNVnator is:
[Res_Sly_illumina_CNVnator_results_binsize_100.txt](https://github.com/abyzovlab/CNVnator/files/1075682/Res_Sly_illumina_CNVnator_results_binsize_100.txt)

**Comment by abyzov** [comment]
Hi,
this is not an expected behavior. The question is what cases it. Could you please check your bam and make sure that you have non q0 reads for some duplication.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by FanruiMeng** [comment]
Thank you for your reply. I did the CNVnator analysis with bin size = 50bp, 100bp, 150bp, 200bp and 500bp(when the bin size is 100 to 200, the value of mean to sigma is 4 to 5). All the output have the q0 = 1. I checked the bam file, and found that for some duplication regions, there are lots of non q0 mapping reads. I also used the parametere -unique to do the CNVnator analysis again, the output became normal. But in your orignal paper you said 'When used with uniquely mapped reads, CNVnator calls for 10-fold more deletion and threefold less duplication, suggesting that the results are unreliable'. So I don't know what I should do to deal with it. Thank you so much! The results of used -unique parametere is:
[Res_Sly_illumina_CNVnator_results_binsize_100_unique.txt](https://github.com/abyzovlab/CNVnator/files/1077741/Res_Sly_illumina_CNVnator_results_binsize_100_unique.txt)

**Comment by moshl** [comment]
thanks. But I also did the CNVnator analysis with bin size = 20bp,50bp, 100bp, 200bp and 1000bp. I got the same results. All the output have the q0 = 0 or -1. I see the FanruiMeng's results, the q0=[0,1] or -1. Why the q0=0 or -1 in my analysis? where are the errors?

**Comment by abyzov** [comment]
Hi,
yes one alway have to use -unique option to have correct value of q0. This is mentioned in the README file.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by abyzov** [comment]
Hi,
did you use -unique option?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by moshl** [comment]
Yes, I did.  But I also did the CNVnator analysis with bin size = 20bp,50bp, 100bp, 200bp and 1000bp. I got the same results. All the output have the q0 = 0 or -1. I see the FanruiMeng's results, the q0=[0,1] or -1. Why the q0=0 or -1 in my results? where are the errors?
my code :
O=/pnas/liuxin_group/moshl/NR_yangjy/Results/CNVnator/Lxf
I=/pnas/liuxin_group/moshl/NR_yangjy/Results/BQSR/Lxf
ref=/pnas/liuxin_group/moshl/Ref/bwa-0.7.10/hg19.fa
ref_dir=/pnas/wangqf_group/database/RefDB/hg19/
cnvnator=/pnas/liuxin_group/moshl/software/CNVnator-0.3.3/cnvnator

#extract reads from bam to root file

$cnvnator -root $O/Lxf_1D0.root -genome $ref -tree $I/Lxf_1D0.dedup.recal.BQSR.bam -unique > $O/Lxf_1D0_extract.out

#create histograms
$cnvnator -root $O/Lxf_1D0.root -genome $ref -d $ref_dir -his 100 > $O/Lxf_1D0.histogram.out

#calculate statistics
$cnvnator -root $O/Lxf_1D0.root -stat 100 > $O/Lxf_1D0.stats.out

#rd signal partitioning
$cnvnator -root $O/Lxf_1D0.root -partition 100 > $O/Lxf_1D0.partition.out

#cnv calling
$cnvnator -root $O/Lxf_1D0.root -call 100 > $O/Lxf_1D0.cnvout.txt

**Comment by LiuYANG0016** [comment]
Please add the opt "-unique" in "EXTRACTING READ MAPPING FROM BAM/SAM FILES" step. Like this "./cnvnator [-genome name] -root out.root [-chrom name1 ...] -tree [file1.bam ...] -unique". That you will fix it.

**Comment by abyzov** [comment]
Hi,
not sure where the error is. If you can send me a link to a small sample file then I can try to debug it.


Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by wangtao-prog** [comment]
I meet the same problem as you. But my q0 results is all 1. This is why?  where are the errors?
my code :
O=/pnas/liuxin_group/moshl/NR_yangjy/Results/CNVnator/Lxf
I=/pnas/liuxin_group/moshl/NR_yangjy/Results/BQSR/Lxf
ref=/pnas/liuxin_group/moshl/Ref/bwa-0.7.10/hg19.fa
ref_dir=/pnas/wangqf_group/database/RefDB/hg19/
cnvnator=/pnas/liuxin_group/moshl/software/CNVnator-0.3.3/cnvnator

#extract reads from bam to root file

$cnvnator -root $O/Lxf_1D0.root -genome $ref -tree $I/Lxf_1D0.dedup.recal.BQSR.bam > $O/Lxf_1D0_extract.out

#create histograms
$cnvnator -root $O/Lxf_1D0.root -genome $ref -d $ref_dir -his 100 > $O/Lxf_1D0.histogram.out

#calculate statistics
$cnvnator -root $O/Lxf_1D0.root -stat 100 > $O/Lxf_1D0.stats.out

#rd signal partitioning
$cnvnator -root $O/Lxf_1D0.root -partition 100 > $O/Lxf_1D0.partition.out

#cnv calling
$cnvnator -root $O/Lxf_1D0.root -call 100 > $O/Lxf_1D0.cnvout.txt
