### ISSUE TITLE
How to use the  parameter of  -eval  

### ISSUE THREAD

**Issue by AJ211** [abyzovlab/CNVnator#65]
Hi， A problem occured When I'm ready to  decide the bin-size，I  wonder which step should add the parameter -eval and how to use it correctly？I tried it in the step  of -his，however，nothing  happened except  for  some errors。

Excepting your replay！
Thanks a lot !

**Comment by abyzov** [comment]
Hi,
-eval returns values of mean and sigma once histograms are calculated.
For example
cnvnator -root my.root -his 1000 -d dir_with_chrom_fas
cnvnator -root my.root -eval 1000

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by AJ211** [comment]
Thank you very much！I got it。
And I have another question，except the filtering  parameter  with q0<0.5， some papers  also use  the  p-value  to filter  the CNV result，but there is no p-value  in the output file，so the  p-value is  only defined  by just a few article's authors？ if not , how I can get the p-value?

**Comment by abyzov** [comment]
Hi,
the output has e-values.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
