### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by HelenCousins** [abyzovlab/CNVnator#68]
With root-6.06.08/ or root-6.08.06/ I get 
usr/bin/ld: cannot find -lCint
when I try make in CNVnator_v0.3/src
this after editing Makefile to correctly point at 
 -L$(ROOTSYS)/lib/root
not 
 -L$(ROOTSYS)/lib
Is there a recommended version of root that does include libCint?

**Comment by abyzov** [comment]
Hi,
I believe there is no need to link Cint library in the ROOT v6. It should be safe to remove it from Makefile.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
