### ISSUE TITLE
Genotype and copy number in cnvnator2VCF

### ISSUE THREAD

**Issue by rtwen** [abyzovlab/CNVnator#69]
Hi, I have a question about the copy number get in cnvnator2VCF.pl . In my result, the cn of many dups were set to 2 .   The cnvnator2VCF.pl used the RD value to get the copy number, RD value has been normalized to 1 , but cn  is 2 for all germline chromosomes except for X and Y in males . So  I can't understand the number of copies of dups that are rounding RD value. So, why is that?

thanks!

**Comment by abyzov** [comment]
Sorry,
I’m not sure I understand the problem. Can you print few lines as an example.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by rtwen** [comment]
hi， As shown in the following example ,  the copy number ( cn ) of  many duplications was 2  in the vcf file that got by cnvnator2VCF .  Why is that ? thanks !

example:

1   142857401   CNVnator_dup_307    G   <DUP>   .   PASS    END=142868600;SVTYPE=DUP;SVLEN=11200;IMPRECISE;natorRD=1.81955;natorP1=0;natorP2=2.86805e+09;natorP3=3.81108e-09;natorP4=2.86858e+09;natorQ0=0.835785   GT:CN   ./1:2
1   142874401   CNVnator_dup_308    G   <DUP>   .   PASS    END=142879400;SVTYPE=DUP;SVLEN=5000;IMPRECISE;natorRD=2.27237;natorP1=0;natorP2=1.97902e+09;natorP3=5.24669e-05;natorP4=2.20362e+09;natorQ0=0.853507    GT:CN   ./1:2
1   142886701   CNVnator_dup_309    C   <DUP>   .   PASS    END=142913200;SVTYPE=DUP;SVLEN=26500;IMPRECISE;natorRD=3.03224;natorP1=0;natorP2=2.83806e+09;natorP3=0;natorP4=2.84054e+09;natorQ0=0.801559 GT:CN   ./1:3
1   142916501   CNVnator_dup_310    A   <DUP>   .   PASS    END=142967800;SVTYPE=DUP;SVLEN=51300;IMPRECISE;natorRD=2.78549;natorP1=0;natorP2=2.85753e+09;natorP3=0;natorP4=2.85805e+09;natorQ0=0.768368 GT:CN   ./1:3
1   143117801   CNVnator_dup_312    T   <DUP>   .   PASS    END=143170200;SVTYPE=DUP;SVLEN=52400;IMPRECISE;natorRD=2.32205;natorP1=0;natorP2=2.57471e+09;natorP3=0;natorP4=2.58544e+09;natorQ0=0.153985 GT:CN   ./1:2
1   143174101   CNVnator_dup_313    T   <DUP>   .   PASS    END=143182100;SVTYPE=DUP;SVLEN=8000;IMPRECISE;natorRD=2.28037;natorP1=0;natorP2=0.259273;natorP3=2.12497e-09;natorP4=84.1059;natorQ0=0.171983   GT:CN   ./1:2
1   143182701   CNVnator_dup_314    A   <DUP>   .   PASS    END=143216000;SVTYPE=DUP;SVLEN=33300;IMPRECISE;natorRD=1.87124;natorP1=0;natorP2=5.6753e+06;natorP3=0;natorP4=8.24886e+06;natorQ0=0.253462  GT:CN   ./1:2
1   143217301   CNVnator_dup_315    T   <DUP>   .   PASS    END=143220400;SVTYPE=DUP;SVLEN=3100;IMPRECISE;natorRD=2.04157;natorP1=0.00948026;natorP2=1.45705e-06;natorP3=56.1995;natorP4=0.00203053;natorQ0=0.461538    GT:CN   ./1:2
1   143224801   CNVnator_dup_316    G   <DUP>   .   PASS    END=143227000;SVTYPE=DUP;SVLEN=2200;IMPRECISE;natorRD=2.13077;natorP1=0.00166689;natorP2=32959.8;natorP3=936425;natorP4=57.2054;natorQ0=0.626597    GT:CN   ./1:2
1   143229401   CNVnator_dup_317    A   <DUP>   .   PASS    END=143269200;SVTYPE=DUP;SVLEN=39800;IMPRECISE;natorRD=2.29612;natorP1=0;natorP2=3.71729e+08;natorP3=0;natorP4=4.11946e+08;natorQ0=0.390564 GT:CN   ./1:2
1   143276801   CNVnator_dup_318    C   <DUP>   .   PASS    END=143281300;SVTYPE=DUP;SVLEN=4500;IMPRECISE;natorRD=4.27221;natorP1=0.0251076;natorP2=9.20147e-09;natorP3=384.28;natorP4=0.548336;natorQ0=0.405023    GT:CN   ./1:4

**Comment by abyzov** [comment]
Hi,
do you refer to natorRD value? Is it different from the original output?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by rtwen** [comment]
hi，I refer to CN value. The natorRD value is same as  the original output.

**Comment by abyzov** [comment]
Hi,
it looks like the output is correct. The interpretation is that for CN > 3 we can’t be sure that this is homozygous locus or combination of other CN for multi-allelic loci, e.g., CN4 = CN3+CN1. Please decide what is the most rational way to treat such call in your project. Perhaps, you can consider them homozygous.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by rtwen** [comment]
Thanks！ how about duplications with CN==2 ，is that correct？

**Comment by rtwen** [comment]
Thanks!  What‘s  the mean about DUP with "CN ==2 "  in the output？

**Comment by abyzov** [comment]
Hi,
not this is not correct. I looked into the code and see that there is an error. For CN it actually reports RD (read depth), i.e., normalized to 1. Please consider this when analyzing the data. I won’t be able to fix this soon at GitHub because of traveling.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by rtwen** [comment]
OK，thank you！ I wish you a pleasant journey.
