### ISSUE TITLE
Wrong release version?

### ISSUE THREAD

**Issue by boboppie** [abyzovlab/CNVnator#7]
Dear @abyzov ,

Should the version be 0.3.1 as specified in Makefile rather than v3.0.1?

Best wishes,
Fengyuan

**Comment by abyzov** [comment]
Right! Thanks for catching it up.

**Comment by bintriz** [comment]
I had made a mistake. I fixed it. Thanks.

**Comment by boboppie** [comment]
Dear @abyzov and @bintriz ,

Thanks for the quick fix and your contribution to the community!

Best wishes,
Fengyuan
