### ISSUE TITLE
problem in the installation of cnvnator

### ISSUE THREAD

**Issue by misbahabbas** [abyzovlab/CNVnator#70]
hello,

i am beginner in this field, I am trying to install CNVnator but there is error when "make" in the cnvnator/src . please help me
thanks

Compiling with parallel (OpenMP) support g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.3\" -fopenmp -o cnvnator obj/cnvnator.o obj/EXOnator.o obj/HisMaker.o obj/AliParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a samtools/htslib-1.3.1/libhts.a -lz -L/lib -lCore -lRIO -lHist -lGraf -lGpad -lTree -lMathCore /usr/bin/ld: cannot find -lCore /usr/bin/ld: cannot find -lRIO /usr/bin/ld: cannot find -lHist /usr/bin/ld: cannot find -lGraf /usr/bin/ld: cannot find -lGpad /usr/bin/ld: cannot find -lTree /usr/bin/ld: cannot find -lMathCore collect2: error: ld returned 1 exit status make: * [cnvnator] Error 1

**Comment by abyzov** [comment]
Hi,
please set ROOTSYS variable.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
