### ISSUE TITLE
the cnv border lager than the chromosome length

### ISSUE THREAD

**Issue by AJ211** [abyzovlab/CNVnator#72]
Hello,there is a strange phenomenon,and i don't know if it's normal.for example:
## cnv result:
deletion        chr1:22113001-22396500  283500  0.58044 5.62161e-13     2.871e+09       5.68173e-13         2.871e+09       0.143542
## the chromosome information:
chr1    length=22395194

**Comment by abyzov** [comment]
Hi,
22 MB deletion do happen occasionally. Please use option -view to check your results.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
