### ISSUE TITLE
Can't open file with chromosome sequence

### ISSUE THREAD

**Issue by AJ211** [abyzovlab/CNVnator#74]
Hello,I'm using CNVnator to call CNV in whole genome scale today ,so I don't need to give the each chromosome imformation in principle ,but when I run the tool  in the step of  -his  ,it gives some imformation (for each chromosome):

Can't open file with chromosome sequence.
 No chromosome/contig information parsed.
 Sequence length (0) is different from expectation (10322184) for 'chr4'

In addition,When it goes to the step  -stat  and  -partition,it gives some other imformation(also for each chromosome):

No histogram with GC content for 'scaffold2718' found.
No correction made

Can't find GC-content histogram for 'chr4';

but, there  is  CNV result   in the end ,so I don't know if the imformation  as shown above has an effect on the result? and when I use CNVnator in whole genome ,should I divide the genome to each chromosome and put these single files in the directory  where the parameter -d  in the -his step  need？

this is my code:
cnvnator -root sample.root -tree  sample.bam -unique 
cnvnator -root  sample.root  -d   ./ (my  genome  fasta file in the directory)   -his 500 
cnvnator  -root  sample.root -stat 500
cnvnator -root  sample.root  -partition 500

Looking forward to your reply.Thanks very much.

**Comment by abyzov** [comment]
Hi,
looks like there is a problem with .fa file for chr4. Does it exist? Does it have valid content?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by AJ211** [comment]
Hi, I only have the whole genome fasta file, there is not each chromosome file.  for whole genome CNV, does it also need each .fa file ?

**Comment by abyzov** [comment]
Yes, the software requires .fa file for each chromosome.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by AJ211** [comment]
Ok , I got it.Thanks very much.

**Comment by yuntwang** [comment]
Hi:
@abyzov 
Another question:
My chromosome is Chr1,Chr2,Chr3……
The command :
./cnvnator  -genome ref.genome.fa -root R01.root -chrom Chr1 Chr2 Chr3 -d  (my genome fasta file in the directory) -his 100 
The error:
Can't open file ./CNV/chr1.fa
Can't open file ./CNV/chr2.fa
Can't open file ./CNV/chr3.fa
But in the directory of CNV, the chromosome file is Chr1.fa Chr2.fa Chr3.fa.
Why are lower case?
When I rename it (mv Chr1.fa chr1.fa).
It can run.
why?

**Comment by abyzov** [comment]
It is probably a little bug in the program.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by yuntwang** [comment]
@abyzov 
Thanks!
Another question:
When I GENERATING A HISTOGRAM use the command:
/cnvnator -genome sequences.fa -root R01.root -chrom Chr1 -d  (my genome fasta file in the directory) -his 100
it can run but I get nothing!
For example:
Allocating memory ...
Done.
Calculating histograms with bin size of 100 for 'Chr1.' ...
Making directory bin_100 ...
Making GC histogram for 'Chr1' ...

Run for a long time（about 10 hours）without any result！
Why？
You said：This step is not memory consuming and so can be done for all chromosomes
at once.
Why I did not have any result and I did not get the directory bin_100 ?
Hope to get your reply.

**Comment by abyzov** [comment]
Hi,
yes, this step should complete within minutes. Not sure why it takes so long for you. How dos you .fa files for chromosome looks like?

Also, you don’t need to specify genome, as information is parsed from bam header.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by yuntwang** [comment]
@abyzov 
Thanks for your reply.
My chromosome file (chr1.fa) like this:
less -S  chr1.fa
>Chr1
GCGTGGCGTGACATGGTGTGACTGGTTGGTCAATTAGCCGACAATGGATCCACCGCCCATGAACCG……
Only two lines.

But I transform it many lines
like this:
>Chr1:
GCGTGGCGTGACATGGTGTGACTGGTTGGTC
AATTAGCCGACAATGGATCCACCGCCCATGA
……
Yes，I can get the final result.

Maybe the problem is here.
Thanks for your tips.

**Comment by abyzov** [comment]
Hi,
do you have ‘>’ in the first line?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by Rachael-rq** [comment]
Hi Alexej,

Should be .fa file for each chromosome be placed in the same directory with the .root file ?

Thanks
lyu

**Comment by abyzov** [comment]
It should be either in the current dir or in dir specified by -d option.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by GangLiTarheel** [comment]
Hi Alexej! 
I am trying to use CNVnator to call a particular small region (~300kb) on Chr16, and use its result as the input of svtools copynumber. I met an error with CNVnator:
Can't open file with chromosome sequence.
No chromosome/contig information parsed.
Sequence length (0) is different from expectation (90338345) for 'chr16'.
Doing nothing!

I am guessing that maybe CNVnator is designed to call on the whole chromosone scale only. But I see the @issue Can't open file with chromosome sequence
where he tried it on the whole chromsone scale, but meet with the same error.

See my chr16.fa
_less chr16.fa

chr16
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
...._

See my code:
cnvnator -root $rootname.root -chrom $chrom -tree $bam 2>err
cnvnator -root $rootname.root -chrom $chrom -his $bin_size -d /var/data/ 2>>err
bin_size=10.

Do you have any idea to solve this issue?

Thank you for your time and efforts.
Best,
Gang

**Comment by Rachael-rq** [comment]
Hi Gang,

I think it requires the .fa file for each chromosome, so you may need to
split your whole genome sequence file into chr1.fa, chr2.fa etc. and
specify the location of these files via the -d argument.


Best regards,
Ruqian

2018-01-04 7:14 GMT+11:00 GangLiTarheel <notifications@github.com>:

**Comment by abyzov** [comment]
Hi,
I’m not sure but I don’t see ‘>’ in front of chr16 in your file. May be this is the reason.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by GangLiTarheel** [comment]
Hi Alexej,
I do have '>' in front of my file.
The reason it does not present before is that when you type a single '>' in
github, it automatically changing to quote mode and do not print '>'.
> The line begin with a '>'.

Best,
Gang

**Comment by GangLiTarheel** [comment]
Hi Ruqian,

Thank you for replying me. But I do have a .fa file for chromosome 16.

Best,
Gang

**Comment by abyzov** [comment]
Hard to say what the problem is. Could you please check that sequence of the chromosome is in multiple rather than in one line.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by GangLiTarheel** [comment]
Hi Alexej,
Thank you for replying me.

The chr16.fa has 1,806,768 lines in total.

cat chr16.fa | wc -l
1806768

tail -5 chr16.fa
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

head -3 chr16.fa
>chr16
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

Thank you for your time and efforts.
Best,
Gang

**Comment by abyzov** [comment]
I guess then that something is about file name because the software give the error
“Can't open file with chromosome sequence."

I would propose to duplicate to Chr16.fa and 16.fa files.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by Rachael-rq** [comment]
Hi,

When I do
head -3 chr16.fa

I got
>16
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

without the "chr", so maybe the chrom format not matching with your bam
file or something?


Regards,
Ruqian

2018-01-16 11:30 GMT+11:00 abyzov <notifications@github.com>:

**Comment by GangLiTarheel** [comment]
Hi Ruqian,

I am using GRCh38 as reference genome. Maybe that's the reason that the
formats are different. Need I make any adjustments for that? Since in the
example workflow, CNVnator use CRCh37 as reference genome.

Best,
Gang

**Comment by GangLiTarheel** [comment]
Hi Alexej,

Just to clarify.
Do you mean that I should rename the chr16.fa to 16.fa, as well as other
fasta files related? Besides, does CNVnator work with GRCh38?

Best,
Gang

**Comment by abyzov** [comment]
Yes, rename the file.
CNVnator works with any genome that is described in BAM header.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by fifdick** [comment]
I had the same problem and tried all mentioned suggestions. None helped. I saw that the naming of my files was right (after checking the source code to see how the path is build up). I also have correct .fa format.
In the end I think my problem was that I had read-only permissions on those files. Changing this solved it for me. Maybe this also helps someone else.

**Comment by lindenb** [comment]
same problem here:

my command looks like:

```
module load cnvnator/0.3.2.20161114git && \
cnvnator -root SAMPLE9FZ.20181002.chr1.vcf.root -chrom chr1 -tree input.realign.bam  -unique && \
cnvnator -root SAMPLE9FZ.20181002.chr1.vcf.root -chrom chr1 -his 1000  && \
cnvnator -root SAMPLE9FZ.20181002.chr1.vcf.root -chrom chr1 -stat 1000 -d /path/to/REF && \
cnvnator -root SAMPLE9FZ.20181002.chr1.vcf.root -chrom chr1 -partition 1000 && \
cnvnator -root SAMPLE9FZ.20181002.chr1.vcf.root -chrom chr1 -call 1000 > SAMPLE9FZ.20181002.chr1.tsv && \
cnvnator2VCF.pl -prefix C0009FZ  SAMPLE9FZ.20181002.chr1.tsv  /path/to/REF  > SAMPLE9FZ.20181002.chr1.vcf
```

with the fasta files:

```
$ ls -lah  /path/to/REF
drwxr-s---. 2 lindenbp fg0073 4.0K Oct  3 12:06 .
drwxr-s---. 4 lindenbp fg0073 4.0K Oct  2 15:17 ..
-rw-r--r--. 1 lindenbp fg0073 132M Oct  2 15:50 chr10.fa
-rw-r--r--. 1 lindenbp fg0073 131M Oct  2 16:59 chr11.fa
-rw-r--r--. 1 lindenbp fg0073 130M Oct  2 17:21 chr12.fa
-rw-r--r--. 1 lindenbp fg0073 112M Oct  2 18:29 chr13.fa
-rw-r--r--. 1 lindenbp fg0073 105M Oct  2 15:50 chr14.fa
-rw-r--r--. 1 lindenbp fg0073 100M Oct  2 16:35 chr15.fa
-rw-r--r--. 1 lindenbp fg0073  88M Oct  2 17:45 chr16.fa
-rw-r--r--. 1 lindenbp fg0073  79M Oct  2 18:29 chr17.fa
-rw-r--r--. 1 lindenbp fg0073  76M Oct  2 15:50 chr18.fa
-rw-r--r--. 1 lindenbp fg0073  58M Oct  2 16:59 chr19.fa
-rw-r--r--. 1 lindenbp fg0073 242M Oct  2 17:45 chr1.fa
-rw-r--r--. 1 lindenbp fg0073  62M Oct  2 18:08 chr20.fa
-rw-r--r--. 1 lindenbp fg0073  47M Oct  2 17:21 chr21.fa
-rw-r--r--. 1 lindenbp fg0073  50M Oct  2 16:35 chr22.fa
-rw-r--r--. 1 lindenbp fg0073 236M Oct  2 16:59 chr2.fa
-rw-r--r--. 1 lindenbp fg0073 192M Oct  2 16:13 chr3.fa
-rw-r--r--. 1 lindenbp fg0073 186M Oct  2 18:50 chr4.fa
-rw-r--r--. 1 lindenbp fg0073 176M Oct  2 16:59 chr5.fa
-rw-r--r--. 1 lindenbp fg0073 166M Oct  2 16:59 chr6.fa
-rw-r--r--. 1 lindenbp fg0073 155M Oct  2 16:13 chr7.fa
-rw-r--r--. 1 lindenbp fg0073 142M Oct  2 18:50 chr8.fa
-rw-r--r--. 1 lindenbp fg0073 137M Oct  2 17:45 chr9.fa
-rw-r--r--. 1 lindenbp fg0073 151M Oct  2 18:29 chrX.fa
-rw-r--r--. 1 lindenbp fg0073  58M Oct  2 15:27 chrY.fa
-rw-r-----. 1 lindenbp fg0073    0 Oct  3 12:06 ref.list
```

and the heads `head -n 2 /path/to/REF/*.fa`

```
==> /path/to/REF/chr10.fa <==
>chr10
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr11.fa <==
>chr11
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr12.fa <==
>chr12
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr13.fa <==
>chr13
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr14.fa <==
>chr14
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr15.fa <==
>chr15
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr16.fa <==
>chr16
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr17.fa <==
>chr17
AAGCTTCTCACCCTGTTCCTGCATAGATAATTGCATGACAATTGCCTTGTCCCTGCTGAA

==> /path/to/REF/chr18.fa <==
>chr18
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr19.fa <==
>chr19
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr1.fa <==
>chr1
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr20.fa <==
>chr20
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr21.fa <==
>chr21
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr22.fa <==
>chr22
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr2.fa <==
>chr2
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr3.fa <==
>chr3
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr4.fa <==
>chr4
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr5.fa <==
>chr5
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr6.fa <==
>chr6
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr7.fa <==
>chr7
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr8.fa <==
>chr8
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chr9.fa <==
>chr9
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chrX.fa <==
>chrX
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

==> /path/to/REF/chrY.fa <==
>chrY
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```

in the BAM header :

```
@SQ	SN:chr1	LN:249250621
@SQ	SN:chr2	LN:243199373
@SQ	SN:chr3	LN:198022430
@SQ	SN:chr4	LN:191154276
@SQ	SN:chr5	LN:180915260
@SQ	SN:chr6	LN:171115067
@SQ	SN:chr7	LN:159138663
@SQ	SN:chr8	LN:146364022
@SQ	SN:chr9	LN:141213431
@SQ	SN:chr10	LN:135534747
(...)
```

size of chr1:
```
$ grep -v '^>' /path/to/REF/chr1.fa | tr -d '\n\r' | wc -c
249250621
```

my processes run in parallel (~100 bams, chroms chr1->chrX), I've got a bunch of interleaved messages (see below) in stderr:

```
(...)
Can't open file with chromosome sequence.
No chromosome/contig information parsed.
Sequence length (0) is different from expectation (59373566) for 'chrY'.
Doing nothing!
No histogram with GC content for 'chrY' found.
No correction made.
Can't find GC-content histogram for 'chrY'.
Reading calls ...
#executed by process	48 in 619.171s	with status	0 : JETER/targets.bash 2533
Can't open file with chromosome sequence.
No chromosome/contig information parsed.
Sequence length (0) is different from expectation (141213431) for 'chr9'.
Doing nothing!
No histogram with GC content for 'chr9' found.
No correction made.
Can't find GC-content histogram for 'chr9'.
Reading calls ...
#executed by process	27 in 734.289s	with status	0 : JETER/targets.bash 818
Can't open file with chromosome sequence.
No chromosome/contig information parsed.
Sequence length (0) is different from expectation (155270560) for 'chrX'.
Doing nothing!
No histogram with GC content for 'chrX' found.
No correction made.
Can't find GC-content histogram for 'chrX'.
Reading calls ...
#executed by process	4 in 867.237s	with status	0 : JETER/targets.bash 607
Can't open file with chromosome sequence.
No chromosome/contig information parsed.
Sequence length (0) is different from expectation (198022430) for 'chr3'.
Doing nothing!
No histogram with GC content for 'chr3' found.
(...)
```

**Comment by abyzov** [comment]
Great. I believe it was not finding .fa files so parsed sequence length was (0).

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by sunbacteria** [comment]
> Yes, the software requires .fa file for each chromosome. Alexej Abyzov, Ph.D. Senior Associate Consultant, Assistant Professor of Biomedical Informatics, Department of Health Sciences Research, Center for Individualized Medicine, Mayo Clinic ----------------------------- Mayo Clinic, Harwick 3-12 200 1st street SW, Rochester, MN 55905 tel: +1-(507)-538-0978 fax: +1-(507)-284-0745

Hi,
I am trying to use cnvnator for CNV calling with WGS data, and i want to get CNVs across the whole genome. I wondered if it is necessary for me to seperate a single fasta file of whole genome to several fasta files of each chromosome or I just need to provide the fasta file of the whole genome directly?
