### ISSUE TITLE
how to change the default cache folder

### ISSUE THREAD

**Issue by ioanacut** [abyzovlab/CNVnator#76]
Hello,
I am trying to run CNVnator directly on cram files and for that it looks like it needs a large space cache which by default is in the home directory. However I don't have enough space there so I would like to change the location of the cache. Is there any way I can do that?
Thanks!

**Comment by abyzov** [comment]
Hi,
not sure what you are asking. Is cache problem related to conversion from cram to bam or to running CNVnator?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by ioanacut** [comment]
Hi,
I guess it must be related to the conversion from cram to bam that CNVnator performs, as the problem doesn't occur when running it on a bam file. But this is related to how CNVnator deals with cram files, if I run myself separately cram2bam I don't have this problem. I am not sure if CNVnator calls another tool to do this conversion or does its own on the fly conversion, but I thought the location of the cache folder used during the conversion should be configurable, that's why I was asking how to change it. Any details on how CNVnator deals with this conversion would be appreciated, maybe I can figure how to change the default cache location.
Thank you,
Ioana

**Comment by abyzov** [comment]
Hi,
this feature was contributed by one of the users. Please see the following thread
https://github.com/abyzovlab/CNVnator/issues/33
CNVnator uses build in option in samtools to open cram files.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by ernfrid** [comment]
You ought to be able to adjust this with environment variables. See the section labeled "The REF_PATH and REF_CACHE" on this page http://www.htslib.org/workflow/

**Comment by ioanacut** [comment]
Thank you!
