### ISSUE TITLE
CNVnator for multiple samples

### ISSUE THREAD

**Issue by zhang248** [abyzovlab/CNVnator#77]
Hi,
I want to use CNVnator to call CNV for multiple. Should I use the "-merge" parameter or not. If I can use "-merge", which step should I use. And if I should just call CNV for multiple samples separately, how can I merge the multiple outputs or if you can  recommend me some tools? Thanks!

**Comment by zhang248** [comment]
Now, I know CNVnator can only call CNVs one sample at a time. And I know generally people merge two CNVs if they have >50% (or other ratio) reciprocal overlap. Now, the problem is when I have three or more samples, which two sampls should I merge first , and I think this should make a difference to overlap the merged CNV with the third sample.

**Comment by abyzov** [comment]
Hi,
this is generally an unsolved problem. There is currently no solution for it implemented in CNVnator.
Reading Mills et al., Nature, 2011 could be helpful to see one possible solution.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by zhang248** [comment]
Thank you! I'll try.

**Comment by zhang248** [comment]
Thank you! I'll try.
