### ISSUE TITLE
CNVnator output filter

### ISSUE THREAD

**Issue by zhang248** [abyzovlab/CNVnator#78]
Hi, I'm using CNVnator to call CNVs. I have 30 samples, and the "duplication" of all the outputs has no one with e-val1<0.05. This is my pipeline

    cnvnator -root temp/${sample}.root -unique -tree $bam

    cnvnator -root temp/${sample}.root -his $bin -d $dir

    cnvnator -root temp/${sample}.root -stat $bin

    cnvnator -root temp/${sample}.root -partition $bin

    cnvnator -root temp/${sample}.root -call $bin > ${sample}_cnv.txt

Can anyone tell me why? Thanks!

**Comment by 54tuifeimo** [comment]
I am also doing the CNV, can you add my wechat: tuifeimo. Thx!

**Comment by abyzov** [comment]
May be you bin size is inappropriate, i.e., too small?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by zhang248** [comment]
I reset the bin size 3500 with "-eval" output is 4.19188, but it doesn't work. This are the 5 samllest e-val1 : 
0.869204
1.25188
1.25365
1.25453
1.25543

**Comment by abyzov** [comment]
Do you have small eval2? CNVnator reports call if either of eval1 or eval2 is significant.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
