### ISSUE TITLE
The results of bin

### ISSUE THREAD

**Issue by 54tuifeimo** [abyzovlab/CNVnator#79]
Hi! I want to choose the best bin value. However, I used option ‘-eval’ and got the following results. Could you explain why the bin (X,Y) is 0. Thanks!

Average RD per bin (1-22) is 17.1245 +- 5.42047 3.15923
Average RD per bin (X,Y)  is 0 +- 0 -nan

**Comment by abyzov** [comment]
Are you sure there are reads mapped to chromosomes X and Y?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by 54tuifeimo** [comment]
I set the binsize 400.

During the HISTOGRAM step and doing the alignment using bwa-mem, the chromsome names were not reassigned as chromosomes X and Y or chr X and Y. The chromosome names were just the same as in the genome reference before, like CM000830.5 and LT634572.1. So, the two names can be recognized as chr X and Y when running CNVnator?

Another question, I am dong the pig genome, there are only 18 pairs of chromosomes, why the results shows 1-22 in the first line as following?
Average RD per bin (1-22) is 17.1245 +- 5.42047 3.15923
Average RD per bin (X,Y) is 0 +- 0 -nan

**Comment by 54tuifeimo** [comment]
I checked the bam, there are reads mapped to chromosomes X and Y.

**Comment by abyzov** [comment]
Hi,
CNVnator wan’t recognize chromosomes as X and Y if they are named like CM000830.5 and LT634572.1
I would propose to create two root files: one for diploid and one for haploid chromosomes.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by 54tuifeimo** [comment]
If I create two roof files, then the bin of chrom XY is still set as the autosomes? and the results of the call step of the chrom XY will be filtered by the same eavl1, eval2 and q0? Thanks!

**Comment by abyzov** [comment]
If X&Y have one copy you may need to increase bin size. Also, I think it would make sense to filter calls by RD < 0.5.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745



On Sep 15, 2017, at 1:19 AM, 54tuifeimo <notifications@github.com<mailto:notifications@github.com>> wrote:


If I create two roof files, then the bin of chrom XY is still set as the autosomes? and the results of the call step of the chrom XY will be filtered by the same eavl1, eval2 and q0? Thanks!

**Comment by 54tuifeimo** [comment]
Now I renamed sex chromosomes as X and Y to get a new bam file to be analyzed by CNVnator.  There are some new problems for my WGS data(~30x, PE150).

Q1.  Should the both Average RD per bin (1-22) and bin(X,Y) are around 4~5? I set bin 200, 250, 300 and got the results, which one is better?
bin 200
Average RD per bin (1-22) is 41.3227 +- 9.39843 4.39677
Average RD per bin (X,Y)  is 41.6417 +- 11.0545 3.76695
bin 250
File A14002.root
Average RD per bin (1-22) is 51.6905 +- 11.0338 4.68474
Average RD per bin (X,Y)  is 52.3344 +- 13.1831 3.96981
bin 300
File A14002.root
Average RD per bin (1-22) is 60.7361 +- 12.2388 4.96257
Average RD per bin (X,Y)  is 63.3473 +- 14.9964 4.22417

Q2.  For the male sample, one has X and Y, which is one copy respectively. For the female sample, one only has X with two copies, but the CNVnator could produce results of X and Y. I can filter results of Y  for female sample. However, is the Average RD per bin(X,Y) for male and female one different ? So how analysis CNV for the males, should I do analysis on Y seperately?

**Comment by abyzov** [comment]
Hi,
based on RD in XY CNVnator determines gender and adjusts calling.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
