### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by boboppie** [abyzovlab/CNVnator#8]
Dear @bintriz ,

I've noticed that **src/samtools** directory is not included in the release, thus I got an error:

```
g++ -O3 -DCNVNATOR_VERSION=\"v0.3.1\" -fopenmp -o cnvnator obj/cnvnator.o obj/HisMaker.o obj/AliParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a -lz -L/lib -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lMatrix -lPhysics -lMathCore -lThread -lGui
g++: error: samtools/libbam.a: No such file or directory
```

Is there a fix for this? A workaround could be that I compile samtools source code and manually move libbam.a to cnvnator, but it doesn't sound like an elegant solution. 

Best wishes,
Fengyuan

**Comment by bintriz** [comment]
Hi Fengyuan,

You should download and compile CNVnator_v0.3.1.zip. It is distribution source ready to compile and includes the samtools source compatible with CNVnator. Other two sources are just zipped git source. 

Thanks,
Taejeong

**Comment by boboppie** [comment]
Hi Taejeong,

I can't see samtools source in this package - https://github.com/abyzovlab/CNVnator/releases/download/v0.3.1/CNVnator_v0.3.1.zip

Best wishes,
Fengyuan

**Comment by bintriz** [comment]
I fixed it. Please download it again and try.

Thanks

**Comment by boboppie** [comment]
Thanks! It's working now.

**Comment by VivekTodur** [comment]
Hi Taejeong,

I am getting error like below while installing,

HisMaker.cpp: In member function ‘int HisMaker::extract_pe(TString, std::string*, int, double, double, bool, int*)’:
HisMaker.cpp:552: error: ‘map’ was not declared in this scope
HisMaker.cpp:552: error: expected primary-expression before ‘,’ token
HisMaker.cpp:552: error: expected primary-expression before ‘int’
HisMaker.cpp:552: error: expected ‘;’ before ‘int’
HisMaker.cpp:561: error: ‘qual_hash’ was not declared in this scope
HisMaker.cpp:612: error: expected primary-expression before ‘,’ token
HisMaker.cpp:612: error: expected primary-expression before ‘int’
HisMaker.cpp:612: error: expected ‘;’ before ‘int’
HisMaker.cpp:613: error: ‘iter’ was not declared in this scope
make: *** [obj/HisMaker.o] Error 1

What could be the issue????

**Comment by bintriz** [comment]
Dear Vivek,

Which release version of CNVnator did you try? Only v0.3.2 is compatible with root6. For v0.3.1, you should install root5.

Thanks,
