### ISSUE TITLE
How long to run the step of genotype

### ISSUE THREAD

**Issue by 54tuifeimo** [abyzovlab/CNVnator#80]
I called the CNV, then did the genotype. However, there is nothing coming out  when I have already run the step for 3 days. The data only 5x depth of the genome. Could you tell me how long to run the step of genotype? Thank you!

The genotype step:  ./cnvnator -root file.root -genotype 100

In addition, when I use cnvnator2VCF.pl to convert the call.out to vcf file, I found there was the result of GT(genotype) and GN(Copy number genotype for imprecise events) in the VCF file. So, should I do the genotype step?

##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=CN,Number=1,Type=Integer,Description="Copy number genotype for imprecise events">
##FORMAT=<ID=PE,Number=1,Type=Integer,Description="Number of paired-ends that support the event">

CM000812.5 31674101 CNVnator_del_225 t . PASS END=31675200;SVTYPE=DEL;SVLEN=-1100;IMPRECISE;natorRD=0.183451;natorP1=0.335032;
natorP2=0.00415032;natorP3=1;natorP4=1;natorQ0=0.0273973 GT:CN 1/1:0

CM000812.5 1302101 CNVnator_del_38 T . PASS END=1302700;SVTYPE=DEL;SVLEN=-600;IMPRECISE;natorRD=0;natorP1=0.0439157;natorP2=7.05437e-18;natorP3=1;natorP4=1;natorQ0=0 GT:CN 1/1:0

CM000812.5 35371701 CNVnator_dup_235 a . PASS END=35376100;SVTYPE=DUP;SVLEN=4400;IMPRECISE;natorRD=1.96751;natorP1=0.027545;na
torP2=2.31116e+07;natorP3=212.629;natorP4=2.06891e+08;natorQ0=0.604298 GT:CN ./1:2

CM000827.5 27771501 CNVnator_dup_14855 T . PASS END=27775000;SVTYPE=DUP;SVLEN=3500;IMPRECISE;natorRD=3.56099;natorP1=0.000151554;natorP2=2.83388e+09;natorP3=10.2211;natorP4=2.85503e+09;natorQ0=0.136969 GT:CN ./1:4

**Comment by 54tuifeimo** [comment]
In addition, when I use  cnvnator2VCF.pl to convert the call.out to  vcf file, I found there was the result of GT(genotype) and GN(Copy number genotype for imprecise events) in the VCF file. So, should I do the genotype step?

`##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=CN,Number=1,Type=Integer,Description="Copy number genotype for imprecise events">
##FORMAT=<ID=PE,Number=1,Type=Integer,Description="Number of paired-ends that support the event">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  WZS01_call
CM000812.5      193201  CNVnator_del_1  A       <DEL>   .       PASS    END=194800;SVTYPE=DEL;SVLEN=-1600;IMPRECISE;natorRD=0.121174;natorP1=9.6518e-06;natorP2=8.77673e
-17;natorP3=1;natorP4=1;natorQ0=0       GT:CN   1/1:0
CM000812.5      198701  CNVnator_del_2  C       <DEL>   .       PASS    END=200700;SVTYPE=DEL;SVLEN=-2000;IMPRECISE;natorRD=0.178922;natorP1=4.85369e-06;natorP2=0.00267
468;natorP3=1;natorP4=1;natorQ0=0       GT:CN   1/1:0
CM000812.5      226101  CNVnator_del_3  T       <DEL>   .       PASS    END=227700;SVTYPE=DEL;SVLEN=-1600;IMPRECISE;natorRD=0.362929;natorP1=0.0120182;natorP2=0.0366221
;natorP3=1;natorP4=1;natorQ0=0  GT:CN   0/1:1
CM000812.5      232901  CNVnator_del_4  T       <DEL>   .       PASS    END=234100;SVTYPE=DEL;SVLEN=-1200;IMPRECISE;natorRD=0.148934;natorP1=0.000526757;natorP2=3.86706
e-16;natorP3=1;natorP4=1;natorQ0=0.2    GT:CN   1/1:0
CM000812.5      392701  CNVnator_del_5  C       <DEL>   .       PASS    END=393400;SVTYPE=DEL;SVLEN=-700;IMPRECISE;natorRD=0.0791561;natorP1=17.0772;natorP2=0.0154227;n
atorP3=1;natorP4=1;natorQ0=0    GT:CN   1/1:0
CM000812.5      394101  CNVnator_del_6  c       <DEL>   .       PASS    END=396700;SVTYPE=DEL;SVLEN=-2600;IMPRECISE;natorRD=0.451343;natorP1=0.000561064;natorP2=1.11948
e+09;natorP3=284.909;natorP4=9.40107;natorQ0=0  GT:CN   0/1:1
CM000812.5      437401  CNVnator_del_7  T       <DEL>   .       PASS    END=443000;SVTYPE=DEL;SVLEN=-5600;IMPRECISE;natorRD=0.149934;natorP1=2.84594e-11;natorP2=1.09781
e-15;natorP3=4.42701e-11;natorP4=5.76853e-07;natorQ0=0.527778   GT:CN   1/1:0
CM000812.5      479601  CNVnator_del_8  A       <DEL>   .       PASS    END=485100;SVTYPE=DEL;SVLEN=-5500;IMPRECISE;natorRD=0.23615;natorP1=2.89768e-11;natorP2=1.08693e
+06;natorP3=4.5535e-11;natorP4=1.90768e+07;natorQ0=0.0842697    GT:CN   0/1:1
CM000812.5      540701  CNVnator_del_9  C       <DEL>   .       PASS    END=541000;SVTYPE=DEL;SVLEN=-300;IMPRECISE;natorRD=0;natorP1=2372.66;natorP2=0.000142313;natorP3
=1;natorP4=1;natorQ0=0  GT:CN   1/1:0
CM000812.5      555501  CNVnator_del_10 G       <DEL>   .       PASS    END=558000;SVTYPE=DEL;SVLEN=-2500;IMPRECISE;natorRD=0.177642;natorP1=1.84872e-09;natorP2=6.49957
e-11;natorP3=1.52398;natorP4=1.92038e-13;natorQ0=0      GT:CN   1/1:0
`

**Comment by abyzov** [comment]
For genotyping you actually have to type in region when prompted. But you can also genotype multiple regions but automatically. See tips at the end of README file.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by bioming** [comment]
I run cnvnator with fish pooled female and male mate pair reads to expect CNV differences between the two sex. when I run genotype and I did give the region of chromsome, but still nothing come out. 
here is my command: 
"cnvnator -root $outdir/male.root -chrom NC_030419.1:1-34595840 -genotype 100 > $outdir/male.genoout.txt"
Could you indicate the problem I met?
By the way, you suggest us to sort the list of region for chromosome, but I confused how to sort a root file!! Could you give me some suggestions?
 Thanks!

**Comment by abyzov** [comment]
Hi,
you have to do the following: n
1) enter cnvnator -root $outdir/male.root  -genotype 100
2) when NC_030419.1:1-34595840 you have a prompt

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On Nov 21, 2018, at 3:06 AM, ming wen <notifications@github.com<mailto:notifications@github.com>> wrote:


I run cnvnator with fish pooled female and male mate pair reads to expect CNV differences between the two sex. when I run genotype and I did give the region of chromsome, but still nothing come out.
here is my command:
"cnvnator -root $outdir/male.root -chrom NC_030419.1:1-34595840 -genotype 100 > $outdir/male.genoout.txt"
Could you indicate the problem I met?
By the way, you suggest us to sort the list of region for chromosome, but I confused how to sort a root file!! Could you give me some suggestions?
Thanks!
