### ISSUE TITLE
Segmentation fault when running partition step

### ISSUE THREAD

**Issue by lixin4306ren** [abyzovlab/CNVnator#82]
The command I used:
```
cnvnator -root out.root -chrom chr1 -partition 1000
```
Got error information very quickly:
```
Partitioning RD signal for 'chr1' with bin size of 1000 ...
Average RD per bin is 93.7653 +- 18.1172
Bin band is 2
Segmentation fault (core dumped)
```

**Comment by abyzov** [comment]
Hi,
it is hard to figure out what is going on. Could you provide extended segmentation fault message?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
