### ISSUE TITLE
valid genome problem

### ISSUE THREAD

**Issue by jamo888** [abyzovlab/CNVnator#84]
Hi!

I run CNVnator  using docker. 
Every time I try to run CNVnator with a test human bam file, I get this message: Valid genomes (-genome option) are: NCBI36, hg18, GRCh37, hg19. 
I used samtools 1.19 and slso samtools 1.3 but it was the same massage. 
can you please point me in the right direction?

Thanks for your help
Jamal

**Comment by abyzov** [comment]
Not sure. What is the command you are trying to run?
But generally you don’t need to specify ref genome if you are using bams, as cnvnator will take description of genome form bam header.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
