### ISSUE TITLE
Add the  chrom  or not?

### ISSUE THREAD

**Issue by AJ211** [abyzovlab/CNVnator#85]
Hi,
   I am  thinking about this question  recently:  My genome file has  scaffolds ,but I want to filter these CNVs who located in the scaffods. I have thought  two  ways to solve the  question:
   the first way like this:
         cnvnator  -root   file.root  -tree   file.bam   -unique   -chrom   chr1  chr2  ch3 ... chr28
   the second:
         cnvnator  -root   file.root  -tree   file.bam   -unique  （has no  chrom  parameter），and after  runned  the  cnvnator , I  filter these  CNV  on  scaffolds  by myself. That is , I run the cnvnator in the whole-genome  scale, but after getting the cnv result, I  abandon  the CNVs  on the  scaffold.
   I test the two  methods ,which can  get different results,So  which one way should I choose?
 Thank you very much !

**Comment by abyzov** [comment]
I would suggest the following

cnvnator -root file.root -tree file.bam -unique
cnvnator -root file.root -his bin -d dir -chrom chr1 chr2 ch3 ... chr28

then continue as usual.

This way you’ll initial processing for all chroms and scaffolds in case you ever need to reanalyze the data.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by AJ211** [comment]
Ok , thank you very much. but  the  next  steps should  like this:
cnvnator -root file.root -stat  bin  -chrom chr1 chr2 chr3 ... chr28 ，or   cnvnator -root file.root -stat bin ?
and  because  my  each  population  have  three  biological repeats. So, should  I  merged the .bam  files  before ran the  CNVnator,or  I run  each  sample,and  merged  them  to  a  population after  CNVnator?

**Comment by AJ211** [comment]
I test  your suggestion,and I  have done this  steps:
cnvnator -root file.root -tree file.bam -unique 
cnvnator -root file.root -his bin -d dir 
cnvnator -root file.root  -stat  bin
cnvnator -root  file.root  -partiton  bin
cnvnator  -root  file.root  -call  bin   >cnv_reuslt
grep -v  "scaffold"   cnv_result    >cnv_no_scaffold_result
and I also test the another way:
cnvnator -root file.root -tree file.bam -unique 
cnvnator -root file.root -his bin -d dir -chrom chr1 chr2 ch3 ... chr28
cnvnator -root file.root -stat bin -chrom chr1 chr2 ch3 ... chr28
cnvnator -root file.root -partiton bin -chrom chr1 chr2 ch3 ... chr28
cnvnator -root file.root -call  bin  chr1 chr2 ch3 ... chr28    >cnv_result
and  the second  strategy's  result have no scaffold.
but I  compare the two methods,and find  there are a little  differences, So which one is more  crediable,and  why  there are differences ? I  try to  understand  your article ,but  I  can't  find  the  answer. Besides, when I  use the  -genotype, I found  the  copy number  may be   '0' ,so  why  ?

**Comment by abyzov** [comment]
Either way should be good. When specifying chromosomes 1-28, the software does not consider scaffolds, so estimates of average and sd of RD are slightly different. So, are the results.
“0” genotype mean homozygous deletion.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by abyzov** [comment]
It depends on what you want to do. If you want higher coverage then you should merge 3 bams:
cnvantor -root file.root -tree file1.bam file2.bam file3.bam

If you need to check replicability then analyzed each bam individually.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
