### ISSUE TITLE
Average of RD signal to Std Deviation 4-5

### ISSUE THREAD

**Issue by bhuwankhatri11** [abyzovlab/CNVnator#86]
Hi,
1) How can we determine the ratio of average of RD signal to std dev and adjust to range 4-5?
2) How can we estimate the copy number variation of a certain region of a chromosome after running cnvnator analysis?
3) Can we filter the cnvnator output on the basis of e-val2, e-val3, e-val4, and copy number variation itself besides e-val1 and q0? If yes, what are the better criteria?

**Comment by AJ211** [comment]
Hello, I want to share my  experiences.
First, how to set the  bin-size(range 4-5),steps as follow:
   1.cnvnator -root  file.root  -tree  file.bam   -unique
   2. cnvnator -root  file.root  -d   fasta_dir/    -his    100 or  200 or   300  or   larger
   3.  cnvnator  -root  file.root  -stat   100 or  200 or   300  or   larger
  4.  cnvnator -root  file.root   -eval    100 or  200 or   300  or   larger
   after  the four  steps  , cnvnator can give you some  information,like  this:
  Average RD per bin (1-22) is 77.0091 +- 15.5122 4.96443
  Average RD per bin (X,Y)  is 0 +- 0 -nan
  the value :4.96443  is  between  4-5, so it's ok.  to get a perfect value, we need to try it  some times.
Second,  calculate the copy number (not copy number variation):  it's  useful  to use  the   -genotype  parameter.
Third, filtering the  CNV :  use the  eval 1   and   q0 .mostly   eval 1  <0.01  or  0.05  and  q0 <0.5  copy number  can't be  filterd.
 I think you may not understand the  copy number and copy number variation.the  cnvnator output is copy number variation infomration,and if you want to calculate  the copy number in some region( include copy number variation),you should use  -genotype parameter.

**Comment by bhuwankhatri11** [comment]
Hi AJ211,
Thank you for answers!
using -genotype parameter, I got output like this. Are the numbers in the last column copy number variation? 
Genotype chr10:34801-39600 test_1200_HS1_cja.root 0.0774924 -1
Genotype chr10:42001-45600 test_1200_HS1_cja.root 0.158772 -1
Genotype chr10:163201-170400 test_1200_HS1_cja.root 0.037992 -1
Genotype chr10:174001-178800 test_1200_HS1_cja.root 0.0356134 -1
Genotype chr10:199201-223200 test_1200_HS1_cja.root 4.2007 -1
Genotype chr10:247201-250800 test_1200_HS1_cja.root 0 -1
Genotype chr10:1736401-1942800 test_1200_HS1_cja.root 1.45973 -1
Genotype chr10:5662801-5665200 test_1200_HS1_cja.root 0 -1
Genotype chr10:6876001-6895200 test_1200_HS1_cja.root 0.955501 -1
Genotype chr10:10852801-10868400 test_1200_HS1_cja.root 1.01734 -1

One more question:
How can we visualize a specified region? I am trying using command line mentioned in README but I do not get any output. I also tried ssh -X user@host option, it is not helping at all to me. Is there any way to visualize the specified region in unix?

**Comment by AJ211** [comment]
Hi,  
 the copy number value is the last second column, visualize : you can use the  -view parameter.and if you can't see it ,you can use the tool of  IGV.

**Comment by abyzov** [comment]
The last column is for genotypes with bins of 1kbp.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by abyzov** [comment]
Not sure but looks like the soft can’t allocate enough memory (may be stack)? Do you have some restrictions?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by bhuwankhatri11** [comment]
Hi Abyzov,
1. Are the copy number values in the second last column linear or log transformed? Would you please explain about those values?
2. Why the CNVnator gives genotype with 1kbp bins all times though is specify other bin like 100bp, 200bp, 1200bp or 1500bp?

**Comment by fatcc** [comment]
Hi abyzov,
I have a set of samples of targeted sequencing about 8M in chr22.  I am trying to set the bin-size (range 4-5) through changing the bin-size. But the max ratio (RD/sd) is ~3 with the bin size increased to 400.  When bin size was set to 500, only one CNV (covered the whole region of targeted sequence) was reported, which is abnormal.  Additionally, the average depth is about 70X.  

How can I  balance the bin-size and depth in targeted sequencing data to improve the reliability of CNV calling with CNVnator? 

Thanks a lot!

cc

**Comment by abyzov** [comment]
1. Those are estimates of copy number (CN).
2. Because this is how the software is written.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by abyzov** [comment]
CNVnator is designed for analysis of whole genome sequencing data.
Use it with targeted sequencing data at your own risk.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by 54tuifeimo** [comment]
Should be the both value of Average RD per bin (1-22) and Average RD per bin (X,Y)  between 4 ~ 5? Or only the Average RD per bin (1-22) reached is OK?

**Comment by abyzov** [comment]
Either way is fine.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by sgdavis1** [comment]
I'm having trouble hitting the target ratio of 4-5 with my WGS data while increasing my bin size to a level much higher than it appears most of your users have to specify. At bin size of 1000, I can hit a ratio of 3.96 (I stopped the analysis at this point). I guess what I am most curious about is: what is the reason my data requires this large bin size, is it read depth? My average RD is ~45x. Is this too low to accurately use your tool? On the other hand, is there a problem with using such a high bin size? Or do you think this indicates something wrong with my data?

**Comment by abyzov** [comment]
Hi,
there could be a problem with GC bias. Currently, the only was to inspect it is manual.
Open your .root file in browser (actually TBrowser) in ROOT, navigate to directory for your bins size (name as bin_XXX), and double click on the histogram rd_gc_XXX. Then inspect how strong is the bias.


Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
