### ISSUE TITLE
Cnvnator view interpretation

### ISSUE THREAD

**Issue by chirrie** [abyzovlab/CNVnator#88]
How does one interpret the view graph?  The green lines means? The  y axis?
![nnnn](https://user-images.githubusercontent.com/3356778/31958187-9d43ca2c-b8f9-11e7-82cc-1722f089e609.png)

![km](https://user-images.githubusercontent.com/3356778/31958227-bb112266-b8f9-11e7-8355-7850f8a496a4.png)

**Comment by abyzov** [comment]
y-axis is coverage, green line is segmentation

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by chirrie** [comment]
green line is segmentation.....meaning  the segment where their is changes implying CNV right?....so like the second picture will be right to say it is under Duplication and deletion at the same time?

**Comment by abyzov** [comment]
Not sure what you mean by "under duplication and deletion”.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by chirrie** [comment]
CNVnator is for detecting CNVs events (deletions and duplication's) . From my knowledge when the read  depth decreases abnormally then  might be a deletions and vice versa for duplication's.

So I am wondering if  I can  use the graph from -view command of CNVnator to view  duplications and deletions on a given  genomic position?

**Comment by abyzov** [comment]
Yes, you can visualize RD signal for deletions and duplications and any other regions in genome.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
