### ISSUE TITLE
CNVnator output and general PCR result

### ISSUE THREAD

**Issue by bhuwankhatri11** [abyzovlab/CNVnator#89]
Hi Aby,

My overall output from CNV analysis using CNVnator looks like:
```
CNV_type	Coordinates	CNV_size	Normalized_RD	e-val1	e-val2	e-val3	e-val4	q0	Copy_number(genotype)	Bin_size	Average RD per bin +-StDev
deletion	chr10:163201-170400	7200	0.0133316	9.99132E-05	2.67762E-22	0.999077	5.90442E-12	0.0828402	0.0266596	1200	78.1745 +- 17.0184 4.59353
deletion	chr10:1573201-2205600	632400	0.765589	4.39056E-09	2871000000	6.04857E-09	2871000000	0.00938821	1.53118	1200	78.1745 +- 17.0184 4.59353
duplication	chr10:12294001-12309600	15600	6.05531	1.74411E-07	0	1.04957E-05	0	0	12.11	1200	78.1745 +- 17.0184 4.59353
deletion	chr10:14281201-14361600	80400	0.698974	3.26278E-09	41330800	1.5216E-08	46908500	0.156352	1.39794	1200	78.1745 +- 17.0184 4.59353
deletion	chr10:17276401-17318400	42000	0.712259	0.000558046	2615040	0.00342452	3901430	0	1.4245	1200	78.1745 +- 17.0184 4.59353
deletion	chr10:17383201-17697600	314400	0.736426	5.0691E-13	431376	5.10809E-13	461361	0.00258112	1.47285	1200	78.1745 +- 17.0184 4.59353
deletion	chr11:344401-396000	51600	0.686759	2.91966E-06	93.5488	3.30346E-06	208.579	0.00184247	1.37349	1200	78.1745 +- 17.0184 4.59353
deletion	chr11:1207201-1256400	49200	0.67736	4.66456E-10	2652890	2.34632E-09	3730220	0.00241838	1.3547	1200	78.1745 +- 17.0184 4.59353
duplication	chr12:801601-846000	44400	8.30606	4.3648E-09	2870770000	4.36377E-09	2870780000	0.0253884	16.6119	1200	78.1745 +- 17.0184 4.59353
deletion	chr12:1348801-1467600	118800	0.714321	1.34152E-12	1003280000	1.36918E-12	1024820000	0	1.42864	1200	78.1745 +- 17.0184 4.59353
```
Depending upon my overall output, I have a couple of questions.
1. Do you think the output result is reliable for downstream analysis?
2. I selected a few (n=7) CNV regions and performed general PCR to detect deletion or duplication in test and control samples, but all the result appeared the same in gel image i.e. no deletions and duplications were detected in my 16 pairs of samples. However, I have not run qPCR to validate this analysis. Do you think I am doing something wrong here? 
Thank you.

**Comment by abyzov** [comment]
Hi,
output looks fine.
For PCR you need to know precise breakpoints. CNVnator relies on read depth analysis and resolution of breakpoints is ~2-3 bin sizes. So, it is possible that your primers don’t target real breakpoints.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by bhuwankhatri11** [comment]
Hi Aby,

Thank you for your response. I am understanding that I need to design primers 2-3 bin size away from beginning of CNV region. So if bin size for my sample is 1200, I should design primers 3*1200 bp far from start of CNV region. Am I right? Is there any reference that I can follow for primer design? Thank you.

**Comment by abyzov** [comment]
Yes, I think you are right. Not sure which reference you are talking about.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
