### ISSUE TITLE
Does CNVnator require a specific version of ROOT?

### ISSUE THREAD

**Issue by robinengler** [abyzovlab/CNVnator#9]
Dear @bintriz and @abyzov,

A short question regarding CNVnator's dependency on ROOT.
Are the latest versions of ROOT (>= 6.0) compatible with CNVnator or is a specific version of ROOT required?

I'm asking because I'm trying to compile CNVnator's with ROOT 6.04.00 and I run into a problem where the library « libCint.so » (the -lCint flag) is not found. My understanding is that this library is no longer available in ROOT 6.04.00 (but maybe I just did not install ROOT correctly).

Thank you and best regards,
Robin

g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.1\" -fopenmp -o cnvnator obj/cnvnator.o obj/HisMaker.o obj/AliParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o /software/UHTS/Analysis/samtools/1.2/lib64/libbam.a -lz -L/software/Development/root/6.04.00-minimal/lib/root//lib -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lMatrix -lPhysics -lMathCore -lThread -lGui
/software/bin/ld: cannot find -lCint

**Comment by robinengler** [comment]
After spending an afteroon trying to compile CINT (from ROOT) with my colleague @DrYak, we found that in fact CINT is not necessary to compile CNVnator with ROOT >= 6.00
To compile CNVnator with ROOT >= 6.00 you thus have to:

- remove the `-lCint` flag from the g++ link command in the `cnvnator: ` rule of the Makefile. This is because "libCint.so" is depreacted and no longer exists in ROOT >= 6.00
- add the `-std=c++11` flag to the g++ command

Another issue that I found is that the newer versions of samtools now have their static libraries ".a" split into two: libbam.a and libhts.a.
Both of these libraries must be referenced in the `SAMLIB` variable.

The following sed command fixes the 3 above-mentionned issues:

`
sed -r -i 's@-O3 -DCNVNATOR_VERSION@-std=c++11 \0@g;s@-lCint@@g;s@^SAMLIB = .*@\0 \$(SAMDIR)/libhts.a@' Makefile
`

**Comment by abyzov** [comment]
Dear Robin,
yes you are right.  ROOT 6.00 introduced some changes which made compilation of CNVnator not compatible with it. Thanks for resolving this! We will update the code in the coming days.

**Comment by bintriz** [comment]
Dear Robin,

I updated Makefile to be compatible with ROOT6 and samtools(>1.0). I uploaded the new release file (v0.3.2) reflecting these changes and including samtools-1.2 source in it. Thanks for giving tips to resolve compatibility issues.
