### ISSUE TITLE
The choice of the genome reference

### ISSUE THREAD

**Issue by 54tuifeimo** [abyzovlab/CNVnator#90]
Hi!
There were three kind of genome references in Ensembl. Some studies thought the segment duplications could influence the detection of CNV. So, should I choose the dna_rm or dna_sm as the reference for mapping the reads? Or the unmasked genomic DNA sequences is just ok? Thanks!

* 'dna' - unmasked genomic DNA sequences.
* 'dna_rm' - masked genomic DNA.  Interspersed repeats and low
     complexity regions are detected with the RepeatMasker tool and masked
     by replacing repeats with 'N's.
* 'dna_sm' - soft-masked genomic DNA. All repeats and low complexity regions
    have been replaced with lowercased versions of their nucleic base

**Comment by abyzov** [comment]
Hi,
you must you either ‘dna’ or ‘dna_sm’. If you use ‘dna_rm’ you’ll get abnormal read coverage across genome.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
