### ISSUE TITLE
I can't install the CNVnator

### ISSUE THREAD

**Issue by yuntwang** [abyzovlab/CNVnator#92]
Hi,
I download the v0.3.3 and install it.
The root package(v5.34.14):
**root -help**
Usage: root [-l] [-b] [-n] [-q] [dir] [[file:]data.root] [file1.C ... fileN.C]
Options:
  -b : run in batch mode without graphics
  -n : do not execute logon and logoff macros as specified in .rootrc
  -q : exit after processing command line macro files
  -l : do not show splash screen
  -x : exit on exception
 dir : if dir is a valid directory cd to it before executing

  -?       : print usage
  -h       : print usage
  --help   : print usage
  -config  : print ./configure options
  -memstat : run with memory usage monitoring

Samtools
Version: 1.3.1 (using htslib 1.3.1)
 
**I can install root and samtools but I encounter a question when compile **Makefile**.**
**make** 
Compiling with parallel (OpenMP) support
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.3\" -fopenmp -o cnvnator obj/cnvnator.o obj/EXOnator.o obj/HisMaker.o obj/AliParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a samtools/htslib-1.3.1/libhts.a -lz -L/share/nas2/genome/biosoft/root/current//lib/root  -lCore -lRIO -lHist -lGraf -lGpad -lTree -lMathCore
/usr/bin/ld: warning: libCint.so, needed by /share/nas2/genome/biosoft/root/current//lib/root/libCore.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libThread.so, needed by /share/nas2/genome/biosoft/root/current//lib/root/libRIO.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libMatrix.so, needed by /share/nas2/genome/biosoft/root/current//lib/root/libHist.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libNet.so, needed by /share/nas2/genome/biosoft/root/current//lib/root/libTree.so, not found (try using -rpath or -rpath-link)
obj/HisMaker.o: In function `HisMaker::HisMaker(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Genome*)':
…………………………
…………………………
**collect2: error：ld return 1
make: *** [cnvnator] error 1**

what is the reason about this question?
Hope to get your reply.
Thanks.

**Comment by abyzov** [comment]
Hi,
you probably didn’t set up ROOTSYS variable (see README).

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
