### ISSUE TITLE
Can't run cnvnator

### ISSUE THREAD

**Issue by yuntwang** [abyzovlab/CNVnator#94]

**Comment by abyzov** [comment]
Looks like ROOT is not able to display graphics. May be it is compiled incorrectly, or display is not set if you are connecting from a remote machine.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
