### ISSUE TITLE
Exome CNV

### ISSUE THREAD

**Issue by joseale2310** [abyzovlab/CNVnator#95]
Hi!

I suppose that CNVnator is not really the tool to do CNV in exome data, right?

Best,

Alex.

**Comment by abyzov** [comment]
Right.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by joseale2310** [comment]
Thank you very much! I thought I was doing something wrong! :)
