### ISSUE TITLE
error running CNVnator

### ISSUE THREAD

**Issue by madhubioinfo** [abyzovlab/CNVnator#96]
I Have installed root 6.12 and there was no problem with installation and I Have a version of CNVnator_v0.3.2 and am trying to run 

../src/cnvnator -root out.root  -chrom Ld05_v01s1 -tree dedup_group_added.bam

Iam getting the following error

Parsing file dedup_group_added.bam ...
Allocating memory ...
Done.
Filling and saving tree for 'Ld05_v01s1' ...
../src/cnvnator: symbol lookup error: ../src/cnvnator: undefined symbol: _ZN5TTreeC1EPKcS1_iP10TDirectory

**Comment by abyzov** [comment]
Hi,
could be related to a compile. Which one did you use?

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by MycrofD** [comment]
> I Have installed root 6.12 and there was no problem with installation and I Have a version of CNVnator_v0.3.2 and am trying to run
> 
> ../src/cnvnator -root out.root -chrom Ld05_v01s1 -tree dedup_group_added.bam
> 
> Iam getting the following error
> 
> Parsing file dedup_group_added.bam ...
> Allocating memory ...
> Done.
> Filling and saving tree for 'Ld05_v01s1' ...
> ../src/cnvnator: symbol lookup error: ../src/cnvnator: undefined symbol: _ZN5TTreeC1EPKcS1_iP10TDirectory

Did you solve the problem @madhubioinfo ? I am also solving similar issue. 
The issue is that even if root_numpy works with ROOT 6, it doesn't work with AliROOT 6. https://github.com/alisw/AliRoot
And gives the above mentioned error.
I checked $LD_LIBRARY_PATH, it does have the path to the ROOT installation. But somehow, it gives this error. Any idea how to recover?
I also raised this issue at https://github.com/abyzovlab/CNVnator/issues/122#issuecomment-423534464

**Comment by abyzov** [comment]
Hi,
this is strange.
Could you try setting up ROOT environment with their script

. path_to_ROOT/bin/thisroot.sh


Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by abyzov** [comment]
Hi,
we rarely use python interface. But seem like you found a way that works for you, and it is great.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
