### ISSUE TITLE
run cnvnator error

### ISSUE THREAD

**Issue by ytguojian** [abyzovlab/CNVnator#97]
Hi, 
I have installed the cnvnator, but it can not be run.
cnvnator.orig: /software/bioinformatics/cnvnator-0.3.3/glibc-2.14/lib/libc.so.6: version `GLIBC_2.17' not found (required by /lib64/libgomp.so.1)
cnvnator.orig: /software/bioinformatics/cnvnator-0.3.3/glibc-2.14/lib/libc.so.6: version `GLIBC_2.17' not found (required by /lib64/libssl.so.10)
cnvnator.orig: /software/bioinformatics/cnvnator-0.3.3/glibc-2.14/lib/libc.so.6: version `GLIBC_2.17' not found (required by /lib64/libcrypto.so.10)
cnvnator.orig: /software/bioinformatics/cnvnator-0.3.3/glibc-2.14/lib/libc.so.6: version `GLIBC_2.16' not found (required by /lib64/libkrb5.so.3)
cnvnator.orig: /software/bioinformatics/cnvnator-0.3.3/glibc-2.14/lib/libc.so.6: version `GLIBC_2.17' not found (required by /lib64/libcom_err.so.2)
I do not know how to resolve it. Could you help?
Cheers,

**Comment by abyzov** [comment]
Hi,
not sure but looks like some incompatibility between gcc version.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
